### ISSUE TITLE
Warning during Bungeecord loading

### ISSUE THREAD

**Issue by xSavior-of-God** [LuckPerms/LuckPerms#3203]
### Description

Hi, i encouraged this warnings at server boot:

22:41:23 [WARNING] Exception encountered when loading plugin: LuckyInjector
java.lang.RuntimeException: Failed to load relocated-netty-all-4.1.51.jar!
    at dev.luckynetwork.alviann.luckyinjector.helper.DependencyHelper.load(DependencyHelper.java:126)
    at dev.luckynetwork.alviann.luckyinjector.helper.DependencyHelper.load(DependencyHelper.java:204)
    at dev.luckynetwork.alviann.luckyinjector.loader.Loader.startInjecting(Loader.java:93)
    at dev.luckynetwork.alviann.luckyinjector.bungee.BungeeInjector.loadEarly(BungeeInjector.java:71)
    at dev.luckynetwork.alviann.luckyinjector.bungee.BungeeInjector.onEnable(BungeeInjector.java:34)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:252)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:450)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:32)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### Reproduction Steps

Literally I just boot my server and I see this warnings in console... this warnings doesn't stop my server or the plugin Luckperms (it's works as normal, for now).

### Expected Behaviour

Nothing special, just a warning in the console

### Server Details

Aegis 9.2.1 GENJUTSU 1.17.1

### LuckPerms Version

LuckPerms for bungeecord v5.3.74

### Logs and Configs

Logs           -> https://pastebin.com/ZtmY5dFa
Config.yml -> https://pastebin.com/ezULxN6u

### Extra Details

I opened this issue just to understand if it is a serious problem or not.
Thanks

**Comment by emilyy-dev** [comment]
The issue is with **LuckyInjector**, not LuckPerms, LP seems to be loading and working fine.
