### ISSUE TITLE
The server just won't start after I installed LuckPerms

### ISSUE THREAD

**Issue by Arko1994** [LuckPerms/LuckPerms#3216]
### Description

System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9) Host: Linux 4.15.0-161-generic (amd64) Loading libraries, please wait...
2021-11-24 13:32:58,594 main WARN Advanced terminal features are not available in this environment
[13:33:04 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:33:04 INFO]: Reloading ResourceManager: Default, bukkit
[13:33:05 INFO]: Loaded 7 recipes
[13:33:06 INFO]: Starting minecraft server version 1.17.1
[13:33:06 INFO]: Loading properties
[13:33:06 INFO]: This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
[13:33:06 INFO]: Server Ping Player Sample Count: 12
[13:33:06 INFO]: Using 4 threads for Netty based IO
[13:33:07 INFO]: Default game type: CREATIVE
[13:33:07 INFO]: Generating keypair
[13:33:07 INFO]: Starting Minecraft server on 176.57.155.64:25565
[13:33:07 INFO]: Using epoll channel type
[13:33:07 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
rate limit exceeded
[13:33:08 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[13:33:13 WARN]: Legacy plugin LuckPerms v5.3.77 does not specify an api-version.
[13:33:13 WARN]: Legacy plugin Dynmap-WorldGuard v1.2 does not specify an api-version.
[13:33:13 INFO]: [LuckPerms] Loading LuckPerms v5.3.77
[13:33:14 INFO]: [Vault] Loading Vault v1.7.3-b131
[13:33:14 INFO]: [Essentials] Loading Essentials v2.19.1-dev+34-5723dac
[13:33:14 INFO]: [dynmap] Loading dynmap v3.2.1-531
[13:33:14 INFO]: [dynmap] version=git-Paper-388 (MC: 1.17.1)
[13:33:14 INFO]: [dynmap] Mod Support API available
rate limit exceeded
[13:33:14 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@bc88397]
[13:33:15 INFO]: [LuckPerms] Loading storage provider... [H2]
[13:33:16 ERROR]: Error occurred while enabling LuckPerms v5.3.77 (Is it up to date?) java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/guava/graph/MutableGraph at me.lucko.luckperms.bukkit.util.PluginManagerUtil.injectDependency(PluginManagerUtil.java:64) ~[?:?] at me.lucko.luckperms.bukkit.LPBukkitPlugin.setupPlatformHooks(LPBukkitPlugin.java:226) ~[?:?] at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:187) ~[?:?] at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?] at me.lucko.luckperms.bukkit.loader.BukkitLegacyLoaderPlugin.onEnable(BukkitLegacyLoaderPlugin.java:51) ~[LuckPerms-Bukkit-Legacy-5.3.77.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-388] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-388] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-388] at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-388] at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-388] at java.lang.Thread.run(Unknown Source) ~[?:?] Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.guava.graph.MutableGraph at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] ... 14 more
[13:33:17 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[13:33:18 INFO]: Preparing start region for dimension minecraft:overworld
[13:33:19 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
rate limit exceeded
[13:33:19 INFO]: [dynmap] Mod Support processing completed
[13:33:21 INFO]: [dynmap] Disabled
[13:33:21 INFO]: [WorldGuard] Enabling WorldGuard v7.0.6+1cff55f
[13:33:22 ERROR]: This crash report has been saved to: /home/sid_3109285/minecraft_paper_117/./crash-reports/crash-2021-11-24_13.33.22-server.txt [13:33:22 INFO]: Stopping server
[13:33:23 FATAL]: Thread IO-Worker-1 failed main thread check: Chunk getEntities call java.lang.Throwable: null at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?] at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1737) ~[app:?] at net.minecraft.world.entity.NeutralMob.readPersistentAngerSaveData(NeutralMob.java:45) ~[app:?] at net.minecraft.world.entity.animal.Wolf.readAdditionalSaveData(Wolf.java:168) ~[app:?] at net.minecraft.world.entity.Entity.load(Entity.java:2229) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.world.entity.EntityType.lambda$create$2(EntityType.java:514) ~[app:?] at net.minecraft.Util.ifElse(Util.java:391) ~[app:?] at net.minecraft.world.entity.EntityType.create(EntityType.java:511) ~[app:?] at net.minecraft.world.entity.EntityType.loadStaticEntity(EntityType.java:602) ~[app:?] at net.minecraft.world.entity.EntityType.loadEntityRecursive(EntityType.java:545) ~[app:?] at net.minecraft.world.entity.EntityType$1.lambda$tryAdvance$1(EntityType.java:569) ~[app:?] at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source) ~[?:?] at net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:568) ~[app:?] at java.util.Spliterator.forEachRemaining(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?] at net.minecraft.world.level.chunk.storage.EntityStorage.lambda$loadEntities$0(EntityStorage.java:72) ~[patched_1.17.1.jar:git-Paper-388] at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?] at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:100) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.registerForExecution(ProcessorMailbox.java:127) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.tell(ProcessorMailbox.java:121) ~[app:?] at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?] at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.util.thread.ProcessorHandle.lambda$askEither$0(ProcessorHandle.java:28) ~[app:?] at net.minecraft.util.thread.ProcessorHandle$1.tell(ProcessorHandle.java:44) ~[app:?] at net.minecraft.world.level.chunk.storage.IOWorker.lambda$submitTask$10(IOWorker.java:129) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:90) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?] at java.lang.Thread.run(Unknown Source) ~[?:?]
[13:33:23 WARN]: Exception loading entity: net.minecraft.ReportedException: Loading entity NBT at net.minecraft.world.entity.Entity.load(Entity.java:2329) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.world.entity.EntityType.lambda$create$2(EntityType.java:514) ~[app:?] at net.minecraft.Util.ifElse(Util.java:391) ~[app:?] at net.minecraft.world.entity.EntityType.create(EntityType.java:511) ~[app:?] at net.minecraft.world.entity.EntityType.loadStaticEntity(EntityType.java:602) ~[app:?] at net.minecraft.world.entity.EntityType.loadEntityRecursive(EntityType.java:545) ~[app:?] at net.minecraft.world.entity.EntityType$1.lambda$tryAdvance$1(EntityType.java:569) ~[app:?] at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source) ~[?:?] at net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:568) ~[app:?] at java.util.Spliterator.forEachRemaining(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?] at net.minecraft.world.level.chunk.storage.EntityStorage.lambda$loadEntities$0(EntityStorage.java:72) ~[patched_1.17.1.jar:git-Paper-388] at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?] at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:100) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.registerForExecution(ProcessorMailbox.java:127) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.tell(ProcessorMailbox.java:121) ~[app:?] at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?] at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.util.thread.ProcessorHandle.lambda$askEither$0(ProcessorHandle.java:28) ~[app:?] at net.minecraft.util.thread.ProcessorHandle$1.tell(ProcessorHandle.java:44) ~[app:?] at net.minecraft.world.level.chunk.storage.IOWorker.lambda$submitTask$10(IOWorker.java:129) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:90) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?] at java.lang.Thread.run(Unknown Source) ~[?:?] Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call! at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?] at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1737) ~[app:?] at net.minecraft.world.entity.NeutralMob.readPersistentAngerSaveData(NeutralMob.java:45) ~[app:?] at net.minecraft.world.entity.animal.Wolf.readAdditionalSaveData(Wolf.java:168) ~[app:?] at net.minecraft.world.entity.Entity.load(Entity.java:2229) ~[patched_1.17.1.jar:git-Paper-388] ... 38 more
[13:33:24 WARN]: Exception loading entity: net.minecraft.ReportedException: Loading entity NBT at net.minecraft.world.entity.Entity.load(Entity.java:2329) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.world.entity.EntityType.lambda$create$2(EntityType.java:514) ~[app:?] at net.minecraft.Util.ifElse(Util.java:391) ~[app:?] at net.minecraft.world.entity.EntityType.create(EntityType.java:511) ~[app:?] at net.minecraft.world.entity.EntityType.loadStaticEntity(EntityType.java:602) ~[app:?] at net.minecraft.world.entity.EntityType.loadEntityRecursive(EntityType.java:545) ~[app:?] at net.minecraft.world.entity.EntityType$1.lambda$tryAdvance$1(EntityType.java:569) ~[app:?] at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source) ~[?:?] at net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:568) ~[app:?] at java.util.Spliterator.forEachRemaining(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?] at net.minecraft.world.level.chunk.storage.EntityStorage.lambda$loadEntities$0(EntityStorage.java:72) ~[patched_1.17.1.jar:git-Paper-388] at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?] at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:100) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.registerForExecution(ProcessorMailbox.java:127) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.tell(ProcessorMailbox.java:121) ~[app:?] at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?] at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.util.thread.ProcessorHandle.lambda$askEither$0(ProcessorHandle.java:28) ~[app:?] at net.minecraft.util.thread.ProcessorHandle$1.tell(ProcessorHandle.java:44) ~[app:?] at net.minecraft.world.level.chunk.storage.IOWorker.lambda$submitTask$10(IOWorker.java:129) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:90) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?] at java.lang.Thread.run(Unknown Source) ~[?:?] Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call! at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?] at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1737) ~[app:?] at net.minecraft.world.entity.NeutralMob.readPersistentAngerSaveData(NeutralMob.java:45) ~[app:?] at net.minecraft.world.entity.animal.Wolf.readAdditionalSaveData(Wolf.java:168) ~[app:?] at net.minecraft.world.entity.Entity.load(Entity.java:2229) ~[patched_1.17.1.jar:git-Paper-388] ... 38 more
rate limit exceeded
[13:33:25 WARN]: Exception loading entity: net.minecraft.ReportedException: Loading entity NBT at net.minecraft.world.entity.Entity.load(Entity.java:2329) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.world.entity.EntityType.lambda$create$2(EntityType.java:514) ~[app:?] at net.minecraft.Util.ifElse(Util.java:391) ~[app:?] at net.minecraft.world.entity.EntityType.create(EntityType.java:511) ~[app:?] at net.minecraft.world.entity.EntityType.loadStaticEntity(EntityType.java:602) ~[app:?] at net.minecraft.world.entity.EntityType.loadEntityRecursive(EntityType.java:545) ~[app:?] at net.minecraft.world.entity.EntityType$1.lambda$tryAdvance$1(EntityType.java:569) ~[app:?] at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source) ~[?:?] at net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:568) ~[app:?] at java.util.Spliterator.forEachRemaining(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?] at net.minecraft.world.level.chunk.storage.EntityStorage.lambda$loadEntities$0(EntityStorage.java:72) ~[patched_1.17.1.jar:git-Paper-388] at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?] at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:100) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.registerForExecution(ProcessorMailbox.java:127) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.tell(ProcessorMailbox.java:121) ~[app:?] at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?] at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.util.thread.ProcessorHandle.lambda$askEither$0(ProcessorHandle.java:28) ~[app:?] at net.minecraft.util.thread.ProcessorHandle$1.tell(ProcessorHandle.java:44) ~[app:?] at net.minecraft.world.level.chunk.storage.IOWorker.lambda$submitTask$10(IOWorker.java:129) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:90) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?] at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?] at java.lang.Thread.run(Unknown Source) ~[?:?] Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call! at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-388] at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?] at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1737) ~[app:?] at net.minecraft.world.entity.NeutralMob.readPersistentAngerSaveData(NeutralMob.java:45) ~[app:?] at net.minecraft.world.entity.animal.Wolf.readAdditionalSaveData(Wolf.java:168) ~[app:?] at net.minecraft.world.entity.Entity.load(Entity.java:2229) ~[patched_1.17.1.jar:git-Paper-388] ... 38 more
[13:33:27 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[13:33:30 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[13:33:30 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved [13:33:30 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:33:30 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved [13:33:30 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[13:33:31 INFO]: Flushing Chunk IO [13:33:31 INFO]: Closing Thread Pool
2021-11-24 13:33:31,044 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment
[13:33:31 INFO]: Closing Server

### Reproduction Steps

copy jar file in plugins folder

### Expected Behaviour

Expected to work

### Server Details

Paper 1.17.10

### LuckPerms Version

5.3.77

**Comment by ZeromaniacMc** [comment]
Hi there,
it appears you are getting the infamous 'NoClassDefFound' Error. This usually happens when dependencies for luckperms are missing. Those dependencies are located in `plugins/luckperms/libs`. If LP created a folder in your case, please shut down your server, delete the whole libs folder and start it back up. The libs folder `does not` hold any user or group data, so there is no need to worry about data loss.

**Comment by Arko1994** [comment]
Thank you!
