### ISSUE TITLE
Bunge ERROR loading LP

### ISSUE THREAD

**Issue by Krzychu4u** [LuckPerms/LuckPerms#3219]
### Description

While loading the server there is an error with LP loading

### Reproduction Steps

create FlameCord (0.6.4) servers and put LP in to FlameCord/plugin

### Expected Behaviour

 Positive loading of the plugin

### Server Details

Paper#388

### LuckPerms Version

v5.3.74

### Logs and Configs

[21:02:44 WARN]: Error loading plugin LuckPerms
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:374c895:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:374c895:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:374c895:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:435) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:374c895:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:341) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:374c895:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:298) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:374c895:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:374c895:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:374c895:unknown]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:374c895:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:374c895:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 13 more

**Comment by emilyy-dev** [comment]
You used the Bukkit version of the plugin on the proxy, download the correct jar file from https://luckperms.net/download

**Comment by Krzychu4u** [comment]
ohh i forgot that the bungee has a separate .jar 
Thanks!
