### ISSUE TITLE
H2 SQL Error After Latest Commit

### ISSUE THREAD

**Issue by Brad1944** [LuckPerms/LuckPerms#3225]
### Description

hi!, i was trying to setup my test server with luckperms installed, and when i joined the server, i got an error

"A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors."

I Have Tried Deleting The Luckperms Folder, And Got The Same Results

and here is the stacktrace
[11:39:25 INFO]: com.mojang.authlib.GameProfile@12fdd7f2[id=c69e33bf-a69e-34e3-9385-99cbfc6addd3,name=Afif87123,properties={},legacy=false] (/127.0.0.1:56913) lost connection: º7[ºbºlLº3ºlPº7]ºr ºcA database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
[11:48:10 ERROR]: [LuckPerms] Exception occurred whilst loading data for c69e33bf-a69e-34e3-9385-99cbfc6addd3 - Afif87123
java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO `LUCKPERMS_PLAYERS` (UUID, USERNAME, PRIMARY_GROUP) VALUES(?, ?, ?) ON[*] DUPLICATE KEY UPDATE USERNAME=?, PRIMARY_GROUP=? "; SQL statement:
INSERT INTO `luckperms_players` (uuid, username, primary_group) VALUES(?, ?, ?) ON DUPLICATE KEY UPDATE username=?, primary_group=? [42000-199]
        at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:93) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_231]
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO `LUCKPERMS_PLAYERS` (UUID, USERNAME, PRIMARY_GROUP) VALUES(?, ?, ?) ON[*] DUPLICATE KEY UPDATE USERNAME=?, PRIMARY_GROUP=? "; SQL statement:
INSERT INTO `luckperms_players` (uuid, username, primary_group) VALUES(?, ?, ?) ON DUPLICATE KEY UPDATE username=?, primary_group=? [42000-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:451) ~[?:?]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:205) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:181) ~[?:?]
        at org.h2.message.DbException.getSyntaxError(DbException.java:229) ~[?:?]
        at org.h2.command.Parser.getSyntaxError(Parser.java:989) ~[?:?]
        at org.h2.command.Parser.prepareCommand(Parser.java:686) ~[?:?]
        at org.h2.engine.Session.prepareLocal(Session.java:627) ~[?:?]
        at org.h2.engine.Session.prepareCommand(Session.java:565) ~[?:?]
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292) ~[?:?]
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77) ~[?:?]
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.file.NonClosableConnection.prepareStatement(NonClosableConnection.java:85) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:627) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:259) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:88) ~[?:?]
        ... 6 more

Server Info:
OS: Windows 10 Latest
Java: 1.8.0_231
MC Server Version: Paper 1.8.8
Online Mode = False

### Reproduction Steps

Install The Plugin, Join The Server

### Expected Behaviour

Not Getting Kicked Out

### Server Details

git-PaperSpigot-"4c7641d" (MC: 1.8.8)

### LuckPerms Version

5.3.81

### Logs and Configs

https://gist.github.com/Brad1944/2cfefcfd521e37c3289d885eb6319603

**Comment by underscore11code** [comment]
#3224

**Comment by Brad1944** [comment]
aight
