### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OSrLima** [LuckPerms/LuckPerms#3240]
### Description

15:53:34 [WARNING] Exception encountered when loading plugin: LuckPerms
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
    at me.lucko.luckperms.lib.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
    at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:115)
    at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:162)
    at me.lucko.luckperms.common.storage.Storage.init(Storage.java:117)
    at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
    at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:166)
    at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:168)
    at me.lucko.luckperms.bungee.loader.BungeeLoaderPlugin.onEnable(BungeeLoaderPlugin.java:51)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:310)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:43)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### Reproduction Steps

I put the database as MySQL and it gives this error...

### Expected Behaviour

The plugin does not start (BungeeCord), and keeps giving this error.

### Server Details

Aegis (1.8.9)

### LuckPerms Version

Bungee-5.3.89

**Comment by underscore11code** [comment]
Can you reproduce on normal Bungeecord? I've never heard of Aegis, but it sounds like some ""performance"" fork that's probably breaking things.

**Comment by lucko** [comment]
Unlikely to be a LuckPerms issue
