### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by ionutelul123** [LuckPerms/LuckPerms#3241]
### Description

Hi I Cant Connect to any of my server networks and I Get this error While Tring To connect to it.
Or Trying to import a config.

### Reproduction Steps

.

### Expected Behaviour

I wanted to import my permissions and to connect to the servers i imported too after i synced and stuff.

### Server Details

1.13.2 / 1.16.4 / 1.8.9

### LuckPerms Version

v5.3.70

### Logs and Configs

`lp import test.json.gz
[19:29:13 INFO]: [LP] (Import) -> Starting import process.
[19:29:13 INFO]: [LP] (Import) -> Reading data....
[19:29:13 INFO]: [LP] (Import) -> Waiting for initial update task to complete....
[19:29:13 WARN]: java.util.concurrent.CompletionException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
[19:29:13 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:106)
[19:29:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[19:29:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
[19:29:13 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[19:29:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[19:29:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[19:29:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[19:29:13 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[19:29:13 WARN]: Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
[19:29:13 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:171)
[19:29:13 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:467)
[19:29:13 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:195)
[19:29:13 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:101)
[19:29:13 WARN]:        ... 7 more
[19:29:47 ERROR]: [LuckPerms] Exception occurred whilst loading data for 4594ab09-4609-3de9-8d18-069cddc8faf8 - GSUSER
java.util.concurrent.CompletionException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
        at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:93) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:171) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:612) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:259) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:88) ~[?:?]
        ... 7 more`

### Extra Details

https://pastebin.com/zpLhpQvG

**Comment by underscore11code** [comment]
There should be another error at startup, this error is caused by the startup error. See [here](https://luckperms.net/wiki/Storage-system-errors), it should explain the error and how to fix it.

**Comment by ionutelul123** [comment]
> 

`[19:50:15 INFO]: [LuckPerms] Enabling LuckPerms v5.3.89
[19:50:15 WARN]: SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
[19:50:15 WARN]: SLF4J: Ignoring binding found at [jar:file:/home/container/cache/patched_1.13.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[19:50:15 WARN]: SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
[19:50:16 INFO]:         __    
[19:50:16 INFO]:   |    |__)   LuckPerms v5.3.89
[19:50:16 INFO]:   |___ |      Running on Bukkit - Paper
[19:50:16 INFO]: 
[19:50:17 INFO]: [LuckPerms] Loading configuration...
[19:50:20 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[19:50:20 ERROR]: [LuckPerms] Failed to init storage implementation
java.lang.NullPointerException: address
        at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
        at me.lucko.luckperms.common.storage.misc.StorageCredentials.getAddress(StorageCredentials.java:58) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:125) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:162) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.init(Storage.java:117) ~[?:?]
        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:166) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:51) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-498]
        at java.lang.Thread.run(Thread.java:829) [?:?]
[19:50:20 INFO]: [LuckPerms] Loading messaging service... [SQL]
[19:50:21 ERROR]: [LuckPerms] Exception occurred whilst enabling SQL messaging service
java.lang.RuntimeException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57) ~[?:?]
        at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:195) ~[?:?]
        at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:71) ~[?:?]
        at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:121) ~[?:?]
        at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:64) ~[?:?]
        at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:89) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:167) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:51) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236) ~[patched_1.13.2.jar:git-Paper-498]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-498]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:171) ~[?:?]
        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85) ~[?:?]
        at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:61) ~[?:?]
        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55) ~[?:?]
        ... 16 more
[19:50:21 WARN]: [LuckPerms] Messaging service 'sql' not recognised.
[19:50:21 INFO]: [LuckPerms] Loading internal permission managers...
[19:50:21 INFO]: [LuckPerms] Performing initial data load...
[19:50:21 WARN]: java.util.concurrent.CompletionException: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
[19:50:21 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:106)
[19:50:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[19:50:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
[19:50:21 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[19:50:21 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[19:50:21 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[19:50:21 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[19:50:21 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[19:50:21 WARN]: Caused by: java.sql.SQLException: Unable to get a connection from the pool. (hikari is null)
[19:50:21 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:171)
[19:50:21 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:467)
[19:50:21 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:195)
[19:50:21 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:101)
[19:50:21 WARN]:        ... 7 more
[19:50:21 INFO]: [LuckPerms] Successfully enabled. (took 5976ms)`

This is the error at startup hm

**Comment by underscore11code** [comment]
You've not entered your DB server's address into the config correctly, or you've made it blank.

**Comment by ionutelul123** [comment]
FIXED
