### ISSUE TITLE
Unable to load dependency

### ISSUE THREAD

**Issue by SlimeDog** [LuckPerms/LuckPerms#3320]
### Description

Unable to load dependency on server start-up. Issue did not recur after shutdown and restart.

### Reproduction Steps

Stop and start server. No changes to configurations or plugins or etc.

### Expected Behaviour

Clean restart.

### Server Details

Paper 1.18.1-198

### LuckPerms Version

5.4.1

### Logs and Configs

```
[23:04:09] [ForkJoinPool-1-worker-3/ERROR]: [LuckPerms] Unable to load dependency ADVENTURE_PLATFORM_BUKKIT.
me.lucko.luckperms.common.dependencies.DependencyDownloadException: java.net.SocketTimeoutException: Connection timed out
        at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:109) ~[?:?]
        at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:122) ~[?:?]
        at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:147) ~[?:?]
        at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:170) ~[?:?]
        at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:148) ~[?:?]
        at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.net.SocketTimeoutException: Connection timed out
        at me.lucko.networkinterceptor.interceptors.ProxySelectorInterceptor$LoggingSelector.select(ProxySelectorInterceptor.java:65) ~[NetworkInterceptor-3.2.1.jar:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1118) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1116) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:962) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1115) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1581) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1579) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:962) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1578) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:101) ~[?:?]
        ... 11 more
```

**Comment by lucko** [comment]
`at me.lucko.networkinterceptor.interceptors.ProxySelectorInterceptor$LoggingSelector.select`

is blocking the connection :)

**Comment by SlimeDog** [comment]
Well, there you have it. Mea culpa. Thanks.
