### ISSUE TITLE
LuckPerms not load in 1.18.2

### ISSUE THREAD

**Issue by GhostAndry** [LuckPerms/LuckPerms#3371]
### Description

[23:09:08] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.21
[23:09:08] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] me/lucko/luckperms/lib/adventure/translation/Translator initializing LuckPerms v5.4.21 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/adventure/translation/Translator
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:120) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:152) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onLoad(BukkitLoaderPlugin.java:46) ~[LuckPerms-Bukkit-5.4.21.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-332]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.adventure.translation.Translator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 8 more

### Reproduction Steps

[23:09:08] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.21
[23:09:08] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] me/lucko/luckperms/lib/adventure/translation/Translator initializing LuckPerms v5.4.21 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/adventure/translation/Translator
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:120) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:152) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onLoad(BukkitLoaderPlugin.java:46) ~[LuckPerms-Bukkit-5.4.21.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-332]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.adventure.translation.Translator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 8 more

### Expected Behaviour

[23:09:08] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.21
[23:09:08] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] me/lucko/luckperms/lib/adventure/translation/Translator initializing LuckPerms v5.4.21 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/adventure/translation/Translator
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:120) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:152) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onLoad(BukkitLoaderPlugin.java:46) ~[LuckPerms-Bukkit-5.4.21.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-332]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.adventure.translation.Translator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 8 more

### Server Details

Paper-1.18.2#332 

### LuckPerms Version

v5.4.21

### Logs and Configs

[23:09:08] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.21
[23:09:08] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] me/lucko/luckperms/lib/adventure/translation/Translator initializing LuckPerms v5.4.21 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/adventure/translation/Translator
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:120) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:152) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onLoad(BukkitLoaderPlugin.java:46) ~[LuckPerms-Bukkit-5.4.21.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-332]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.adventure.translation.Translator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 8 more

### Extra Details

[23:09:08] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.21
[23:09:08] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] me/lucko/luckperms/lib/adventure/translation/Translator initializing LuckPerms v5.4.21 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/adventure/translation/Translator
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:120) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:152) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onLoad(BukkitLoaderPlugin.java:46) ~[LuckPerms-Bukkit-5.4.21.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-332]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-332]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.adventure.translation.Translator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 8 more

**Comment by powercasgamer** [comment]
Stop your server, delete the `libs` folder in `plugins/LuckPerms/`, then start your server again. You can also get help in our [discord](https://discord.gg/luckperms)

**Comment by ZeromaniacMc** [comment]
Please dont (half) ignore the issue template, there is no reason to put half of your log into 5 parts which all ask different things. 
The errors you are getting are indicating that LuckPerms is missing dependency libraries it needs to operate. 
Try to delete the /libs/ folder while your server is offline so it redownloads them when you start it back up.
~Cheers

**Comment by GhostAndry** [comment]
What Is the dependencies?
