### ISSUE TITLE
[Quilt 1.18.2] Server crash (NoClassDefFoundError: Translator)

### ISSUE THREAD

**Issue by rogi27** [LuckPerms/LuckPerms#3380]
### Description

Mod crashes on server-side, logs below.

I tried deleting `/libs`, not helping.

### Reproduction Steps

Download latest Quilt build server and install Quilt Libraries

### Expected Behaviour

Mod should load.

### Server Details

Quilt (Fabric) Server 1.18.2

### LuckPerms Version

v5.4.25 / v5.4.21

### Logs and Configs

```Java
[06:28:52] [luckperms-worker-7/ERROR]: Unable to load dependency CONFIGURATE_HOCON.
java.lang.NoSuchMethodError: 'void net.fabricmc.loader.launch.common.FabricLauncher.propose(java.net.URL)'
	at me.lucko.luckperms.fabric.FabricClassPathAppender.addJarToClasspath(FabricClassPathAppender.java:43) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:153) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[06:28:52] [luckperms-worker-1/ERROR]: Unable to load dependency EVENT.
java.lang.NoSuchMethodError: 'void net.fabricmc.loader.launch.common.FabricLauncher.propose(java.net.URL)'
	at me.lucko.luckperms.fabric.FabricClassPathAppender.addJarToClasspath(FabricClassPathAppender.java:43) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:153) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[06:28:52] [luckperms-worker-6/ERROR]: Unable to load dependency CONFIGURATE_CORE.
java.lang.NoSuchMethodError: 'void net.fabricmc.loader.launch.common.FabricLauncher.propose(java.net.URL)'
	at me.lucko.luckperms.fabric.FabricClassPathAppender.addJarToClasspath(FabricClassPathAppender.java:43) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:153) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[06:28:52] [luckperms-worker-4/ERROR]: Unable to load dependency OKHTTP.
java.lang.NoSuchMethodError: 'void net.fabricmc.loader.launch.common.FabricLauncher.propose(java.net.URL)'
	at me.lucko.luckperms.fabric.FabricClassPathAppender.addJarToClasspath(FabricClassPathAppender.java:43) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:153) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[06:28:52] [luckperms-worker-3/ERROR]: Unable to load dependency OKIO.
java.lang.NoSuchMethodError: 'void net.fabricmc.loader.launch.common.FabricLauncher.propose(java.net.URL)'
	at me.lucko.luckperms.fabric.FabricClassPathAppender.addJarToClasspath(FabricClassPathAppender.java:43) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:153) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[06:28:53] [luckperms-worker-8/ERROR]: Unable to load dependency HOCON_CONFIG.
java.lang.NoSuchMethodError: 'void net.fabricmc.loader.launch.common.FabricLauncher.propose(java.net.URL)'
	at me.lucko.luckperms.fabric.FabricClassPathAppender.addJarToClasspath(FabricClassPathAppender.java:43) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:153) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[06:28:53] [luckperms-worker-0/ERROR]: Unable to load dependency ADVENTURE.
java.lang.NoSuchMethodError: 'void net.fabricmc.loader.launch.common.FabricLauncher.propose(java.net.URL)'
	at me.lucko.luckperms.fabric.FabricClassPathAppender.addJarToClasspath(FabricClassPathAppender.java:43) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:153) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[06:28:53] [luckperms-worker-2/ERROR]: Unable to load dependency CAFFEINE.
java.lang.NoSuchMethodError: 'void net.fabricmc.loader.launch.common.FabricLauncher.propose(java.net.URL)'
	at me.lucko.luckperms.fabric.FabricClassPathAppender.addJarToClasspath(FabricClassPathAppender.java:43) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:153) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[06:28:54] [luckperms-worker-5/ERROR]: Unable to load dependency BYTEBUDDY.
java.lang.NoSuchMethodError: 'void net.fabricmc.loader.launch.common.FabricLauncher.propose(java.net.URL)'
	at me.lucko.luckperms.fabric.FabricClassPathAppender.addJarToClasspath(FabricClassPathAppender.java:43) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:153) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[06:28:54] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'luckperms'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:62) ~[quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:60) ~[quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:45) ~[quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:32) ~[quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[quilt-loader-0.16.1.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.16.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.launch.knot.KnotHelper.launchServer(KnotHelper.java:32) [quilt-loader-0.16.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:23) [quilt-loader-0.16.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:62) [quilt-loader-0.16.1.jar:?]
Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/adventure/translation/Translator
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:120) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.fabric.LPFabricBootstrap.onInitializeServer(LPFabricBootstrap.java:137) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$3(Hooks.java:63) ~[quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:32) ~[quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:58) ~[quilt-loader-0.16.1.jar:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.adventure.translation.Translator
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[quilt-loader-0.16.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:120) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at me.lucko.luckperms.fabric.LPFabricBootstrap.onInitializeServer(LPFabricBootstrap.java:137) ~[LuckPerms-Fabric-5.4.21.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$3(Hooks.java:63) ~[quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:32) ~[quilt-loader-0.16.1.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:58) ~[quilt-loader-0.16.1.jar:?]
	... 17 more
```

### Extra Details

Quilt: https://quiltmc.org/install/
Quilt API: [https://modrinth.com/mod/qsl](https://modrinth.com/mod/qsl)

**Comment by rogi27** [comment]
Somehow this error is similar to error in #3371

**Comment by emilyy-dev** [comment]
LuckPerms is not ready for usage on Quilt, as explained in #3365 the Fabric build uses internal Fabric API that does not exist in Quilt. There will be a supported Quilt build for LP when a supported alternative exists.

**Comment by AlexIIL** [comment]
Can you retry with Quilt-loader 0.17.0 or later? That version added more legacy fabric loader apis, including the method mentioned in the log.

**Comment by rogi27** [comment]
> Can you retry with Quilt-loader 0.17.0 or later? That version added more legacy fabric loader apis, including the method mentioned in the log.

Yeah, got it working, thanks 🙏
