### ISSUE TITLE
Running with config file for first time.

### ISSUE THREAD

**Issue by Authorises** [LuckPerms/LuckPerms#3388]
### Description

When you run the server, I've only tested this with docker, It only produces this issue on bungee, if you copy over a config file to the /plugins/LuckPerms and then start the server, luckperms will get this error:

`java.lang.RuntimeException: Unable to create libs directory

	at me.lucko.luckperms.common.dependencies.DependencyManager.setupCacheDirectory(DependencyManager.java:204) ~[?:?]

	at me.lucko.luckperms.common.dependencies.DependencyManager.<init>(DependencyManager.java:75) ~[?:?]

	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:117) ~[?:?]

	at me.lucko.luckperms.bungee.LPBungeeBootstrap.onLoad(LPBungeeBootstrap.java:144) ~[?:?]

	at me.lucko.luckperms.bungee.loader.BungeeLoaderPlugin.onLoad(BungeeLoaderPlugin.java:46) ~[?:?]

	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:398) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8d64a1a:485]

	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8d64a1a:485]

	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8d64a1a:485]

	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8d64a1a:485]

	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8d64a1a:485]`

### Reproduction Steps

Create all of the files needed for a waterfall/bungee intance, add Luckperms to the /plugins and in /plugins/LuckPerms place your config file, then start the server for the first time.

### Expected Behaviour

Should startup normally using the config

### Server Details

waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8d64a1a:485

### LuckPerms Version

LuckPerms-Bungee-5.4.21

### Logs and Configs

https://fdow.nl/ak9iA

**Comment by emilyy-dev** [comment]
> /server/plugins/LuckPerms/libs: Not a directory

Does the file for that path exist? If so delete it and restart the proxy

**Comment by emilyy-dev** [comment]
> The whole point is that it needs to be able to be ran only once

In an ideal world yes, but things can go wrong which require to run things more than once.

What Java version and Operating System does the system run? Can you try creating the `LuckPerms/libs` directory manually?

**Comment by Authorises** [comment]
> > The whole point is that it needs to be able to be ran only once
> 
> 
> 
> In an ideal world yes, but things can go wrong which require to run things more than once.
> 
> 
> 
> What Java version and Operating System does the system run? Can you try creating the `LuckPerms/libs` directory manually?

I made a hotfix which starts it without the config and then puts the config in and starts it but it really should work anyway. Manually creating the libs dir does nothing to help.

**Comment by lucko** [comment]
My guess is that when you create the `plugins/LuckPerms/` directory and copy the config, your script is not setting the correct file permissions / owner.

The server directory should be "owned" by the same user as the server process. You should be able to rectify this by running `chown` after the directory/config files are created.

**Comment by Authorises** [comment]
okay
