### ISSUE TITLE
LuckPerms-Bukkit-5.4.30Not available on 1.19.

### ISSUE THREAD

**Issue by NEIKI19914** [LuckPerms/LuckPerms#3396]
### Description

LuckPerms-Bukkit-5.4.30Not available on 1.19.
[LuckPerms] Loading LuckPerms v5.4.30
[09:56:41] [luckperms-worker-0/ERROR]: [LuckPerms] Unable to load dependency ADVENTURE.
me.lucko.luckperms.common.dependencies.DependencyDownloadException: java.net.ConnectException: Connection timed out: connect
	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:112) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:125) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:150) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:170) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:148) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:104) ~[?:?]
	... 11 more
[09:56:41] [luckperms-worker-1/ERROR]: [LuckPerms] Unable to load dependency ADVENTURE_PLATFORM.
me.lucko.luckperms.common.dependencies.DependencyDownloadException: java.net.ConnectException: Connection timed out: connect
	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:112) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:125) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:150) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:170) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:148) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:104) ~[?:?]
	... 11 more
[09:56:41] [luckperms-worker-2/ERROR]: [LuckPerms] Unable to load dependency ADVENTURE_PLATFORM_BUKKIT.
me.lucko.luckperms.common.dependencies.DependencyDownloadException: java.net.ConnectException: Connection timed out: connect
	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:112) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:125) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:150) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:170) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:148) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:104) ~[?:?]
	... 11 more
[09:56:41] [luckperms-worker-8/ERROR]: [LuckPerms] Unable to load dependency COMMODORE.
me.lucko.luckperms.common.dependencies.DependencyDownloadException: java.net.ConnectException: Connection timed out: connect
	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:112) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:125) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:150) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.downloadDependency(DependencyManager.java:170) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.loadDependency(DependencyManager.java:148) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyManager.lambda$loadDependencies$2(DependencyManager.java:127) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:104) ~[?:?]
	... 11 more
[09:56:41] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_19_R1.CraftServer] me/lucko/luckperms/lib/adventure/translation/Translator initializing LuckPerms v5.4.30 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/adventure/translation/Translator
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:121) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onLoad(LPBukkitBootstrap.java:152) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onLoad(BukkitLoaderPlugin.java:46) ~[LuckPerms-Bukkit-5.4.30.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-8]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.adventure.translation.Translator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 8 more

### Reproduction Steps

It is directly unavailable at startup.

### Expected Behaviour

Hope it can be resolved soon

### Server Details

paper-1.19-8.jar

### LuckPerms Version

LuckPerms-Bukkit-5.4.30

**Comment by LeotomasMC** [comment]
> Connection timed out
seems like an internet issue

**Comment by NEIKI19914** [comment]
> > Connection timed out
> 
> seems like an internet issue

But not on luckperms-bukkit-5.4.26.
