### ISSUE TITLE
Cannot run Luckperms with the fabric 1.18.2

### ISSUE THREAD

**Issue by Eric-liucn** [LuckPerms/LuckPerms#3404]
### Description

```
[22:31:57] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'luckperms'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.8.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/command/v2/CommandRegistrationCallback
        at me.lucko.luckperms.fabric.FabricCommandExecutor.register(FabricCommandExecutor.java:56) ~[%5Bserver%5DLuckPerms-Fabric-5.4.30.jar:?]
        at me.lucko.luckperms.fabric.LPFabricPlugin.registerFabricListeners(LPFabricPlugin.java:95) ~[%5Bserver%5DLuckPerms-Fabric-5.4.30.jar:?]
        at me.lucko.luckperms.fabric.LPFabricBootstrap.onInitializeServer(LPFabricBootstrap.java:145) ~[%5Bserver%5DLuckPerms-Fabric-5.4.30.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at me.lucko.luckperms.fabric.FabricCommandExecutor.register(FabricCommandExecutor.java:56) ~[%5Bserver%5DLuckPerms-Fabric-5.4.30.jar:?]
        at me.lucko.luckperms.fabric.LPFabricPlugin.registerFabricListeners(LPFabricPlugin.java:95) ~[%5Bserver%5DLuckPerms-Fabric-5.4.30.jar:?]
        at me.lucko.luckperms.fabric.LPFabricBootstrap.onInitializeServer(LPFabricBootstrap.java:145) ~[%5Bserver%5DLuckPerms-Fabric-5.4.30.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
        ... 7 more
```

Installed mods:
```
[FabricAPI]fabric-api-0.56.1+1.18.2.jar
[server]flan-1.18.2-1.7.9-fabric.jar
[server]LuckPerms-Fabric-5.4.30.jar
[server]worldedit-mod-7.2.10.jar
```

### Reproduction Steps

Install fabric server with the installer offered by fabricMC  
Then install the mods mentioned above and start the server

### Expected Behaviour

work properly

### Server Details

fabric 0.56.1+1.18.2

### LuckPerms Version

v5.4.30

**Comment by ZeromaniacMc** [comment]
Please refer to [this issue](https://github.com/LuckPerms/LuckPerms/issues/3400)
