### ISSUE TITLE
Luckperms errors fatally upon using PostgreSQL on Sponge(Forge) (1.16.5, Sponge 8)

### ISSUE THREAD

**Issue by exoRift** [LuckPerms/LuckPerms#3414]
### Description

When using LuckPerms on SpongeForge and a PostgreSQL database, The LuckPerms plugin fails to initialize and denies all players entry into the server with an error saying it was unable to fetch their permission data.

### Reproduction Steps

1. Set up a SpongeForge server (Sponge 8, 1.16.5)
2. Install LuckPerms
3. Set your database option to PostgreSQL

### Expected Behaviour

It should work lmao

### Server Details

Sponge-1.16.5-36.2.5-8.1.0-RC1153

### LuckPerms Version

v5.4.30

### Logs and Configs

https://pastebin.com/zxKdeVpE

### Extra Details

This was confirmed by _11 to be a bug

**Comment by lucko** [comment]
This is a classpath issue, most likely caused by a plugin/mod.

```
java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContextFactory.isClassLoaderDependent()Z
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:49) ~[?:2.17.1]
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46) ~[log4j-api-2.11.2.jar:2.11.2]
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33) ~[?:2.17.1]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[?:1.7.25]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383) ~[?:1.7.25]
```

Does it work with just LuckPerms installed on the server?
