### ISSUE TITLE
Shut down server cant disconnect sql correctly

### ISSUE THREAD

**Issue by mrcang09** [LuckPerms/LuckPerms#3423]
### Description

when i shut down the server,luckperm will stll use hakari  to connect mysql,it cant not disconnect sql correctly.Please add a new function to detect if the server is shut down, if so, stop trying to connect to mysql

### Reproduction Steps

This problem sometimes occurs when the server is stopped

### Expected Behaviour

This problem sometimes occurs when the server is stopped

### Server Details

MC: 1.12.2

### LuckPerms Version

v5.3.27

### Logs and Configs

[06:05:49] [luckperms-scheduler-worker-380/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 14779ms.
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174)
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85)
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.pollMessages(AbstractSqlMessenger.java:115)
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:124)
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[06:05:49] [luckperms-scheduler-worker-380/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 14779ms.
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.pollMessages(AbstractSqlMessenger.java:115)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at me.lucko.luckperms.common.plugin.scheduler.AbstractJavaScheduler$ErrorReportingRunnable.run(AbstractJavaScheduler.java:124)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[06:05:49] [luckperms-scheduler-worker-391/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by lucko** [comment]
LuckPerms needs to be able to access the database at all times whilst it is running. It is expected that issues will occur if the database is unavailable.
