### ISSUE TITLE
Cause a NullPointerException while a player connect into the server.

### ISSUE THREAD

**Issue by K85** [LuckPerms/LuckPerms#3432]
### Description

Cause a NullPointerException while a player connect into the server.

### Reproduction Steps

any player try to connect into the server.

### Expected Behaviour

At least a player should connect to the server.
I am using the default H2 database server and keep the default configuration that the plugin generated.
so anything should be ok. there should no be any database exception

### Server Details

 Mohist version 1.16.5-1061 (MC: 1.16.5)

### LuckPerms Version

LuckPerms-Bukkit-5.4.30

### Logs and Configs

```
[17:42:06 ERROR]: [LuckPerms] Exception occurred whilst loading data for null - SakuraWald
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
        at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.getIfPresent(BoundedLocalCache.java:1904) ~[?:?]
        at me.lucko.luckperms.lib.caffeine.cache.LocalManualCache.getIfPresent(LocalManualCache.java:57) ~[?:?]
        at me.lucko.luckperms.common.util.ExpiringSet.contains(ExpiringSet.java:53) ~[?:?]
        at me.lucko.luckperms.common.util.ExpiringSet.add(ExpiringSet.java:47) ~[?:?]
        at me.lucko.luckperms.common.model.manager.user.UserHousekeeper.registerUsage(UserHousekeeper.java:58) ~[?:?]
        at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser(AbstractConnectionListener.java:67) ~[?:?]
        at me.lucko.luckperms.bukkit.listeners.BukkitConnectionListener.onPlayerPreLogin(BukkitConnectionListener.java:125) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[forge:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593) ~[forge:?]
        at net.minecraft.network.login.ServerLoginNetHandler$LoginHandler.fireEvents(ServerLoginNetHandler.java:281) ~[?:?]
        at net.minecraft.network.login.ServerLoginNetHandler$1.run(ServerLoginNetHandler.java:194) ~[?:?]
[17:42:06 INFO]: Disconnecting com.mojang.authlib.GameProfile@61bc05a2[id=<null>,name=SakuraWald,properties={},legacy=false] (/117.30.120.90:5974): [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
[17:42:07 INFO]: com.mojang.authlib.GameProfile@61bc05a2[id=<null>,name=SakuraWald,properties={},legacy=false] (/117.30.120.90:5974) lost connection: [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
>

```

### Extra Details

```
> version
[17:44:09 INFO]: This server is running Mohist version 1.16.5-1061 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
>
```

**Comment by ZeromaniacMc** [comment]
I've seen this error being reported before. LuckPerms does not officially support hybrid server software. However, your mohist build is 6 versions behind. Try updating it, and if that also fails, two people have reported switching to magma to work, so might be worth considering that.

**Comment by K85** [comment]
i have update my mohist 1.16.5 from #1061 to #1067. the problem are the same.

**Comment by xIsm4** [comment]
> i have updated my mohist 1.16.5 from #1061 to #1067. the problem are the same. sad that Magma doesn't support a higher minecraft version.

As they said, hybrid software is not supported due this problems. A lot of bugs are on way and can't really be solved.
I really suggest you split your servers on plugins - mods!

**Comment by K85** [comment]
> 

thanks. i have changed the core to paper.

**Comment by lucko** [comment]
Seems like a mohist bug.
