### ISSUE TITLE
lp editor not working

### ISSUE THREAD

**Issue by huoyan1231** [LuckPerms/LuckPerms#3443]
### Description

lp editor not working

### Reproduction Steps

use /lp editor

### Expected Behaviour

show lp editor link

### Server Details

catserver 1.12.2 with Bukkit 1.12.2-R0.1-SpigotAPI

### LuckPerms Version

5.4.36

### Logs and Configs

[16:32:18] [luckperms-command-executor/WARN] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin]: [LuckPerms] Unable to establish socket connection
java.lang.RuntimeException: Timed out waiting to socket to connect
	at me.lucko.luckperms.common.webeditor.socket.WebEditorSocket.waitForConnect(WebEditorSocket.java:103) ~[?:?]
	at me.lucko.luckperms.common.webeditor.WebEditorSession.createSocket(WebEditorSession.java:96) ~[?:?]
	at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87) ~[?:?]
	at me.lucko.luckperms.common.webeditor.WebEditorSession.createAndOpen(WebEditorSession.java:62) ~[?:?]
	at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:111) ~[?:?]
	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56) ~[?:?]
	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48) ~[?:?]
	at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:265) ~[?:?]
	at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:169) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_341]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_341]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_341]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(Unknown Source) ~[?:1.8.0_341]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_341]
	at me.lucko.luckperms.common.webeditor.socket.WebEditorSocket.waitForConnect(WebEditorSocket.java:101) ~[?:?]
	... 12 more
[16:32:18] [luckperms-command-executor/INFO] []: [Yum] [Yum 网络管理] 插件 AutoSaveWorld 尝试访问网络 请注意服务器网络安全!
[16:32:18] [luckperms-command-executor/INFO] []: [Yum] [Yum 网络管理] 地址: https://usercontent.luckperms.net/
[16:32:19] [luckperms-worker-4/WARN] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin]: [LuckPerms] Command execution [editor] has not completed. Trace: 
  java.lang.Object.wait(Native Method)
  java.lang.Object.wait(Unknown Source)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:660)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
  me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:104)
  me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:200)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:130)
  me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:88)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createAndOpen(WebEditorSession.java:62)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:111)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:265)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:169)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$2714/307193001.run(Unknown Source)
  java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)

**Comment by lucko** [comment]
Most likely a firewall issue.

Make sure your server is allowed to access `usercontent.luckperms.net` and `usersockets.luckperms.net`
