### ISSUE TITLE
An error occurs when the Luckperms mod closes the server

### ISSUE THREAD

**Issue by alazeprt** [LuckPerms/LuckPerms#3450]
### Description

I run the Luckperms module on the server. When I start the server, the Luckperms module runs normally, but when I shut down the server, an error is reported

### Reproduction Steps

Shut down the server (did not use any Luckperms commands during this time)

### Expected Behaviour

The server is shut down normally, and Luckperms will not report an error

### Server Details

fabric-server-mc.1.18.2-loader.0.14.8-launcher.0.11.0(Fabric API:0.58.0)

### LuckPerms Version

v5.4.25

### Logs and Configs

```
[20:30:29] [Server thread/INFO]: Stopping the server
[20:30:29] [Server thread/INFO]: Starting shutdown process...
[20:30:29] [Server thread/INFO]: Closing storage...
[20:30:29] [Server thread/INFO]: Goodbye!
[20:30:29] [Server thread/INFO]: Stopping server
[20:30:29] [Server thread/INFO]: Saving players
[20:30:29] [Server thread/ERROR]: Exception stopping the server
java.util.concurrent.RejectedExecutionException: null
        at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2179) ~[?:?]
        at java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:2196) ~[?:?]
        at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2664) ~[?:?]
        at me.lucko.luckperms.common.plugin.scheduler.SchedulerAdapter.executeAsync(SchedulerAdapter.java:56) ~[%5B服务 器基础-权限%5DLuckPerms-Fabric-5.4.25.jar:?]
        at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.handleDisconnect(AbstractConnectionListener.java:121) ~[%5B服务器基础-权限%5DLuckPerms-Fabric-5.4.25.jar:?]
        at me.lucko.luckperms.fabric.listeners.FabricConnectionListener.onDisconnect(FabricConnectionListener.java:137) ~[%5B服务器基础-权限%5DLuckPerms-Fabric-5.4.25.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$4(ServerPlayConnectionEvents.java:59) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.invokeDisconnectEvent(ServerPlayNetworkAddon.java:140) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
        at net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect(AbstractNetworkAddon.java:131) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
        at net.minecraft.class_3244.handler$blj001$handleDisconnection(class_3244.java:2221) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_10839(class_3244.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10768(class_2535.java:424) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_19537(class_1255.java:88) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_14367(class_3244.java:301) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14597(class_3324.java:772) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:608) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:565) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:729) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Extra Details

Server mod list:
        - adventure-platform-fabric 5.2.1 via minimotd-fabric
        - at_favre_lib_bcrypt 0.9.0 via easyauth
        - at_favre_lib_bytes 1.5.0 via easyauth
        - carpet 1.4.69
        - carpet-tis-addition 1.39.0
        - com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.13.0 via essential_commands
        - conditional-mixin 0.3.1 via carpet-tis-addition
        - config2brigadier 1.1.1 via taterzens
        - de_mkammerer_argon2-jvm 2.11 via easyauth
        - de_mkammerer_argon2-jvm-nolibs 2.11 via easyauth
        - easyauth 3.0.0-6
        - ec-core 1.0.1-mc1.18.2 via essential_commands
        - essential_commands 0.24.5-mc1.18.2
        - fabric 0.58.0+1.18.2
        - fabric-api-base 0.4.4+d7c144a860 via fabric
        - fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
        - fabric-biome-api-v1 8.0.6+651bcc5960 via fabric
        - fabric-command-api-v1 1.1.9+d7c144a860 via fabric
        - fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
        - fabric-containers-v0 0.1.23+d7c144a860 via fabric
        - fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric
        - fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
        - fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
        - fabric-data-generation-api-v1 3.0.1+9fcb91d260 via fabric
        - fabric-dimensions-v1 2.1.20+489d6f8260 via fabric
        - fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
        - fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
        - fabric-events-lifecycle-v0 0.2.19+d7c144a860 via fabric
        - fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
        - fabric-item-api-v1 1.5.2+17cbbd4360 via fabric
        - fabric-item-groups-v0 0.3.14+91896a4960 via fabric
        - fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
        - fabric-loot-api-v2 1.1.0+1997ad1260 via fabric
        - fabric-loot-tables-v1 1.1.2+e747827960 via fabric
        - fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric
        - fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric
        - fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric
        - fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric
        - fabric-particles-v1 0.2.12+526dc1ac60 via fabric
        - fabric-permissions-api-v0 0.1-SNAPSHOT via spark
        - fabric-registry-sync-v0 0.9.10+0d9ab37260 via fabric
        - fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
        - fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
        - fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
        - fabric-resource-loader-v0 0.5.2+446e059560 via fabric
        - fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric
        - fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
        - fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
        - fabricloader 0.14.8
        - fantasy 0.4.4+1.18.2 via multiworld
        -java 17
        - luckperms 5.4.25
        - minecraft 1.18.2
        - minimotd-fabric 2.0.7
        - multiworld 1.4
        - mysql_mysql-connector-java 8.0.28 via easyauth
        - net_java_dev_jna_jna 5.9.0 via easyauth
        - net_kyori_adventure-api 4.10.1 via adventure-platform-fabric
        - net_kyori_adventure-key 4.10.1 via adventure-platform-fabric
        - net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
        - net_kyori_adventure-text-minimessage 4.10.1 via adventure-platform-fabric
        - net_kyori_adventure-text-serializer-gson 4.10.1 via adventure-platform-fabric
        - net_kyori_adventure-text-serializer-plain 4.10.1 via adventure-platform-fabric
        - net_kyori_examination-api 1.3.0 via adventure-platform-fabric
        - net_kyori_examination-string 1.3.0 via adventure-platform-fabric
        - org_iq80_leveldb_leveldb 0.12 via easyauth
        - org_iq80_leveldb_leveldb-api 0.12 via easyauth
        - org_mongodb_bson 4.3.2 via easyauth
        - org_mongodb_mongodb-driver-core 4.3.2 via easyauth
        - org_mongodb_mongodb-driver-sync 4.3.2 via easyauth
        - org_yaml_snakeyaml 1.30 via carpet-tis-addition
        - packet_tweaker 0.2.0+1.18-pre1 via server_translations_api
        - placeholder-api 1.1.3+1.17.1 via essential_commands
        - playerabilitylib 1.3.0 via essential_commands
        - server_translations_api 1.4.12+1.18.2 via taterzens
        - sgui 1.0.0+1.18.1 via taterzens
        - skinrestorer 1.0.4
        - spark 1.9.11
        - taterzens 1.9.6
        - tradernpcs 1.1.1
        - worldedit 7.2.10+1742f98

**Comment by lucko** [comment]
Arguably a server (/fabric?) bug that those events are called after the server has shutdown. Not sure how they can be worked around in LuckPerms, but you can probably safely ignore the errors.
