### ISSUE TITLE
Issue 3440 not resolved on version 5.4.40

### ISSUE THREAD

**Issue by Rockin21** [LuckPerms/LuckPerms#3452]
### Description

Receiving this error when trying to auto fill any user when using a luck perms command:

[21:33:47 ERROR]: Could not pass event AsyncTabCompleteEvent to LuckPerms v5.4.40
java.lang.NullPointerException: null
[21:33:47 ERROR]: Exception when j4ppyy attempted to tab complete lp user 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/lp user ' in plugin LuckPerms v5.4.40
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:240) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]

### Reproduction Steps

Typing any luckperms command and trying to auto fill.

### Expected Behaviour

The command should work. 

### Server Details

git-Pufferfish-24 (MC: 1.19)

### LuckPerms Version

5.4.40

### Logs and Configs

https://pastes.dev/lb5zWUpN0r

**Comment by LeotomasMC** [comment]
#3440 is not the same issue as this. also please attach a **full log**, not just the error from the console

**Comment by Rockin21** [comment]
> #3440 is not the same issue as this. also please attach a **full log**, not just the error from the console

My bad, I've attached the entire log.

**Comment by LeotomasMC** [comment]
can you paste the `latest.log` file instead of uploading a compressed older log

**Comment by Rockin21** [comment]
> can you paste the `latest.log` file instead of uploading a compressed older log

The latest.log is running an older version that I tried today, is that fine?

**Comment by LeotomasMC** [comment]
update everything, restart the server, reproduce the issue, then do it

**Comment by Rockin21** [comment]
> update everything, restart the server, reproduce the issue, then do it

Ok, I'll do that now
