### ISSUE TITLE
Support PowerNukkitX

### ISSUE THREAD

**Issue by GalaxyGamerLIVE** [LuckPerms/LuckPerms#3459]
### Description

Hello,
our bedrock server use PowerNukkit (fork of Nukkit) as software. Luckperms works fine with PowerNukkit. Now we like the change the software to PowerNukkitX. Because Nukkit and PowerNukkit are not active anymore. PowerNukkitX is a fork of PowerNukkit and has lot of cool features. All our plugins working fine with PowerNukkitX except for LuckPerms (Exception in the details section). So it would be great for us and probably many other bedrock servers if you support PowerNukkitX.

Here are some important links about PowerNukkitX:

- [Github](https://github.com/PowerNukkitX/PowerNukkitX)
- [Github English Readme](https://github.com/PowerNukkitX/PowerNukkitX/blob/master/blob/en-us/README.md)
- [Website](https://www.powernukkitx.cn)
- [Documentation](https://doc.powernukkitx.cn/en-us/Get_Started.html)

### Proposed Behaviour

Since LuckPerms works fine on PowerNukkit and PowerNukkitX is based on PowerNukkit, only minor adjustments will probably be necessary. In addition, LuckPerms is also activated when you start the server. There are only problems when joining the server.

### Extra Details

Here are some additional information about our setup:

- Debian GNU/Linux 10 (buster)
- Java 17
- PowerNukkitX Version 1.19.10-r1
- LuckPerms-Nukkit-5.4.41

This is the exception that I get if I join the server. After that, the server crashes.

>12:45:41 [FATAL] Exception in asynchronous task
java.lang.NoClassDefFoundError: me/lucko/luckperms/nukkit/listeners/NukkitConnectionListener
        at cn.nukkit.plugin.PNXMethodEventExecutor$7.execute(EventHandler@me.lucko.luckperms.nukkit.listeners.NukkitConnectionListener#onPlayerPreLogin) ~[?:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61) ~[PowerNukkitX-master-2aaceebdc.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:589) ~[PowerNukkitX-master-2aaceebdc.jar:?]
        at cn.nukkit.Player$2.onRun(Player.java:2647) ~[PowerNukkitX-master-2aaceebdc.jar:?]
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:26) ~[PowerNukkitX-master-2aaceebdc.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.nukkit.listeners.NukkitConnectionListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[PowerNukkitX-master-2aaceebdc.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[PowerNukkitX-master-2aaceebdc.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 8 more
> java.lang.NoClassDefFoundError: me/lucko/luckperms/nukkit/listeners/NukkitConnectionListener
        at cn.nukkit.plugin.PNXMethodEventExecutor$7.execute(EventHandler@me.lucko.luckperms.nukkit.listeners.NukkitConnectionListener#onPlayerPreLogin)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:589)
        at cn.nukkit.Player$2.onRun(Player.java:2647)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.nukkit.listeners.NukkitConnectionListener
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 8 more

**Comment by GalaxyGamerLIVE** [comment]
Devs from PowerNukkitX fixed that issue.
