### ISSUE TITLE
MariaDB not working (error)

### ISSUE THREAD

**Issue by Ariouz** [LuckPerms/LuckPerms#3462]
### Description

I addes mariadb to luckperms config with right credentials. First i got an error saying that plugin doesn't support "cachin-sha-password", so i edited my mariadb user and set the protocol to 'mysql-native-password'.
There is also an error after this. How can i do please?

### Reproduction Steps

Add mariadb to config
Restart server
See error

### Expected Behaviour

Db should works

### Server Details

git-Paper-387 (1.18.2)

### LuckPerms Version

v5.4.40

### Logs and Configs

[16:29:39] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:30:02] [Worker-Main-2/INFO]: Loaded 7 recipes
[16:30:04] [Server thread/INFO]: Starting minecraft server version 1.18.2
[16:30:04] [Server thread/WARN]: ****************************
[16:30:04] [Server thread/WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[16:30:04] [Server thread/WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[16:30:04] [Server thread/WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[16:30:04] [Server thread/WARN]: ****************************
[16:30:04] [Server thread/INFO]: Loading properties
[16:30:04] [Server thread/INFO]: This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
[16:30:10] [Server thread/INFO]: Server Ping Player Sample Count: 12
[16:30:10] [Server thread/INFO]: Using 6 threads for Netty based IO
[16:30:10] [Server thread/INFO]: Default game type: SURVIVAL
[16:30:10] [Server thread/INFO]: Generating keypair
[16:30:11] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:30:11] [Server thread/INFO]: Using epoll channel type
[16:30:11] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[16:30:11] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[16:30:14] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.40
[16:30:15] [Server thread/INFO]: [AngelskyApi] Loading AngelskyApi v0.0.8
[16:30:15] [Server thread/INFO]: [spark] Loading spark v1.9.33
[16:30:15] [Server thread/INFO]: [AngelskyLobby] Loading AngelskyLobby v1.0-SNAPSHOT
[16:30:15] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:30:15] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.40
[16:30:15] [Server thread/INFO]:         __    
[16:30:15] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.40
[16:30:15] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[16:30:15] [Server thread/INFO]: 
[16:30:15] [Server thread/INFO]: [LuckPerms] Loading configuration...
[16:30:21] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MARIADB]
[16:30:21] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Starting...
[16:30:21] [Server thread/INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Start completed.
[16:30:26] [Server thread/ERROR]: [LuckPerms] Failed to init storage implementation
java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[?:?]
	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:169) ~[?:?]
	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:117) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:182) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:177) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:51) ~[LuckPerms-Bukkit-5.4.40.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'
	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:305) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'
	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1392) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.util.Utils.retrieveProxy(Utils.java:635) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.MariaDbConnection.newConnection(MariaDbConnection.java:150) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:302) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.sql.SQLException: Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'
	at me.lucko.luckperms.lib.mariadb.authentication.AuthenticationPluginLoader.get(AuthenticationPluginLoader.java:52) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:734) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:553) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1387) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.util.Utils.retrieveProxy(Utils.java:635) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.MariaDbConnection.newConnection(MariaDbConnection.java:150) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:302) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
[16:30:26] [Server thread/INFO]: [LuckPerms] Loading messaging service... [SQL]
[16:30:31] [Server thread/ERROR]: [LuckPerms] Exception occurred whilst enabling SQL messaging service
java.lang.RuntimeException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57) ~[?:?]
	at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:195) ~[?:?]
	at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:71) ~[?:?]
	at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:121) ~[?:?]
	at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:64) ~[?:?]
	at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:89) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:183) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:177) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:51) ~[LuckPerms-Bukkit-5.4.40.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[?:?]
	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174) ~[?:?]
	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85) ~[?:?]
	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:61) ~[?:?]
	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55) ~[?:?]
	... 17 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'
	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:305) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'
	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1392) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.util.Utils.retrieveProxy(Utils.java:635) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.MariaDbConnection.newConnection(MariaDbConnection.java:150) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:302) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.sql.SQLException: Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'
	at me.lucko.luckperms.lib.mariadb.authentication.AuthenticationPluginLoader.get(AuthenticationPluginLoader.java:52) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:734) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:553) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1387) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.internal.util.Utils.retrieveProxy(Utils.java:635) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.MariaDbConnection.newConnection(MariaDbConnection.java:150) ~[?:?]
	at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:302) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
[16:30:31] [Server thread/WARN]: [LuckPerms] Messaging service 'sql' not recognised.
[16:30:32] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[16:30:32] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[16:30:43] [Server thread/WARN]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:106)
[16:30:43] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[16:30:43] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[16:30:43] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[16:30:43] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[16:30:43] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[16:30:43] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[16:30:43] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[16:30:43] [Server thread/WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:503)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$11(Storage.java:205)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:101)
[16:30:43] [Server thread/WARN]: 	... 7 more
[16:30:43] [Server thread/WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:305)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
[16:30:43] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:30:43] [Server thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:30:43] [Server thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:30:43] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:30:43] [Server thread/WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1392)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.util.Utils.retrieveProxy(Utils.java:635)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.MariaDbConnection.newConnection(MariaDbConnection.java:150)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.MariaDbDataSource.getConnection(MariaDbDataSource.java:302)
[16:30:43] [Server thread/WARN]: 	... 10 more
[16:30:43] [Server thread/WARN]: Caused by: java.sql.SQLException: Client does not support authentication protocol requested by server. plugin type was = 'caching_sha2_password'
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.authentication.AuthenticationPluginLoader.get(AuthenticationPluginLoader.java:52)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:734)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:553)
[16:30:43] [Server thread/WARN]: 	at me.lucko.luckperms.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1387)
[16:30:43] [Server thread/WARN]: 	... 13 more
[16:30:43] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 28047ms)
[16:30:43] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[16:30:43] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[16:30:43] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[16:30:43] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[16:30:43] [Server thread/INFO]: Preparing level "world"
[16:31:11] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:31:11] [Server thread/INFO]: Time elapsed: 327 ms
[16:31:11] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[16:31:12] [Server thread/INFO]: Time elapsed: 236 ms
[16:31:12] [Server thread/INFO]: [AngelskyApi] Enabling AngelskyApi v0.0.8
[16:31:12] [Server thread/INFO]: API Connectée à la base de données!
[16:31:12] [Server thread/INFO]: [spark] Enabling spark v1.9.33
[16:31:12] [Server thread/INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[16:31:12] [Server thread/INFO]: [AngelskyLobby] Enabling AngelskyLobby v1.0-SNAPSHOT
[16:31:12] [Server thread/INFO]: [AngelskyLobby] Instance API récupérée
[16:31:12] [Server thread/INFO]: Running delayed init tasks
[16:31:12] [Server thread/INFO]: Done (68.029s)! For help, type "help"
[16:31:12] [Server thread/INFO]: Timings Reset

**Comment by lucko** [comment]
https://luckperms.net/wiki/Storage-system-errors
