### ISSUE TITLE
LuckPerms could not load

### ISSUE THREAD

**Issue by monor2233223** [LuckPerms/LuckPerms#3496]
### Description

LuckPerms could not load

### Reproduction Steps

IDK

### Expected Behaviour

IDK

### Server Details

mohist 1.16.5 1077

### LuckPerms Version

v5.4.40

### Logs and Configs

Could not load 'plugins\LuckPerms-Bukkit-5.4.40.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: me.lucko.luckperms.common.loader.LoadingException: Unable to load bootstrap class
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:148) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: me.lucko.luckperms.common.loader.LoadingException: Unable to load bootstrap class
        at me.lucko.luckperms.common.loader.JarInJarClassLoader.instantiatePlugin(JarInJarClassLoader.java:97) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.<init>(BukkitLoaderPlugin.java:41) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341) ~[?:?]
        at java.lang.Class.newInstance(Class.java:677) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[forge:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class me.lucko.luckperms.bukkit.LPBukkitBootstrap
        at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.remappedFindClass(DelegateURLClassLoder.java:119) ~[forge:?]
        at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.findClass(DelegateURLClassLoder.java:75) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at me.lucko.luckperms.common.loader.JarInJarClassLoader.instantiatePlugin(JarInJarClassLoader.java:95) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.<init>(BukkitLoaderPlugin.java:41) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341) ~[?:?]
        at java.lang.Class.newInstance(Class.java:677) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[forge:?]
        ... 7 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 62
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284) ~[asm-9.1.jar:9.1]
        at com.mohistmc.bukkit.nms.remappers.MohistClassRepo.findClass0(MohistClassRepo.java:45) ~[mohist-1.16.5-1077-universal.jar:?]
        at net.md_5.specialsource.repo.CachingRepo.findClass(CachingRepo.java:46) ~[SpecialSource-1.8.5.jar:?]
        at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.findNormalParents(MohistInheritanceProvider.java:70) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.fineParents(MohistInheritanceProvider.java:41) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.getParents(MohistInheritanceProvider.java:34) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.getParents(MohistInheritanceProvider.java:28) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistJarMapping.tryClimb(MohistJarMapping.java:248) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.mapMethodName(MohistJarRemapper.java:169) ~[forge:?]
        at net.md_5.specialsource.UnsortedRemappingMethodAdapter.visitMethodInsn(UnsortedRemappingMethodAdapter.java:115) ~[SpecialSource-1.8.5.jar:?]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2425) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:721) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:401) ~[asm-9.1.jar:9.1]
        at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.remapClassFile(MohistJarRemapper.java:195) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.remapClassFile(MohistJarRemapper.java:177) ~[forge:?]
        at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.remappedFindClass(DelegateURLClassLoder.java:103) ~[forge:?]
        at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.findClass(DelegateURLClassLoder.java:75) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at me.lucko.luckperms.common.loader.JarInJarClassLoader.instantiatePlugin(JarInJarClassLoader.java:95) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.<init>(BukkitLoaderPlugin.java:41) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341) ~[?:?]
        at java.lang.Class.newInstance(Class.java:677) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[forge:?]
        ... 7 more
[11:12:21 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[11:12:43 WARN]: Legacy plugin ProtectionStones v1.4.1 does not specify an api-version.
[11:12:44 ERROR]: Could not load 'plugins\ProtectionStones-1.4.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:148) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:488) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[forge:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:152) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:111) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:488) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[forge:?]
        ... 7 more

### Extra Details

IDK

**Comment by OmegaWeaponDev** [comment]
Try downgrading your servers java version to something lower than java 18. If you're using 1.16.5 you could get away with using Java 11. Or at the max don't go any higher than java 17.

**Comment by monor2233223** [comment]
> Try downgrading your servers java version to something lower than java 18. If you're using 1.16.5 you could get away with using Java 11. Or at the max don't go any higher than java 17.

I don't know how or why but it worked thx
