### ISSUE TITLE
ERROR with Luck Perms | org.bukkit.plugin.InvalidPluginException: me.lucko.luckperms.common.loader.LoadingException: Unable to load bootstrap class

### ISSUE THREAD

**Issue by Singular11ty** [LuckPerms/LuckPerms#3498]
### Description

Code that sends:

Could not load 'plugins\LuckPerms-Bukkit-5.4.40 (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: me.lucko.luckperms.common.loader.LoadingException: Unable to load bootstrap class
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:148) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: me.lucko.luckperms.common.loader.LoadingException: Unable to load bootstrap class
        at me.lucko.luckperms.common.loader.JarInJarClassLoader.instantiatePlugin(JarInJarClassLoader.java:97) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.<init>(BukkitLoaderPlugin.java:41) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341) ~[?:?]
        at java.lang.Class.newInstance(Class.java:677) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[forge:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class me.lucko.luckperms.bukkit.LPBukkitBootstrap
        at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.remappedFindClass(DelegateURLClassLoder.java:119) ~[forge:?]
        at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.findClass(DelegateURLClassLoder.java:75) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at me.lucko.luckperms.common.loader.JarInJarClassLoader.instantiatePlugin(JarInJarClassLoader.java:95) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.<init>(BukkitLoaderPlugin.java:41) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341) ~[?:?]
        at java.lang.Class.newInstance(Class.java:677) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[forge:?]
        ... 7 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 62
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284) ~[asm-9.1.jar:9.1]
        at com.mohistmc.bukkit.nms.remappers.MohistClassRepo.findClass0(MohistClassRepo.java:45) ~[mohist-1.16.5-1082-universal.jar:?]
        at net.md_5.specialsource.repo.CachingRepo.findClass(CachingRepo.java:46) ~[SpecialSource-1.8.5.jar:?]
        at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.findNormalParents(MohistInheritanceProvider.java:70) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.fineParents(MohistInheritanceProvider.java:41) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.getParents(MohistInheritanceProvider.java:34) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.getParents(MohistInheritanceProvider.java:28) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistJarMapping.tryClimb(MohistJarMapping.java:248) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.mapMethodName(MohistJarRemapper.java:169) ~[forge:?]
        at net.md_5.specialsource.UnsortedRemappingMethodAdapter.visitMethodInsn(UnsortedRemappingMethodAdapter.java:115) ~[SpecialSource-1.8.5.jar:?]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2425) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:721) ~[asm-9.1.jar:9.1]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:401) ~[asm-9.1.jar:9.1]
        at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.remapClassFile(MohistJarRemapper.java:195) ~[forge:?]
        at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.remapClassFile(MohistJarRemapper.java:177) ~[forge:?]
        at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.remappedFindClass(DelegateURLClassLoder.java:103) ~[forge:?]
        at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.findClass(DelegateURLClassLoder.java:75) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at me.lucko.luckperms.common.loader.JarInJarClassLoader.instantiatePlugin(JarInJarClassLoader.java:95) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.<init>(BukkitLoaderPlugin.java:41) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341) ~[?:?]
        at java.lang.Class.newInstance(Class.java:677) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[forge:?]
        ... 7 more

### Reproduction Steps

Dosn't load the plugin i just installed it and instantly sent me that error.

### Expected Behaviour

Expected to work so i can start with permissions on my server.

### Server Details

Mohist Server

### LuckPerms Version

v5.4.40

**Comment by underscore11code** [comment]
Java version mismatch. The jar you are running appears to have been built for Java 18, you are running some version of Java older than that.

**Comment by lucko** [comment]
Aldo 
```
Caused by: java.lang.ClassNotFoundException: Failed to remap class me.lucko.luckperms.bukkit.LPBukkitBootstrap
at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.remappedFindClass(DelegateURLClassLoder.java:119) ~[forge:?]
```
