### ISSUE TITLE
Everytime I run a command, in the console it says LuckPerms isn't enabled and in game, it says an internal error occured.

### ISSUE THREAD

**Issue by GuyInTheAlley** [LuckPerms/LuckPerms#3499]
### Description

what the title says
console:
[01:18:38 INFO]: [Name] issued server command: /luckperms:perms
[01:18:38 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'luckperms:perms' in plugin LuckPerms v5.4.49 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.2.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-131]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2298) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2252) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1360) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1337) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1330) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1308) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1196) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-131]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
save-off

### Reproduction Steps

install LP on a paper 1.19.2 minehut server
type any command

### Expected Behaviour

"an internal error has occurred"

### Server Details

Paper- 1.19.2

### LuckPerms Version

earliest verion bukkit

### Extra Details

help.

**Comment by underscore11code** [comment]
There will be another error during startup, that's the actual issue.

**Comment by GuyInTheAlley** [comment]
do you know how to fix it?

**Comment by Aberdeener** [comment]
Please attach a *full* server log.
You can find the latest one at `logs/latest.log`, use https://pastes.dev to attach it. We cannot help until we have this

**Comment by GuyInTheAlley** [comment]
https://pastes.dev/olHZjfs18T
if you need another log please tell me

**Comment by LeotomasMC** [comment]
try deleting the `./plugins/luckperms/libs/` folder and restart

**Comment by GuyInTheAlley** [comment]
YES it worked
thank you so much
