### ISSUE TITLE
luckperms_players database errors

### ISSUE THREAD

**Issue by istarengwa** [LuckPerms/LuckPerms#3537]
### Description

I have deleted the database on mysql to start again on new, everything is created except the table 'luckperms_players' What is rather annoying because no one can connect or work on the server! 

### Reproduction Steps

I stop the server, I drop the tables, I restart the server, everything is created, except this table

### Expected Behaviour

I would just like the table to be created, if you ever have a SQL command to create the table properly, I accept too =)

### Server Details

pufferfish-paperclip-1.19.2-R0.1-SNAPSHOT-reobf

### LuckPerms Version

v5.4.55

### Logs and Configs

https://gist.github.com/istarengwa/0cc8b14756f2cf1a183b6f6667ffad60

### Extra Details

```shell
[13:21:54 ERROR]: [LuckPerms] Exception occurred whilst loading data for 1741a0db-2fe7-430b-a591-1f5df1a71b57 - Istarengwa
java.util.concurrent.CompletionException: java.sql.SQLSyntaxErrorException: Table 'luck_s3m1.luckperms_players' doesn't exist
        at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:93) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.sql.SQLSyntaxErrorException: Table 'luck_s3m1.luckperms_players' doesn't exist
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[?:?]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[?:?]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[?:?]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectPlayerData(SqlStorage.java:895) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:649) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$21(Storage.java:269) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:88) ~[?:?]
        ... 7 more

```

**Comment by lucko** [comment]
You can try creating the table manually using the relevant schema file: https://github.com/LuckPerms/LuckPerms/tree/master/common/src/main/resources/me/lucko/luckperms/schema
