### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Regomy** [LuckPerms/LuckPerms#3562]
### Description

[23:01:42 WARN]: [LuckPerms] An exception was thrown by com.earth2me.essentials.perm.impl.LuckPermsHandler$CombinedCalculator whilst calculating the context of subject CraftPlayer{name=Samurai_RxA}
java.lang.NullPointerException: null
at com.earth2me.essentials.perm.PermissionsHandler.lambda$initContexts$0(PermissionsHandler.java:231) ~[?:?]
at com.earth2me.essentials.perm.impl.LuckPermsHandler$CombinedCalculator.calculate(LuckPermsHandler.java:79) ~[?:?]
at com.earth2me.essentials.perm.impl.LuckPermsHandler$CombinedCalculator.calculate(LuckPermsHandler.java:65) ~[?:?]
at me.lucko.luckperms.common.context.manager.ContextManager.callContextCalculator(ContextManager.java:140) ~[?:?]
at me.lucko.luckperms.common.context.manager.ContextManager.calculate(ContextManager.java:159) ~[?:?]
at me.lucko.luckperms.common.context.manager.QueryOptionsCache.supply(QueryOptionsCache.java:54) ~[?:?]
at me.lucko.luckperms.common.context.manager.QueryOptionsCache.supply(QueryOptionsCache.java:42) ~[?:?]
at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64) ~[?:?]
at me.lucko.luckperms.common.context.manager.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59) ~[?:?]
at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:175) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:102) ~[server.jar:git-PaperSpigot-2ae641e3]
at dev.brighten.antivpn.bukkit.BukkitListener.onListener(BukkitListener.java:71) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-2ae641e3]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-PaperSpigot-2ae641e3]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-2ae641e3]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[server.jar:git-PaperSpigot-2ae641e3]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-PaperSpigot-2ae641e3]
at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:472) ~[server.jar:git-PaperSpigot-2ae641e3]
at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118) ~[server.jar:git-PaperSpigot-2ae641e3]
at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) ~[server.jar:git-PaperSpigot-2ae641e3]
at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) ~[server.jar:git-PaperSpigot-2ae641e3]
at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) ~[server.jar:git-PaperSpigot-2ae641e3]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:840) ~[server.jar:git-PaperSpigot-2ae641e3]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366) ~[server.jar:git-PaperSpigot-2ae641e3]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:678) ~[server.jar:git-PaperSpigot-2ae641e3]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:581) ~[server.jar:git-PaperSpigot-2ae641e3]
at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]

### Reproduction Steps

idk

### Expected Behaviour

1

### Server Details

1.8.8

### LuckPerms Version

Running LuckPerms v5.4.58

### Logs and Configs

1

### Extra Details

1

**Comment by lucko** [comment]
java.lang.NullPointerException: null
at com.earth2me.essentials.perm.PermissionsHandler.lambda$initContexts$0(PermissionsHandler.java:231) ~[?:?]

Please report to essentials
