### ISSUE TITLE
Fabric offline mode not working

### ISSUE THREAD

**Issue by SuperErnD** [LuckPerms/LuckPerms#3564]
### Description

[10:36:40] [luckperms-worker-14/ERROR]: Exception occurred whilst loading data for null - SuperErnD
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
        at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.getIfPresent(BoundedLocalCache.java:1904) ~[caffeine-2.9.0-remapped.jar:?]
        at me.lucko.luckperms.lib.caffeine.cache.LocalManualCache.getIfPresent(LocalManualCache.java:57) ~[caffeine-2.9.0-remapped.jar:?]
        at me.lucko.luckperms.common.util.ExpiringSet.contains(ExpiringSet.java:53) ~[LuckPerms-Fabric-5.4.58.jar:?]
        at me.lucko.luckperms.common.util.ExpiringSet.add(ExpiringSet.java:47) ~[LuckPerms-Fabric-5.4.58.jar:?]
        at me.lucko.luckperms.common.model.manager.user.UserHousekeeper.registerUsage(UserHousekeeper.java:58) ~[LuckPerms-Fabric-5.4.58.jar:?]
        at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.loadUser(AbstractConnectionListener.java:67) ~[LuckPerms-Fabric-5.4.58.jar:?]
        at me.lucko.luckperms.fabric.listeners.FabricConnectionListener.onPreLoginAsync(FabricConnectionListener.java:98) ~[LuckPerms-Fabric-5.4.58.jar:?]
        at me.lucko.luckperms.fabric.listeners.FabricConnectionListener.lambda$onPreLogin$0(FabricConnectionListener.java:80) ~[LuckPerms-Fabric-5.4.58.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
        
First join after installing luckperms kicking.

### Reproduction Steps

idk

### Expected Behaviour

that it will work

### Server Details

Fabric 1.19.3 0.14.12. LuckPerms latest

### LuckPerms Version

v5.4.58

### Logs and Configs

https://gist.github.com/SuperErnD/b03548d1d7502fea4c482a2f39d52f8b

**Comment by LeotomasMC** [comment]
are you using velocity by any chance? if so, you have set it up incorrectly, and its not a luckperms issue. if you are not using a proxy, send your mod list.

**Comment by SuperErnD** [comment]
I dont using velocity

**Comment by SuperErnD** [comment]
Offline mode. 
![image](https://user-images.githubusercontent.com/84639576/213205845-7fd73e6f-b5b8-4dba-9967-15241226a3e4.png)
I joining from 1.19.2

**Comment by underscore11code** [comment]
Are you able to reproduce with no other mods installed? This may be caused by your auth mod.

**Comment by LeotomasMC** [comment]
i reproduced it with only LP and fapi, so its not the auth mod

**Comment by martijnpu** [comment]
> Offline mode. ![image](https://user-images.githubusercontent.com/84639576/213205845-7fd73e6f-b5b8-4dba-9967-15241226a3e4.png) I joining from 1.19.2

"Offline mode". Does that mean the server is behind a bungee/velocity, or is it open for cracked players?

**Comment by underscore11code** [comment]
See comment above indicating proxy is not used.

**Comment by SuperErnD** [comment]
Any answer?

**Comment by senkmen18** [comment]
same issue on QuiltMC 1.19.3.
Offline mode on
