### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by York393098870** [LuckPerms/LuckPerms#3567]
### Description

When I set some permissions an error occured
[23:20:07 INFO]: Test issued server command: /lp user Test permission set dh.admin true
[23:20:07 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.java.JavaPlugin.getDescription()" because "loader.plugin" is null
[23:20:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235)
[23:20:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[23:20:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[23:20:07 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
[23:20:07 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[23:20:07 WARN]:        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.testUsernameValidity(AbstractLuckPermsPlugin.java:407)
[23:20:07 WARN]:        at me.lucko.luckperms.common.commands.user.UserParentCommand.parseTargetUniqueId(UserParentCommand.java:87)
[23:20:07 WARN]:        at me.lucko.luckperms.common.commands.user.UserParentCommand.parseTarget(UserParentCommand.java:103)
[23:20:07 WARN]:        at me.lucko.luckperms.common.commands.user.UserParentCommand.parseTarget(UserParentCommand.java:55)
[23:20:07 WARN]:        at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:93)
[23:20:07 WARN]:        at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:45)
[23:20:07 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:275)
[23:20:07 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:179)
[23:20:07 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[23:20:07 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:20:07 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:20:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> lp user Test permission set dh.admin true
[23:20:31 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.java.JavaPlugin.getDescription()" because "loader.plugin" is null
[23:20:31 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235)
[23:20:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[23:20:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[23:20:31 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
[23:20:31 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[23:20:31 WARN]:        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.testUsernameValidity(AbstractLuckPermsPlugin.java:407)
[23:20:31 WARN]:        at me.lucko.luckperms.common.commands.user.UserParentCommand.parseTargetUniqueId(UserParentCommand.java:87)
[23:20:31 WARN]:        at me.lucko.luckperms.common.commands.user.UserParentCommand.parseTarget(UserParentCommand.java:103)
[23:20:31 WARN]:        at me.lucko.luckperms.common.commands.user.UserParentCommand.parseTarget(UserParentCommand.java:55)
[23:20:31 WARN]:        at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:93)
[23:20:31 WARN]:        at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:45)
[23:20:31 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:275)
[23:20:31 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:179)
[23:20:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[23:20:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:20:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:20:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Reproduction Steps

I just write down /lp user Test permission set dh.admin true,and there was nothing output in the client.

### Expected Behaviour

I would like you to solve the problems of error.

### Server Details

Paper 1.19.2 latest

### LuckPerms Version

Bukkit-5.4.58

### Logs and Configs

Luckperms will sometimes crash

### Extra Details

 [Essentials] Permissions lag notice with (LuckPermsHandler). Response took 34.909000ms. Summary: Getting prefix for Y_PGDND

**Comment by underscore11code** [comment]
Have you `/reload`ed, plugman reloaded, or similar? That error shouldn't normally be possible. If so, restart the server, and read [this](https://madelinemiller.dev/blog/problem-with-reload/) for an explanation as to why you shouldn't.

Also, `latest` isn't a version number, please get an actual version number from `/ver` if restarting doesn't fix it.
