### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Regomy** [LuckPerms/LuckPerms#3568]
### Description

[07:09:55 WARN]: [LuckPerms] An exception was thrown by com.earth2me.essentials.perm.impl.LuckPermsHandler$CombinedCalculator whilst calculating the context of subject CraftPlayer{name=Sanpur}
java.lang.NullPointerException: null
at com.earth2me.essentials.perm.PermissionsHandler.lambda$initContexts$2(PermissionsHandler.java:232) ~[?:?]
at com.earth2me.essentials.perm.impl.LuckPermsHandler$CombinedCalculator.calculate(LuckPermsHandler.java:79) ~[?:?]
at com.earth2me.essentials.perm.impl.LuckPermsHandler$CombinedCalculator.calculate(LuckPermsHandler.java:65) ~[?:?]
at me.lucko.luckperms.common.context.manager.ContextManager.callContextCalculator(ContextManager.java:140) ~[?:?]
at me.lucko.luckperms.common.context.manager.ContextManager.calculate(ContextManager.java:159) ~[?:?]
at me.lucko.luckperms.common.context.manager.QueryOptionsCache.supply(QueryOptionsCache.java:54) ~[?:?]
at me.lucko.luckperms.common.context.manager.QueryOptionsCache.supply(QueryOptionsCache.java:42) ~[?:?]
at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64) ~[?:?]
at me.lucko.luckperms.common.context.manager.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59) ~[?:?]
at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:175) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:112) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at dev.brighten.antivpn.bukkit.BukkitListener.onListener(BukkitListener.java:71) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor37.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at net.minecraft.server.v1_12_R1.PlayerList.attemptLogin(PlayerList.java:570) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:152) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:417) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:159) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:990) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:788) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678) ~[patched_1.12.2.jar:git-Reaper-"1454595"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

### Reproduction Steps

1

### Expected Behaviour

1

### Server Details

[07:42:26 INFO]: This server is running Reaper version git-Reaper-"1454595" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) [07:42:26 INFO]: Checking version, please wait... [07:42:26 INFO]: You are 23 version(s) behind

### LuckPerms Version

Running LuckPerms v5.4.58

### Logs and Configs

1

### Extra Details

1

**Comment by underscore11code** [comment]
Please follow the issue template, notably the "Logs and Configs" section.
