### ISSUE TITLE
Bungee Console Crashing

### ISSUE THREAD

**Issue by ys050505** [LuckPerms/LuckPerms#3570]
### Description

18:19:33 [WARNING] [LuckPerms] A permission check was made for player Meliodas5104 - 0384b582-c31b-3e09-9865-79b6e4cc93be, but LuckPerms does not have any permissions data loaded for them. Perhaps their UUID has been altered since login?
java.lang.Exception
    at me.lucko.luckperms.bungee.listeners.BungeePermissionCheckListener.onPlayerPermissionCheck(BungeePermissionCheckListener.java:67)
    at jdk.internal.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
    at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:573)
    at com.lahuca.botsentry.bungee.d.a(Unknown Source)
    at com.lahuca.botsentry.d.b.d.a(Unknown Source)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at com.lahuca.botsentry.d.b.d.b(Unknown Source)
    at com.lahuca.botsentry.d.b.d.run(Unknown Source)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)

### Reproduction Steps

ytcfy

### Expected Behaviour

In Luckperms discord server no one is helping and there staff are just ignoring my issue and saying if someone will know they help me and its gonna 2 days i got zero support from there.

### Server Details

bungee 1.19

### LuckPerms Version

v5.4.58

### Logs and Configs

https://pastes.dev/NgzlLHcBl0

**Comment by underscore11code** [comment]
This error is usually caused by plugins modifying UUIDs improperly, usually either improperly configured Geyser, or poorly written offline mode authentication plugins.

**Comment by ys050505** [comment]
According to you how to config geyser properly

**Comment by ys050505** [comment]
> This error is usually caused by plugins modifying UUIDs improperly, usually either improperly configured Geyser, or poorly written offline mode authentication plugins.

And this problem is not coming with geyser it is coming from java uuid
