### ISSUE TITLE
Luckperms not connecting to my 1.8.8 server (hub server) but connecting on my other servers that are 1.16.5 to 1.19.3

### ISSUE THREAD

**Issue by GamerBoyAkash** [LuckPerms/LuckPerms#3571]
### Description

[08:20:48 INFO]: [LuckPerms] Enabling LuckPerms v5.4.58
[08:20:49 INFO]:         __    
[08:20:49 INFO]:   |    |__)   LuckPerms v5.4.58
[08:20:49 INFO]:   |___ |      Running on Bukkit - CraftBukkit
[08:20:49 INFO]: 
[08:20:49 INFO]: [LuckPerms] Loading configuration...
[08:20:50 INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[08:20:50 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
[08:20:50 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
[08:20:55 ERROR]: [LuckPerms] Failed to init storage implementation
java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174) ~[luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:169) ~[luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.storage.Storage.init(Storage.java:117) [luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88) [luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:185) [luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:177) [luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:51) [LuckPerms-Bukkit-5.4.58.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.sql.SQLNonTransientConnectionException: Too many connections
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
        ... 1 more
[08:20:55 INFO]: [LuckPerms] Loading messaging service... [SQL]
[08:21:00 ERROR]: [LuckPerms] Exception occurred whilst enabling SQL messaging service
java.lang.RuntimeException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5005ms.
        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:57) ~[luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:239) ~[luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:71) ~[luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:137) [luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.bukkit.messaging.BukkitMessagingFactory.getServiceFor(BukkitMessagingFactory.java:64) [luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:96) [luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:186) [luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:177) [luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:51) [LuckPerms-Bukkit-5.4.58.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5005ms.
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174) ~[luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:85) ~[luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:61) ~[luckperms-jarinjar7222291630745274471.jar.tmp:?]
        at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:55) ~[luckperms-jarinjar7222291630745274471.jar.tmp:?]
        ... 16 more
Caused by: java.sql.SQLNonTransientConnectionException: Too many connections
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-driver-8.0.23-remapped.jar:8.0.23]
        at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[hikari-4.0.3-remapped.jar:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
        ... 1 more
[08:21:00 WARN]: [LuckPerms] Messaging service 'sql' not recognised.
[08:21:00 INFO]: [LuckPerms] Loading internal permission managers...
[08:21:01 INFO]: [LuckPerms] Performing initial data load...
[08:21:06 WARN]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[08:21:06 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:106)
[08:21:06 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[08:21:06 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
[08:21:06 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[08:21:06 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[08:21:06 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[08:21:06 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[08:21:06 WARN]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[08:21:06 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:174)
[08:21:06 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:503)
[08:21:06 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$11(Storage.java:205)
[08:21:06 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:101)
[08:21:06 WARN]:        ... 6 more
[08:21:06 WARN]: Caused by: java.sql.SQLNonTransientConnectionException: Too many connections
[08:21:06 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
[08:21:06 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
[08:21:06 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[08:21:06 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08:21:06 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08:21:06 WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:21:06 INFO]: [LuckPerms] Successfully enabled. (took 17238ms)

### Reproduction Steps

dont know 

### Expected Behaviour

i am not sure 

### Server Details

1.8.8 server

### LuckPerms Version

5.4.58 

### Logs and Configs

https://gist.github.com/GamerBoyAkash/5f8c095c63437ef877975085afa0facc

### Extra Details

not connecting mysql on hub server 1.8.8 but connecting on other servers that are in 1.16.5 to 1.19.3

**Comment by supercoolspy** [comment]
It was unable to connect to the db within the available timeframe that you setup, maybe try increasing the timeout time
