### ISSUE TITLE
/lp editor

### ISSUE THREAD

**Issue by BaxAndrei** [LuckPerms/LuckPerms#3588]
### Description

/lp editor not working

### Reproduction Steps

use /lp editor

### Expected Behaviour

Show url without any error

### Server Details

This server is running Paper version git-Paper-399 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f2f9e8c)

### LuckPerms Version

LuckPerms v5.4.61

### Logs and Configs

```
[13:42:21 WARN]: [LuckPerms] Unable to establish socket connection
java.lang.RuntimeException: Timed out waiting to socket to connect
	at me.lucko.luckperms.common.webeditor.socket.WebEditorSocket.waitForConnect(WebEditorSocket.java:103) ~[?:?]
	at me.lucko.luckperms.common.webeditor.WebEditorSession.createSocket(WebEditorSession.java:96) ~[?:?]
	at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87) ~[?:?]
	at me.lucko.luckperms.common.webeditor.WebEditorSession.createAndOpen(WebEditorSession.java:62) ~[?:?]
	at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:111) ~[?:?]
	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56) ~[?:?]
	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48) ~[?:?]
	at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:275) ~[?:?]
	at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:179) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at me.lucko.luckperms.common.webeditor.socket.WebEditorSocket.waitForConnect(WebEditorSocket.java:101) ~[?:?]
	... 12 more
[13:42:26 WARN]: [LuckPerms] Command execution [editor] has not completed. Trace: 
  java.base@17.0.6/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
  java.base@17.0.6/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
  java.base@17.0.6/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
  java.base@17.0.6/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
  java.base@17.0.6/java.net.InetAddress.getAllByName0(Unknown Source)
  java.base@17.0.6/java.net.InetAddress.getAllByName(Unknown Source)
  java.base@17.0.6/java.net.InetAddress.getAllByName(Unknown Source)
  me.lucko.luckperms.lib.okhttp3.Dns.lambda$static$0(Dns.java:39)
  me.lucko.luckperms.lib.okhttp3.Dns$$Lambda$6227/0x0000000801d20a70.lookup(Unknown Source)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:135)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:78)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:104)
  me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:200)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:130)
  me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:88)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createAndOpen(WebEditorSession.java:62)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:111)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:275)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:179)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$8220/0x0000000802192360.run(Unknown Source)
  java.base@17.0.6/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.base@17.0.6/java.lang.Thread.run(Unknown Source)
[13:42:26 INFO]: [LP] Click the link below to open the editor:
[13:42:26 INFO]: https://luckperms.net/editor/XXXXXXX
```

### Extra Details

I am running it inside docker https://github.com/itzg/docker-minecraft-server/blob/master/README.md
Also, if you go to the link and make changes, then click Save/Apply, the same error appears in the console, and on the website it appears to use the command /lp applyedits XXXXXXXXX

**Comment by BaxAndrei** [comment]
EDIT: Maybe if timeout is increased will be ok https://github.com/LuckPerms/LuckPerms/blob/5c8b0a604e4300e485c3ad2d5368d2da10d687ff/common/src/main/java/me/lucko/luckperms/common/webeditor/WebEditorSession.java#L96
