### ISSUE TITLE
LuckPerms won't load after server restart

### ISSUE THREAD

**Issue by kolia22871** [LuckPerms/LuckPerms#3623]
### Description

LuckPerms won't load after server restart

> lp editor
[02:03:33 WARN]: java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: База данных уже закрыта
[02:03:33 WARN]: The database has been closed [90098-199]
[02:03:33 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:106)
[02:03:33 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[02:03:33 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
[02:03:33 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[02:03:33 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[02:03:33 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[02:03:33 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[02:03:33 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[02:03:33 WARN]: Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: База данных уже закрыта
[02:03:33 WARN]: The database has been closed [90098-199]
[02:03:33 WARN]:        at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
[02:03:33 WARN]:        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[02:03:33 WARN]:        at org.h2.message.DbException.get(DbException.java:194)
[02:03:33 WARN]:        at org.h2.engine.Session.getTransaction(Session.java:1709)
[02:03:33 WARN]:        at org.h2.engine.Session.startStatementWithinTransaction(Session.java:1729)
[02:03:33 WARN]:        at org.h2.command.Command.executeQuery(Command.java:196)
[02:03:33 WARN]:        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
[02:03:33 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectGroups(SqlStorage.java:999)
[02:03:33 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:504)
[02:03:33 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$11(Storage.java:205)
[02:03:33 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:101)
[02:03:33 WARN]:        ... 7 more
[02:03:33 WARN]: Caused by: java.lang.IllegalStateException: File corrupted in chunk 17095, expected page length 4..384, got 285347108 [1.4.199/6]
[02:03:33 WARN]:        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1055)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1606)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1571)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1603)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.inspectVersion(MVStore.java:1513)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1458)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.freeUnusedChunks(MVStore.java:1407)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.freeUnusedIfNeeded(MVStore.java:1400)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.storeNow(MVStore.java:1208)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.store(MVStore.java:1190)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.tryCommit(MVStore.java:1135)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2763)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3123)
[02:04:35 INFO]: [Matrix] (!) You are currently using free(trial) version of Matrix!
[02:05:04 ERROR]: [LuckPerms] Exception occurred whilst loading data for 18fb9874-5d20-376d-a655-1d7ef84f7be6 - FZPJCLBQ
java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: База данных уже закрыта
The database has been closed [90098-199]
        at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:93) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: База данных уже закрыта
The database has been closed [90098-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:617) ~[?:?]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:194) ~[?:?]
        at org.h2.engine.Session.getTransaction(Session.java:1709) ~[?:?]
        at org.h2.engine.Session.startStatementWithinTransaction(Session.java:1729) ~[?:?]
        at org.h2.command.Command.executeQuery(Command.java:196) ~[?:?]
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectPlayerData(SqlStorage.java:895) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:649) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$21(Storage.java:269) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:88) ~[?:?]
        ... 7 more
Caused by: java.lang.IllegalStateException: File corrupted in chunk 17095, expected page length 4..384, got 285347108 [1.4.199/6]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883) ~[?:?]
        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1055) ~[?:?]
        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1606) ~[?:?]
        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1571) ~[?:?]
        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1603) ~[?:?]
        at org.h2.mvstore.MVStore.inspectVersion(MVStore.java:1513) ~[?:?]
        at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1458) ~[?:?]
        at org.h2.mvstore.MVStore.freeUnusedChunks(MVStore.java:1407) ~[?:?]
        at org.h2.mvstore.MVStore.freeUnusedIfNeeded(MVStore.java:1400) ~[?:?]
        at org.h2.mvstore.MVStore.storeNow(MVStore.java:1208) ~[?:?]
        at org.h2.mvstore.MVStore.store(MVStore.java:1190) ~[?:?]
        at org.h2.mvstore.MVStore.tryCommit(MVStore.java:1135) ~[?:?]
        at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2763) ~[?:?]
        at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3123) ~[?:?]

### Reproduction Steps

restart server

### Expected Behaviour

server load

### Server Details

lasted paper 1.12.2

### LuckPerms Version

LuckPerms-Bukkit-5.4.41

### Logs and Configs

> lp editor
[02:03:33 WARN]: java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: База данных уже закрыта
[02:03:33 WARN]: The database has been closed [90098-199]
[02:03:33 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:106)
[02:03:33 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[02:03:33 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
[02:03:33 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[02:03:33 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[02:03:33 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[02:03:33 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[02:03:33 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[02:03:33 WARN]: Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: База данных уже закрыта
[02:03:33 WARN]: The database has been closed [90098-199]
[02:03:33 WARN]:        at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
[02:03:33 WARN]:        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[02:03:33 WARN]:        at org.h2.message.DbException.get(DbException.java:194)
[02:03:33 WARN]:        at org.h2.engine.Session.getTransaction(Session.java:1709)
[02:03:33 WARN]:        at org.h2.engine.Session.startStatementWithinTransaction(Session.java:1729)
[02:03:33 WARN]:        at org.h2.command.Command.executeQuery(Command.java:196)
[02:03:33 WARN]:        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115)
[02:03:33 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectGroups(SqlStorage.java:999)
[02:03:33 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:504)
[02:03:33 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$11(Storage.java:205)
[02:03:33 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:101)
[02:03:33 WARN]:        ... 7 more
[02:03:33 WARN]: Caused by: java.lang.IllegalStateException: File corrupted in chunk 17095, expected page length 4..384, got 285347108 [1.4.199/6]
[02:03:33 WARN]:        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1055)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1606)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1571)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1603)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.inspectVersion(MVStore.java:1513)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1458)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.freeUnusedChunks(MVStore.java:1407)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.freeUnusedIfNeeded(MVStore.java:1400)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.storeNow(MVStore.java:1208)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.store(MVStore.java:1190)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.tryCommit(MVStore.java:1135)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2763)
[02:03:33 WARN]:        at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3123)
[02:04:35 INFO]: [Matrix] (!) You are currently using free(trial) version of Matrix!
[02:05:04 ERROR]: [LuckPerms] Exception occurred whilst loading data for 18fb9874-5d20-376d-a655-1d7ef84f7be6 - FZPJCLBQ
java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: База данных уже закрыта
The database has been closed [90098-199]
        at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:93) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: База данных уже закрыта
The database has been closed [90098-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:617) ~[?:?]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:194) ~[?:?]
        at org.h2.engine.Session.getTransaction(Session.java:1709) ~[?:?]
        at org.h2.engine.Session.startStatementWithinTransaction(Session.java:1729) ~[?:?]
        at org.h2.command.Command.executeQuery(Command.java:196) ~[?:?]
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:115) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectPlayerData(SqlStorage.java:895) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:649) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$21(Storage.java:269) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.lambda$future$0(Storage.java:88) ~[?:?]
        ... 7 more
Caused by: java.lang.IllegalStateException: File corrupted in chunk 17095, expected page length 4..384, got 285347108 [1.4.199/6]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883) ~[?:?]
        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1055) ~[?:?]
        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1606) ~[?:?]
        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1571) ~[?:?]
        at org.h2.mvstore.MVStore$ChunkIdsCollector.visit(MVStore.java:1603) ~[?:?]
        at org.h2.mvstore.MVStore.inspectVersion(MVStore.java:1513) ~[?:?]
        at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1458) ~[?:?]
        at org.h2.mvstore.MVStore.freeUnusedChunks(MVStore.java:1407) ~[?:?]
        at org.h2.mvstore.MVStore.freeUnusedIfNeeded(MVStore.java:1400) ~[?:?]
        at org.h2.mvstore.MVStore.storeNow(MVStore.java:1208) ~[?:?]
        at org.h2.mvstore.MVStore.store(MVStore.java:1190) ~[?:?]
        at org.h2.mvstore.MVStore.tryCommit(MVStore.java:1135) ~[?:?]
        at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2763) ~[?:?]
        at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3123) ~[?:?]

**Comment by lucko** [comment]
Looks like your local database has got corrupted somehow. You options are to restore from a backup (hopefully you or your server host have some!) or try to repair the corrupt database following the H2 documentation.
