### ISSUE TITLE
How can ı fix it?

### ISSUE THREAD

**Issue by Ahmet-pc** [LuckPerms/LuckPerms#3637]
### Description

[10:58:29] [Server thread/INFO]: [LuckPerms] Loading configuration...
[10:58:29] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[10:58:29] [Server thread/WARN]: [LuckPerms] [DB Upgrade] Found an old (v1) H2 database file. LuckPerms will now attempt to upgrade it to v2 (this is a one time operation).
[10:58:29] [Server thread/INFO]: [LuckPerms] [DB Upgrade] Stage 1: Exporting the old database to an intermediary file...
[10:58:30] [Server thread/INFO]: [LuckPerms] [DB Upgrade] Stage 2: Importing the intermediary file into the new database...
[10:58:30] [Server thread/WARN]: [LuckPerms] Something went wrong whilst upgrading the LuckPerms database. Please report this on GitHub.
org.h2.jdbc.JdbcSQLSyntaxErrorException: Sequence "SYSTEM_SEQUENCE_54545851_DB25_4A63_B204_16FC9FDC2937" already exists; SQL statement:
           
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_54545851_DB25_4A63_B204_16FC9FDC2937" START WITH 1540 BELONGS_TO_TABLE [90035-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:632) ~[?:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:223) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:199) ~[?:?]
	at org.h2.command.ddl.CreateSequence.update(CreateSequence.java:53) ~[?:?]
	at org.h2.command.ddl.SchemaOwnerCommand.update(SchemaOwnerCommand.java:33) ~[?:?]
	at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
	at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
	at org.h2.command.dml.RunScriptCommand.execute(RunScriptCommand.java:108) ~[?:?]
	at org.h2.command.dml.RunScriptCommand.update(RunScriptCommand.java:70) ~[?:?]
	at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
	at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252) ~[?:?]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory$MigrateH2ToVersion2.run(H2ConnectionFactory.java:138) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.init(H2ConnectionFactory.java:68) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:166) ~[?:?]
	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:117) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:186) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:177) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:51) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Reproduction Steps

.

### Expected Behaviour

.

### Server Details

paper 1.17.1

### LuckPerms Version

LuckPerms-Bukkit-5.4.71

**Comment by lucko** [comment]
Your database seems to be corrupted, my advice would be to roll back to an earlier LuckPerms version (whenever things last worked), then run an `/lp export`, upgrade again, then re-import with `/lp import`
