### ISSUE TITLE
Something went wrong whilst upgrading the LuckPerms database.

### ISSUE THREAD

**Issue by Obseline** [LuckPerms/LuckPerms#3693]
### Description

`[16:46:53] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.94
[16:46:53] [Server thread/INFO]:         __
[16:46:53] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.94
[16:46:53] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[16:46:53] [Server thread/INFO]:
[16:46:53] [Server thread/INFO]: [LuckPerms] Loading configuration...
[16:46:54] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[16:46:54] [Server thread/WARN]: [LuckPerms] [DB Upgrade] Found an old (v1) H2 database file. LuckPerms will now attempt to upgrade it to v2 (this is a one time operation).
[16:46:54] [Server thread/INFO]: [LuckPerms] [DB Upgrade] Stage 1: Exporting the old database to an intermediary file...
[16:46:54] [Server thread/INFO]: [LuckPerms] [DB Upgrade] Stage 2: Importing the intermediary file into the new database...
[16:46:55] [Server thread/WARN]: [LuckPerms] Something went wrong whilst upgrading the LuckPerms database. Please report this on GitHub.
org.h2.jdbc.JdbcSQLSyntaxErrorException: Sequence "SYSTEM_SEQUENCE_4B501332_2EEC_4A53_9D27_08EB98F7EF2F" already exists; SQL statement:

CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_4B501332_2EEC_4A53_9D27_08EB98F7EF2F" START WITH 1 BELONGS_TO_TABLE [90035-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:632) ~[?:?]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:223) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:199) ~[?:?]
        at org.h2.command.ddl.CreateSequence.update(CreateSequence.java:53) ~[?:?]
        at org.h2.command.ddl.SchemaOwnerCommand.update(SchemaOwnerCommand.java:33) ~[?:?]
        at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
        at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
        at org.h2.command.dml.RunScriptCommand.execute(RunScriptCommand.java:108) ~[?:?]
        at org.h2.command.dml.RunScriptCommand.update(RunScriptCommand.java:70) ~[?:?]
        at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
        at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252) ~[?:?]
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory$MigrateH2ToVersion2.run(H2ConnectionFactory.java:137) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.init(H2ConnectionFactory.java:67) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:164) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.init(Storage.java:115) ~[?:?]
        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:87) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:184) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:50) ~[LuckPerms-Bukkit-5.4.94.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-47]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-47]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-47]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-47]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.1.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-47]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:46:55] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[16:46:55] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[16:46:55] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 2633ms)`

### Reproduction Steps

- Migrate from Minecraft 1.19.4 to 1.20.1
- Migrate to LuckPerms v5.4.94
- Run PaperMC server

### Expected Behaviour

I Expected to find out all my roles and permissions in game, have nothing anymore

### Server Details

paper-1.20.1-47 (MC: 1.20.1)

### LuckPerms Version

v5.4.94

### Logs and Configs

https://gist.github.com/Obseline/c6a421d1a25c56893547440408438a99

**Comment by lucko** [comment]
Please try the following steps:

1. stop your server
2. take a backup of the LuckPerms folder
3. in the LuckPerms folder, rename `luckperms-h2-v1-backup.mv.db` to `luckperms-h2.mv.db`
4. delete all other files related to "luckperms-h2". you should just have a file called `luckperms-h2.mv.db`
5. start the server again
