### ISSUE TITLE
java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by Osanchez** [LuckPerms/LuckPerms#3694]
### Description

I am seeing this error when I restart or stop my server.

### Reproduction Steps

luck perms is running on a bungeecord network

### Expected Behaviour

no errors.

### Server Details

Paper 1.20.1

### LuckPerms Version

 v5.4.98 

### Logs and Configs

[05:05:06 ERROR]: Error occurred (in the plugin loader) while disabling LuckPerms v5.4.98 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:130) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43) ~[paper-1.20.1.jar:git-Paper-31]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[paper-1.20.1.jar:git-Paper-31]
        at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[paper-1.20.1.jar:git-Paper-31]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:173) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:574) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.values(BoundedLocalCache.java:2639) ~[?:?]
        at me.lucko.luckperms.common.webeditor.store.WebEditorSocketMap.getSockets(WebEditorSocketMap.java:54) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:262) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onDisable(LPBukkitBootstrap.java:191) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onDisable(BukkitLoaderPlugin.java:55) ~[LuckPerms-Bukkit-5.4.98.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-31]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[paper-1.20.1.jar:git-Paper-31]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[paper-1.20.1.jar:git-Paper-31]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.disablePlugins(CraftServer.java:497) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:943) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:806) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1210) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-31]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LeotomasMC** [comment]
please use something like pastes.dev to upload a *full* log, not just the error

**Comment by Osanchez** [comment]
im not sure what youre askling for, but this error message should be all thats needed. there is a zip file that is being accessed but has already been closed

**Comment by LeotomasMC** [comment]
this error alone is not enough to tell you exactly what is causing it

**Comment by i998979** [comment]
The issue appears randomly. It still happens even if I have all my plugins freshly installed on paper server (non bungeecord, 1.19.4 and 1.20.1) and never messed with LuckPerms.
I don't know does @Osanchez has a plugin reloading plugin or not but personally I have PlugmanX installed, and this thing broke after paper plugin manager updates, don't know if PlugmanX broke something to get things to work or not and causing LuckPerms not to work.
Dunno whether the information helps or not, I just wanna give some ideas.

**Comment by LeotomasMC** [comment]
if you reloaded luckperms, then that is most likely the cause of the issue. reloading plugins is strongly discouraged for [exactly this reason](https://madelinemiller.dev/blog/problem-with-reload/#why-is-it-broken-and-unsafe).

**Comment by Osanchez** [comment]
just an FYI I see this error still and it happens whenever I execute a full server restart from pterodactyl console

**Comment by lucko** [comment]
This is always caused by reloading the server or plugins - nothing LP can do to fix it
