### ISSUE TITLE
error on bungeecord

### ISSUE THREAD

**Issue by L0RRIX-1** [LuckPerms/LuckPerms#3708]
### Description

[18:56:54 ERROR]: java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "/home/Server/proxy/plugins/LuckPerms/luckperms-h2-v2.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
[18:56:54 ERROR]:       at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:104)
[18:56:54 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[18:56:54 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[18:56:54 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:56:54 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:56:54 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[18:56:54 ERROR]: Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "/home/Server/proxy/plugins/LuckPerms/luckperms-h2-v2.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-214]
[18:56:54 ERROR]:       at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
[18:56:54 ERROR]:       at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
[18:56:54 ERROR]:       at org.h2.message.DbException.get(DbException.java:212)
[18:56:54 ERROR]:       at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:168)
[18:56:54 ERROR]:       at org.h2.mvstore.db.Store.<init>(Store.java:145)
[18:56:54 ERROR]:       at org.h2.engine.Database.<init>(Database.java:324)
[18:56:54 ERROR]:       at org.h2.engine.Engine.openSession(Engine.java:92)
[18:56:54 ERROR]:       at org.h2.engine.Engine.openSession(Engine.java:222)
[18:56:54 ERROR]:       at org.h2.engine.Engine.createSession(Engine.java:201)
[18:56:54 ERROR]:       at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
[18:56:54 ERROR]:       at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
[18:56:54 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:56:54 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:56:54 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:56:54 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:56:54 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:56:54 ERROR]:       at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.createConnection(H2ConnectionFactory.java:77)
[18:56:54 ERROR]:       at me.lucko.luckperms.common.storage.implementation.sql.connection.file.FlatfileConnectionFactory.getConnection(FlatfileConnectionFactory.java:70)
[18:56:54 ERROR]:       at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.getConnection(H2ConnectionFactory.java:43)
[18:56:54 ERROR]:       at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:508)
[18:56:54 ERROR]:       at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$11(Storage.java:203)
[18:56:54 ERROR]:       at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:99)
[18:56:54 ERROR]:       ... 5 more
[18:56:54 ERROR]: Caused by: org.h2.mvstore.MVStoreException: The file is locked: /home/Server/proxy/plugins/LuckPerms/luckperms-h2-v2.mv.db [2.1.214/7]
[18:56:54 ERROR]:       at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
[18:56:54 ERROR]:       at org.h2.mvstore.FileStore.open(FileStore.java:178)
[18:56:54 ERROR]:       at org.h2.mvstore.FileStore.open(FileStore.java:128)
[18:56:54 ERROR]:       at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
[18:56:54 ERROR]:       at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
[18:56:54 ERROR]:       at org.h2.mvstore.db.Store.<init>(Store.java:136)

### Reproduction Steps

.

### Expected Behaviour

.

### Server Details

waterfall 1.20.1

### LuckPerms Version

v5.30.7

**Comment by lucko** [comment]
Make sure you only have one instance of the server running from the same LP directory.
