### ISSUE TITLE
Something went wrong whilst upgrading the LuckPerms database. Please report this on GitHub.

### ISSUE THREAD

**Issue by kalleswe** [LuckPerms/LuckPerms#3716]
### Description

[08:26:03] [Server thread/WARN]: [LuckPerms] Something went wrong whilst upgrading the LuckPerms database. Please report this on GitHub.
org.h2.jdbc.JdbcSQLSyntaxErrorException: Sequence "SYSTEM_SEQUENCE_D9A7B1D8_4B3E_476C_B37A_BE42DD11EA51" already exists; SQL statement:
            
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D9A7B1D8_4B3E_476C_B37A_BE42DD11EA51" START WITH 1 BELONGS_TO_TABLE [90035-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:632) ~[?:?]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:223) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:199) ~[?:?]
        at org.h2.command.ddl.CreateSequence.update(CreateSequence.java:53) ~[?:?]
        at org.h2.command.ddl.SchemaOwnerCommand.update(SchemaOwnerCommand.java:33) ~[?:?]
        at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
        at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
        at org.h2.command.dml.RunScriptCommand.execute(RunScriptCommand.java:108) ~[?:?]
        at org.h2.command.dml.RunScriptCommand.update(RunScriptCommand.java:70) ~[?:?]
        at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
        at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252) ~[?:?]
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory$MigrateH2ToVersion2.run(H2ConnectionFactory.java:137) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.init(H2ConnectionFactory.java:67) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:164) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.init(Storage.java:115) ~[?:?]
        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:87) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:184) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:50) ~[LuckPerms-Bukkit-5.4.82.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-83]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-83]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.1.jar:git-Paper-83]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-83]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Reproduction Steps

1. load the plugin
2. watch the logfile

### Expected Behaviour

No error messages

### Server Details

paper 1.20.1-68

### LuckPerms Version

5.4.82

**Comment by lucko** [comment]
See the comments on the other issues for suggestions on how to resolve: https://github.com/LuckPerms/LuckPerms/issues?q=Something+went+wrong+whilst+upgrading+the+LuckPerms+database
