### ISSUE TITLE
luckperms-migration-groupmanager not working on the latest version

### ISSUE THREAD

**Issue by PirataGu** [LuckPerms/LuckPerms#3737]
### Description

While using luckperms-migration-groupmanager.jar on the latest version on minecraft 1.20.1 and with the latest groupmanager version It doesn't finish the migration:

### Reproduction Steps

Everything said on the wiki.

### Expected Behaviour

To have migrated but nothing is actually migrated.

### Server Details

git-Purpur-2017 (MC: 1.20.1)

### LuckPerms Version

v5.4.40

### Logs and Configs

[23:02:40 INFO]: PirataGu issued server command: /migrate-groupmanager
[23:02:40 INFO]: [luckperms-migration-groupmanager] Starting.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Starting global group migration.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 1 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 2 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 3 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 4 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 5 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 6 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 7 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 8 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 9 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 10 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 11 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 12 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 13 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 14 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 15 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 16 groups so far.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 16 global groups
[23:02:40 INFO]: [luckperms-migration-groupmanager] Collecting user and group data.
[23:02:40 INFO]: [luckperms-migration-groupmanager] Querying world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 1 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 2 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 3 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 4 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 5 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 6 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 7 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 8 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 9 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 10 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 11 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 12 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 13 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 14 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 15 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 16 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 17 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 18 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 19 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 20 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 21 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 22 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 23 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 24 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 25 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 26 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 27 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 28 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 29 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 30 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 31 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 32 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 33 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 34 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 35 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 36 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 37 groups so far in world survival2023
[23:02:40 INFO]: [luckperms-migration-groupmanager] Migrated 37 groups in world survival2023
[23:02:40 WARN]: [luckperms-migration-groupmanager] Plugin luckperms-migration-groupmanager v1 generated an exception while executing task 848
java.lang.NoSuchMethodError: 'org.anjocaido.groupmanager.data.UserVariables org.anjocaido.groupmanager.data.User.getVariables()'
        at me.lucko.luckperms.migration.MigrationGroupManager.lambda$runMigration$5(MigrationGroupManager.java:191) ~[luckperms-migration-groupmanager.jar:?]
        at me.lucko.luckperms.migration.Iterators.tryIterate(Iterators.java:38) ~[luckperms-migration-groupmanager.jar:?]
        at me.lucko.luckperms.migration.MigrationGroupManager.lambda$runMigration$6(MigrationGroupManager.java:159) ~[luckperms-migration-groupmanager.jar:?]
        at me.lucko.luckperms.migration.Iterators.tryIterate(Iterators.java:51) ~[luckperms-migration-groupmanager.jar:?]
        at me.lucko.luckperms.migration.MigrationGroupManager.runMigration(MigrationGroupManager.java:118) ~[luckperms-migration-groupmanager.jar:?]
        at me.lucko.luckperms.migration.MigrationJavaPlugin.lambda$onCommand$0(MigrationJavaPlugin.java:37) ~[luckperms-migration-groupmanager.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2017]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2017]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LeotomasMC** [comment]
this issue should probably be moved to https://github.com/LuckPerms/migration
