### ISSUE TITLE
No support for ipv6 address for database

### ISSUE THREAD

**Issue by masmc05** [LuckPerms/LuckPerms#3753]
### Description

https://github.com/LuckPerms/LuckPerms/blob/f12d3cd8ba47fb0d25f7c13e1f3a89d770bd34a6/common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/hikari/HikariConnectionFactory.java#L122-L125

This will never work with address of type [xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:YYYY

### Reproduction Steps

Use ipv6 for database

### Expected Behaviour

For it to work

### Server Details

This server is running Purpur version git-Purpur-2056 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: bd327ae on HEAD)

### LuckPerms Version

[LuckPerms] Enabling LuckPerms v5.4.102

### Extra Details

You could try to separate only the latest : if the string doesn't end in ], the rest to go untouched, as an address with of form [xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx] should be valid for hikari

**Comment by masmc05** [comment]
Same with https://github.com/LuckPerms/LuckPerms/blob/f12d3cd8ba47fb0d25f7c13e1f3a89d770bd34a6/common/src/main/java/me/lucko/luckperms/common/messaging/redis/RedisMessenger.java#L88-L92

**Comment by lucko** [comment]
Recategorising this as a suggestion - I will accept a good PR to implement this functionality for the storage backends that support IPv6 :)

**Comment by vovamod** [comment]
It works flawlessly after last updates. Only got an issue if MariaDB is set as storage-method over MySQL. It will error out similar to this (seems to be no IPV6 address support for this method or validation went for a walk):
```sh
[00:34:33 INFO] [luckperms]: Loading configuration...
[00:34:33 INFO]:         __    
[00:34:33 INFO]:   |    |__)   LuckPerms v5.5.34
[00:34:33 INFO]:   |___ |      Running on Velocity - Velocity
[00:34:33 INFO]: 
[00:34:33 INFO] [luckperms]: Loading storage provider... [MARIADB]
[00:34:33 INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Starting...
[00:34:33 INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Start completed.
[00:34:38 ERROR] [luckperms]: Failed to init storage implementation
java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms (total=0, active=0, idle=0, waiting=0)
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:709) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:188) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:146) ~[?:?]
        at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:99) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:173) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:170) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.init(Storage.java:90) ~[?:?]
        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:210) ~[?:?]
        at me.lucko.luckperms.velocity.LPVelocityBootstrap.onEnable(LPVelocityBootstrap.java:140) ~[?:?]
        at me.lucko.luckperms.velocity.Lmbda$5.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.5.0-SNAPSHOT-576.jar:3.5.0-SNAPSHOT (git-c2fd3c07-b576)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:553) ~[velocity-3.5.0-SNAPSHOT-576.jar:3.5.0-SNAPSHOT (git-c2fd3c07-b576)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:542) ~[velocity-3.5.0-SNAPSHOT-576.jar:3.5.0-SNAPSHOT (git-c2fd3c07-b576)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1474) [?:?]
Caused by: java.sql.SQLException: Incorrect port value : 4f8
        at me.lucko.luckperms.lib.mariadb.HostAddress.getPort(HostAddress.java:195) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.HostAddress.parseSimpleHostAddress(HostAddress.java:173) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.HostAddress.parse(HostAddress.java:141) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.Configuration.parseInternal(Configuration.java:726) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.Configuration.parse(Configuration.java:670) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.Driver.connect(Driver.java:99) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.Driver.connect(Driver.java:29) ~[?:?]
        at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:139) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:368) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:483) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:747) ~[?:?]
        at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328) ~[?:?]
        ... 3 more
```
Version used: v5.5.34 (Velocity)
Velocity version can be ignored since it was upgraded after. This error is gone if used Postgre or MySQL storage-method
Address is in scopes. Example: `address: '[IPV6_HERE]'`
