### ISSUE TITLE
1.16.5 arclight issue with /lp editor

### ISSUE THREAD

**Issue by K1nton** [LuckPerms/LuckPerms#3754]
### Description

when i am executing /lp editor in console i am getting this error:

>....=>....Sep 21, 2023 8:46:14 PM org.bukkit.craftbukkit.v1_16_R3.CraftServer dispatchServerCommand
WARNING: Unexpected exception while parsing console command "lp editor"
org.bukkit.command.CommandException: Cannot execute command 'lp' in plugin LuckPerms v5.4.40 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:761)
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServerMixin.java:746)
at net.minecraft.server.dedicated.DedicatedServer.redirect$bbk000$arclight$serverCommandEvent(DedicatedServerMixin.java:655)
at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServerMixin.java:312)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:292)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787)
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917)
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
at java.lang.Thread.run(Thread.java:750)

### Reproduction Steps

install 1.16.5 arclight on aternos
install luckperms
run /lp editor in console

### Expected Behaviour

expected getting access to a luckperms editor

### Server Details

arclight (forge(379 - 36.2.39), 1.16.5)

### LuckPerms Version

v5.4.40

### Extra Details

i am also using essentialsX, and i have tryed to run on the latest version of luckperms and got the same issue

**Comment by lucko** [comment]
Bukkit/forge hybrids are not supported
