### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by SlyGuy89** [LuckPerms/LuckPerms#3776]
### Description

Been receiving this console error on startup for a while, not sure what it means or how it may be affecting the plugin, but it seems to function normally.

```
[20:00:42] [Server thread/WARN]: [LuckPerms] Something went wrong whilst upgrading the LuckPerms database. Please report this on GitHub.
org.h2.jdbc.JdbcSQLSyntaxErrorException: Sequence "SYSTEM_SEQUENCE_309C4C1F_74E2_48DF_8AD2_05734C385094" already exists; SQL statement:
            
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_309C4C1F_74E2_48DF_8AD2_05734C385094" START WITH 1318 BELONGS_TO_TABLE [90035-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:632) ~[?:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:223) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:199) ~[?:?]
	at org.h2.command.ddl.CreateSequence.update(CreateSequence.java:53) ~[?:?]
	at org.h2.command.ddl.SchemaOwnerCommand.update(SchemaOwnerCommand.java:33) ~[?:?]
	at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
	at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
	at org.h2.command.dml.RunScriptCommand.execute(RunScriptCommand.java:108) ~[?:?]
	at org.h2.command.dml.RunScriptCommand.update(RunScriptCommand.java:70) ~[?:?]
	at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
	at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252) ~[?:?]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory$MigrateH2ToVersion2.run(H2ConnectionFactory.java:144) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.init(H2ConnectionFactory.java:68) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:164) ~[?:?]
	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:115) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:87) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:193) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:50) ~[LuckPerms-Bukkit-5.4.102.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-260]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-260]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-260]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-260]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-260]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Reproduction Steps

On startup

### Expected Behaviour

No error

### Server Details

git-Paper-260 MC: 1.20.2

### LuckPerms Version

v5.4.102

**Comment by lucko** [comment]
Please see the suggestions/comments on the linked issues: https://github.com/LuckPerms/LuckPerms/issues?q=Something+went+wrong+whilst+upgrading+the+LuckPerms+database
