### ISSUE TITLE
RCON ProxiedCommandSender crash

### ISSUE THREAD

**Issue by ZuVEnO** [LuckPerms/LuckPerms#3780]
### Description

When i trying to give someone group through RCON it crashes and did nothing

### Reproduction Steps

1. Opening RCON Site (CraftingStore for example)
2. Clicking on Execute manual payment
3. Server got RCON request.
4. LuckPerms is leaking down...

### Expected Behaviour

When i clicked "Execute manual payment" on Minecraft store panel, it shows a RCON connection and after that LuckPerms crashes (RCON No answer)

### Server Details

1.7.10 Thermos (Cauldron fork)

### LuckPerms Version

[v5.4.108] Legacy

### Logs and Configs

```
[20:01:52 INFO]: Rcon connection from: [REDACTED]
[20:01:53 WARN]: java.lang.NoClassDefFoundError: org/bukkit/command/ProxiedCommandSender
[20:01:53 WARN]:        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.sender(BukkitAudiencesImpl.java:121)
[20:01:53 WARN]:        at me.lucko.luckperms.bukkit.BukkitSenderFactory.sendMessage(BukkitSenderFactory.java:68)
[20:01:53 WARN]:        at me.lucko.luckperms.bukkit.BukkitSenderFactory.sendMessage(BukkitSenderFactory.java:40)
[20:01:53 WARN]:        at me.lucko.luckperms.common.sender.AbstractSender.sendMessage(AbstractSender.java:83)
[20:01:53 WARN]:        at me.lucko.luckperms.common.locale.Message$Args4.send(Message.java:4402)
[20:01:53 WARN]:        at me.lucko.luckperms.common.commands.generic.parent.ParentAddTemp.execute(ParentAddTemp.java:94)
[20:01:53 WARN]:        at me.lucko.luckperms.common.command.abstraction.GenericParentCommand.execute(GenericParentCommand.java:89)
[20:01:53 WARN]:        at me.lucko.luckperms.common.command.abstraction.GenericParentCommand.execute(GenericParentCommand.java:49)
[20:01:53 WARN]:        at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:107)
[20:01:53 WARN]:        at me.lucko.luckperms.common.command.abstraction.ParentCommand.execute(ParentCommand.java:44)
[20:01:53 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
[20:01:53 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
[20:01:53 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[20:01:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:01:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:01:53 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by emilyy-dev** [comment]
> `java.lang.NoClassDefFoundError: org/bukkit/command/ProxiedCommandSender`

`ProxiedCommandSender` is a class that must be present in all Bukkit servers, hybrids are not really supported for reasons like this. If you can reproduce this issue on a supported Bukkit server (CraftBukkit/Spigot/Paper) then it ought to be fixed, but otherwise the hybrid environment is at fault here.
