### ISSUE TITLE
Luckperms-hikari - Failed to validate connection

### ISSUE THREAD

**Issue by mysticcraftnetwork** [LuckPerms/LuckPerms#3796]
### Description

[20:15:18] [luckperms-worker-8/WARN]: [me.lucko.luckperms.lib.hikari.pool.PoolBase] luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl@615c29e2 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[20:15:18] [luckperms-worker-8/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5056ms.
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:172)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:84)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.pollMessages(AbstractSqlMessenger.java:114)
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[20:15:18] [luckperms-worker-8/WARN]: Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2495)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:566)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[20:15:18] [luckperms-worker-8/WARN]: 	... 11 more
[20:15:18] [luckperms-worker-8/WARN]: Caused by: me.lucko.luckperms.lib.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:15:18] [luckperms-worker-8/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.NativeSession.checkClosed(NativeSession.java:1171)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:573)
[20:15:18] [luckperms-worker-8/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2491)
[20:15:18] [luckperms-worker-8/WARN]: 	... 14 more
[20:15:24] [luckperms-worker-2/WARN]: [me.lucko.luckperms.lib.hikari.pool.PoolBase] luckperms-hikari - Failed to validate connection me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl@1dbb9ad5 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[20:15:24] [luckperms-worker-2/WARN]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5003ms.
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:172)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:84)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.pollMessages(AbstractSqlMessenger.java:114)
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[20:15:24] [luckperms-worker-2/WARN]: Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2495)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:566)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
[20:15:24] [luckperms-worker-2/WARN]: 	... 11 more
[20:15:24] [luckperms-worker-2/WARN]: Caused by: me.lucko.luckperms.lib.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:15:24] [luckperms-worker-2/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.NativeSession.checkClosed(NativeSession.java:1171)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:573)
[20:15:24] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2491)
[20:15:24] [luckperms-worker-2/WARN]: 	... 14 more

### Reproduction Steps

Last night strange errors in the console, if you can tell what they are and how I can fix them. The server started to lag and kicked out all the players

### Expected Behaviour

I'm waiting to find out where the problem is

### Server Details

git-Paper-160 (MC: 1.20.1)

### LuckPerms Version

v.5.4.102

**Comment by emilyy-dev** [comment]
This is a problem with either the database server or the connection configuration in your LP config. See https://luckperms.net/wiki/Storage-system-errors for more info.
