### ISSUE TITLE
Parsing Selector support

### ISSUE THREAD

**Issue by Reaviik** [LuckPerms/LuckPerms#3818]
### Description

I am currently using FTB-Quests to set the progression level of each player as well as other things, however in version 1.20.1 the parsing selector does not seem to be supported by LP as in previous versions, even though the command-selectors option is enabled. Would there be any way to get around this? waiting for an update

### Proposed Behaviour

version - 5.4.116

### Extra Details

`[16:13:49 WARN] [LuckPerms]: Error parsing selector '@p' for CraftPlayer{name=Reavik} executing [user, @p, meta, addsuffix, 3, &f𓆗&f]
java.lang.IllegalArgumentException: Could not parse selector: @p
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.selectEntities(CraftServerMixin.java:2378) ~[arclight-1.20.1-1.0.2-730181a4.jar%23314!/:arclight-1.20.1-1.0.2-730181a4]
        at me.lucko.luckperms.bukkit.BukkitCommandExecutor.resolveSelectors(BukkitCommandExecutor.java:140) ~[?:?]
        at me.lucko.luckperms.bukkit.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:81) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight-1.20.1-1.0.2-730181a4.jar%23314!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight-1.20.1-1.0.2-730181a4.jar%23314!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServerMixin.java:877) ~[arclight-1.20.1-1.0.2-730181a4.jar%23314!/:arclight-1.20.1-1.0.2-730181a4]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[arclight-1.20.1-1.0.2-730181a4.jar%23314!/:arclight-1.20.1-1.0.2-730181a4]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar%23110!/:?]
        at net.minecraft.commands.Commands.m_242674_(CommandsMixin.java:257) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.commands.Commands.m_230957_(CommandsMixin.java:237) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at dev.ftb.mods.ftbquests.quest.reward.CommandReward.claim(CommandReward.java:104) ~[ftb-quests-forge-2001.3.0.jar%23381!/:2001.3.0]
        at dev.ftb.mods.ftbquests.quest.TeamData.claimReward(TeamData.java:539) ~[ftb-quests-forge-2001.3.0.jar%23381!/:2001.3.0]
        at dev.ftb.mods.ftbquests.net.ClaimRewardMessage.handle(ClaimRewardMessage.java:49) ~[ftb-quests-forge-2001.3.0.jar%23381!/:2001.3.0]
        at dev.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52) ~[architectury-9.1.12-forge.jar%23327!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23467!/:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Selector not allowed`

**Comment by emilyy-dev** [comment]
Hybrids are not supported, the setting works correctly on Bukkit servers, the Forge build of LP also has the same setting, maybe that version will work better.
