### ISSUE TITLE
Failed to init storage implementation

### ISSUE THREAD

**Issue by Segund1a** [LuckPerms/LuckPerms#3832]
### Description

I can't get it to work even with local or MySQL it gives the same error, I'm using arclight with some mods

### Reproduction Steps

I just put the mod together with pixelmon in arclight and it gave this error 

### Expected Behaviour

I hoped everything would go well because they told me that arclight is good for luckperms

### Server Details

arclight-forge-1.16.5-1.0.25.jar

### LuckPerms Version

5.4.117

### Logs and Configs

https://gist.github.com/Segund1a/04fd62f9d92f1ac22a3bd9aa8d5dd651

**Comment by underscore11code** [comment]
> Caused by: java.net.UnknownHostException: sql204.infinityfree.com

Either your server is having DNS issues (ensure your server has a stable internet connection), or that domain doesn't exist.

Hybrids are also not supported, so use LuckPerms on ArcLight at your own risk.

**Comment by Segund1a** [comment]
I will try to do it locally

**Comment by Segund1a** [comment]
LuckPerms/]: Failed to init storage implementation
java.lang.RuntimeException: java.lang.NoSuchMethodException: org.h2.jdbc.JdbcConnection.<init>(java.lang.String,java.util.Properties,java.lang.String,java.lang.Object,boolean)
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.init(H2ConnectionFactory.java:64) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:162) ~[?:?]
	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:114) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:87) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:201) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServerMixin.java:492) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServerMixin.java:406) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at net.minecraft.server.dedicated.DedicatedServer.handler$bak000$arclight$loadPlugins(DedicatedServerMixin.java:638) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1879) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NoSuchMethodException: org.h2.jdbc.JdbcConnection.<init>(java.lang.String,java.util.Properties,java.lang.String,java.lang.Object,boolean)
	at java.lang.Class.getConstructor0(Class.java:3585) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.init(H2ConnectionFactory.java:62) ~[?:?]
	... 16 more
[06Feb2024 17:42:14.732] [Server thread/INFO] [LuckPerms/]: Loading internal permission managers...
[06Feb2024 17:42:15.219] [Server thread/INFO] [LuckPerms/]: Performing initial data load...
[06Feb2024 17:42:15.230] [Server thread/INFO] [STDERR/]: [me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin:enable:250]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "this.connectionConstructor" is null
[06Feb2024 17:42:15.231] [Server thread/INFO] [STDERR/]: [me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin:enable:250]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[06Feb2024 17:42:15.231] [Server thread/INFO] [STDERR/]: [me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin:enable:250]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[06Feb2024 17:42:15.231] [Server thread/INFO] [STDERR/]: [me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin:enable:250]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
[06Feb2024 17:42:15.231] [Server thread/INFO] [STDERR/]: [me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin:enable:250]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[06Feb2024 17:42:15.231] [Server thread/INFO] [STDERR/]: [me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin:enable:250]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[06Feb2024 17:42:15.231] [Server thread/INFO] [STDERR/]: [me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin:enable:250]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[06Feb2024 17:42:15.231] [Server thread/INFO] [STDERR/]: [me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin:enable:250]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[06Feb2024 17:42:15.231] [Server thread/INFO] [STDERR/]: [me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin:enable:250]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[06Feb2024 17:42:15.231] [Server thread/INFO] [STDERR/]: [me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin:enable:250]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[06Feb2024 17:42:15.231] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]: Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "this.connectionConstructor" is null
[06Feb2024 17:42:15.232] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.createConnection(H2ConnectionFactory.java:77)
[06Feb2024 17:42:15.232] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.FlatfileConnectionFactory.getConnection(FlatfileConnectionFactory.java:64)
[06Feb2024 17:42:15.232] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.getConnection(H2ConnectionFactory.java:43)
[06Feb2024 17:42:15.232] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:496)
[06Feb2024 17:42:15.232] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]: 	at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$11(Storage.java:202)
[06Feb2024 17:42:15.232] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]: 	at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:98)
[06Feb2024 17:42:15.232] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[06Feb2024 17:42:15.232] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:650]: 	... 6 more
