### ISSUE TITLE
[LuckPerms] Unable to establish socket connection

### ISSUE THREAD

**Issue by xZinio** [LuckPerms/LuckPerms#3834]
### Error:
```
>lp editor
[05:10:27 INFO]: [LP] Preparing a new editor session, please wait...
java.net.ConnectException: Failed to connect to usersockets.luckperms.net/2606:4700:20:0:0:0:681a:ec0:443
        at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81) ~[?:?]
        at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47) ~[?:?]
        at me.lucko.luckperms.common.http.BytesocksClient.createSocket(BytesocksClient.java:67) ~[?:?]
        at me.lucko.luckperms.common.webeditor.socket.WebEditorSocket.initialize(WebEditorSocket.java:88) ~[?:?]
        at me.lucko.luckperms.common.webeditor.WebEditorSession.createSocket(WebEditorSession.java:94) ~[?:?]
        at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:86) ~[?:?]
        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110) ~[?:?]
        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55) ~[?:?]
        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47) ~[?:?]
        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279) ~[?:?]
        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_372]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_372]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_372]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
Caused by: java.net.ConnectException: Network is unreachable (connect failed)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_372]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_372]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_372]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_372]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_372]
        at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_372]
        at me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:130) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263) ~[?:?]
        ... 32 more

[05:10:27 WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[05:10:27 WARN]:  at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:210)
[05:10:27 WARN]:  at me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)
[05:10:27 WARN]:  at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)
[05:10:27 WARN]:  at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[05:10:27 WARN]:  at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
[05:10:27 WARN]:  at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
[05:10:27 WARN]:  at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
[05:10:27 WARN]:  at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
[05:10:27 WARN]:  at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[05:10:27 WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[05:10:27 WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[05:10:27 WARN]:  at java.lang.Thread.run(Thread.java:750)
[05:10:27 WARN]: Caused by: java.net.ConnectException: Failed to connect to usercontent.luckperms.net/2606:4700:20:0:0:0:681a:fc0:443
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[05:10:27 WARN]:  at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[05:10:27 WARN]:  at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)
[05:10:27 WARN]:  at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)
[05:10:27 WARN]:  at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)
[05:10:27 WARN]:  ... 11 more
[05:10:27 WARN]: Caused by: java.net.ConnectException: Network is unreachable (connect failed)
[05:10:27 WARN]:  at java.net.PlainSocketImpl.socketConnect(Native Method)
[05:10:27 WARN]:  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[05:10:27 WARN]:  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[05:10:27 WARN]:  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[05:10:27 WARN]:  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[05:10:27 WARN]:  at java.net.Socket.connect(Socket.java:607)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
[05:10:27 WARN]:  at me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
[05:10:27 WARN]:  ... 33 more
[05:10:27 INFO]: [LP] Unable to communicate with the editor. Check the console for errors.
```

### /lp info Output:
```
[05:12:20 INFO]: [LP] Running LuckPerms v5.4.117 by Luck.
[05:12:20 INFO]: [LP] -  Platform: Bukkit
[05:12:20 INFO]: [LP] -  Server Brand: Mohist
[05:12:20 INFO]: [LP] -  Server Version:
[05:12:20 INFO]: [LP]      git-Mohist-1.12.2-343 (MC: 1.12.2) - 1.12.2-R0.1-SNAPSHOT
[05:12:20 INFO]: [LP] -  Storage:
[05:12:20 INFO]: [LP]      Type: H2
[05:12:20 INFO]: [LP]      File Size: 0.05MB
[05:12:20 INFO]: [LP] -  Extensions:
[05:12:20 INFO]: [LP]      None
[05:12:20 INFO]: [LP] -  Messaging: None
[05:12:20 INFO]: [LP] -  Instance:
[05:12:20 INFO]: [LP]      Static contexts: None
[05:12:20 INFO]: [LP]      Online Players: 1 (1 unique)
[05:12:20 INFO]: [LP]      Uptime: 27m 40s
[05:12:20 INFO]: [LP]      Local Data: 1 users, 4 groups, 0 tracks
```

### Reproduction Steps

Just run /lp editor.

### Expected Behaviour

The Editor to open.

### Server Details

git-Mohist-1.12.2-343 (MC: 1.12.2) - 1.12.2-R0.1-SNAPSHOT

### LuckPerms Version

v5.4.117

### Extra Details

Everything about LockPerms seems to be working just fine except the web editor, which I would really like to use since it's great.
Minecraft Server is running on a Debian 12 Server with 10 GB of RAM and a 4 Core Processor.

I saw one other Github issue where it was said this might be a firewall issue, but since I haven't set up a firewall, I do not know how to fix that.

**Comment by Slimified** [comment]
Please try this with a fresh install of Luckperms on a localhost or other server with no external plugins.
