### ISSUE TITLE
Apply LuckPerms to existing Fabric 1.20.1 Server causing server to not start

### ISSUE THREAD

**Issue by dooburt** [LuckPerms/LuckPerms#3839]
### Description

Using: https://modrinth.com/mod/luckperms/version/v5.4.102-fabric on MC1.20.1 (Fabric 0.14.25) on an existing stable server (running Luna Pixel's Prominence II RPG modpack coincidentally). When adding LuckPerms to mods, it causes the server to fail to start with the following:

```
18.02 22:59:26 [Server] [INFO] java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'luckperms'!
18.02 22:59:26 [Server] [INFO] at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:26 [Server] [INFO] at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:26 [Server] [INFO] at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:26 [Server] [INFO] at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:26 [Server] [INFO] at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
18.02 22:59:26 [Server] [INFO] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:26 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:26 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:26 [Server] [INFO] at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:26 [Server] [INFO] Caused by: java.lang.NoClassDefFoundError: me/lucko/fabric/api/permissions/v0/OfflinePermissionCheckEvent
18.02 22:59:26 [Server] [INFO] at me.lucko.luckperms.fabric.listeners.FabricPermissionsApiListener.registerListeners(FabricPermissionsApiListener.java:65) ~[LuckPerms-Fabric-5.4.102.jar:?]
18.02 22:59:26 [Server] [INFO] at me.lucko.luckperms.fabric.LPFabricPlugin.registerFabricListeners(LPFabricPlugin.java:90) ~[LuckPerms-Fabric-5.4.102.jar:?]
18.02 22:59:26 [Server] [INFO] at me.lucko.luckperms.fabric.LPFabricBootstrap.onInitializeServer(LPFabricBootstrap.java:142) ~[LuckPerms-Fabric-5.4.102.jar:?]
18.02 22:59:26 [Server] [INFO] at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:26 [Server] [INFO] ... 6 more
18.02 22:59:26 [Server] [INFO] Caused by: java.lang.ClassNotFoundException: me.lucko.fabric.api.permissions.v0.OfflinePermissionCheckEvent
18.02 22:59:28 [Server] [INFO] at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
18.02 22:59:28 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
18.02 22:59:28 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:28 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:28 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
18.02 22:59:28 [Server] [INFO] at me.lucko.luckperms.fabric.listeners.FabricPermissionsApiListener.registerListeners(FabricPermissionsApiListener.java:65) ~[LuckPerms-Fabric-5.4.102.jar:?]
18.02 22:59:28 [Server] [INFO] at me.lucko.luckperms.fabric.LPFabricPlugin.registerFabricListeners(LPFabricPlugin.java:90) ~[LuckPerms-Fabric-5.4.102.jar:?]
18.02 22:59:28 [Server] [INFO] at me.lucko.luckperms.fabric.LPFabricBootstrap.onInitializeServer(LPFabricBootstrap.java:142) ~[LuckPerms-Fabric-5.4.102.jar:?]
18.02 22:59:28 [Server] [INFO] at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.25.jar:?]
18.02 22:59:28 [Server] [INFO] ... 6 more
```

I'm sure I have done everything correctly and have the correct versions - what is the issue?

### Reproduction Steps

Add `v5.4.102-fabric` to existing Fabric 0.14.25 server. Watch explosions on start.

### Expected Behaviour

To start and LuckPerms to be available.

### Server Details

Fabric 0.14.25, MC 1.20.1

### LuckPerms Version

v5.4.102-fabric

**Comment by BNTFryingPan** [comment]
do you have fabric api?

**Comment by JJeeff248** [comment]
I am having the same issue adding LuckPerms to an existing 1.20.1 server. I am running the BigChadGuys Plus mod pack with cobblemon. I have the fabric api (fabric-api-0.91.0+1.20.1.jar) and I am using the latest LuckPerms (LuckPerms-Fabric-5.4.119.jar)

[servercrash.log](https://github.com/LuckPerms/LuckPerms/files/14325132/servercrash.log)

**Comment by emilyy-dev** [comment]
@dooburt would need to see the whole server latest.log to give a diagnosis, please upload it

**Comment by dooburt** [comment]
I'll need the server to go quiet later today and I'll come back with a log from a full start using LP. Standby!

**Comment by dooburt** [comment]
> do you have fabric api?

Yes: 0.91.0.

**Comment by dooburt** [comment]
As requested: https://mcpaste.io/5a5a7b1a7d28aa46

This was with .88, but the same happens with .119

**Comment by BenjiBag** [comment]
@dooburt 

Any updates, having the exact same issue, on the exact same version, with the same error in log?

**Comment by BenjiBag** [comment]
@dooburt 

I ended up figuring it out. fabric-permissions-api "fabric-permissions-api-v0.2.jar" (https://github.com/lucko/fabric-permissions-api) causes that error... I removed the mod and then it worked perfectly with no issues. Not sure if its just on this version 1.20.1 Fabric but thought i'd just let you know just in case you were still struggling. :-o

**Comment by dooburt** [comment]
@BenjiBag thanks for this. Sorry for the delay, I get huge numbers of notifications from GH. So AFAIK, my Fabric API jar is part of the modpack and required. Are you running Prominence (from Luna)? If you are running a published modpack, what effect did ditching the permission jar have for you?

**Comment by zayne-wang** [comment]
Met the same issue, with full log here:

[latest.log](https://github.com/LuckPerms/LuckPerms/files/14809397/latest.log)

**Comment by BNTFryingPan** [comment]
@zayne-wang please refer to this previous comment

> On Fabric/Forge latest LuckPerms will only work on latest Minecraft. For 1.20.1 you need to use the correct version [listed on Modrinth](https://modrinth.com/mod/luckperms/versions) for that Minecraft version.

**Comment by KEVIN-G386** [comment]
same version [MC 1.20.1 ,fabric 0.14.25]
I fix the problem by using v5.4.102 on [Modrinth](https://modrinth.com/mod/luckperms/versions)
My fabric-api is 0.83.0+1.20.1, maybe you need to downgrade the version of fabricapi
