### ISSUE TITLE
[LuckPerms] Something went wrong whilst upgrading the LuckPerms database. Please report this on GitHub.

### ISSUE THREAD

**Issue by justlead** [LuckPerms/LuckPerms#3852]
### Description

Trobles to update database. I have server on 1.16.5 now and will go to 1.20.4 but this problem :(

### Reproduction Steps

Just setup old LP database and start on last plugin version

### Expected Behaviour

I need to update my database and save all data

### Server Details

Paper 1.20.4

### LuckPerms Version

v5.4.102

### Logs and Configs

[21:09:09] [Server thread/WARN]: [LuckPerms] Something went wrong whilst upgrading the LuckPerms database. Please report this on GitHub.
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory$MigrateH2ToVersion2.getConnection(H2ConnectionFactory.java:170) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory$MigrateH2ToVersion2.run(H2ConnectionFactory.java:135) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.init(H2ConnectionFactory.java:68) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:164) ~[?:?]
	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:115) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:87) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:193) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:50) ~[LuckPerms-Bukkit-5.4.102.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[ssspigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[ssspigot-1.20.4.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[ssspigot-1.20.4.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[ssspigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[ssspigot-1.20.4.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[ssspigot-1.20.4.jar:?]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[ssspigot-1.20.4.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[ssspigot-1.20.4.jar:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[ssspigot-1.20.4.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory$MigrateH2ToVersion2.getConnection(H2ConnectionFactory.java:168) ~[?:?]
	... 18 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617) ~[?:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:194) ~[?:?]
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:205) ~[?:?]
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173) ~[?:?]
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95) ~[?:?]
	at org.h2.engine.Database.getPageStore(Database.java:2739) ~[?:?]
	at org.h2.engine.Database.open(Database.java:769) ~[?:?]
	at org.h2.engine.Database.openDatabase(Database.java:319) ~[?:?]
	at org.h2.engine.Database.<init>(Database.java:313) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:69) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:201) ~[?:?]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:161) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:31) ~[?:?]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148) ~[?:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory$MigrateH2ToVersion2.getConnection(H2ConnectionFactory.java:168) ~[?:?]
	... 18 more
Caused by: java.lang.IllegalStateException: File corrupted in chunk 5608201, expected page length 4..2048, got -803907384 [1.4.199/6]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883) ~[?:?]
	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1055) ~[?:?]
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186) ~[?:?]
	at org.h2.mvstore.MVMap.readPage(MVMap.java:554) ~[?:?]
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086) ~[?:?]
	at org.h2.mvstore.Page.get(Page.java:221) ~[?:?]
	at org.h2.mvstore.MVMap.get(MVMap.java:402) ~[?:?]
	at org.h2.mvstore.MVMap.get(MVMap.java:389) ~[?:?]
	at org.h2.mvstore.MVStore.getChunk(MVStore.java:1088) ~[?:?]
	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1025) ~[?:?]
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186) ~[?:?]
	at org.h2.mvstore.MVMap.readPage(MVMap.java:554) ~[?:?]
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086) ~[?:?]
	at org.h2.mvstore.Cursor.hasNext(Cursor.java:53) ~[?:?]
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:793) ~[?:?]
	at org.h2.mvstore.MVStore.<init>(MVStore.java:401) ~[?:?]
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343) ~[?:?]
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162) ~[?:?]
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95) ~[?:?]
	at org.h2.engine.Database.getPageStore(Database.java:2739) ~[?:?]
	at org.h2.engine.Database.open(Database.java:769) ~[?:?]
	at org.h2.engine.Database.openDatabase(Database.java:319) ~[?:?]
	at org.h2.engine.Database.<init>(Database.java:313) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:69) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:201) ~[?:?]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:161) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:31) ~[?:?]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148) ~[?:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory$MigrateH2ToVersion2.getConnection(H2ConnectionFactory.java:168) ~[?:?]
	... 18 more

**Comment by Laarryy** [comment]
As mentioned in #3676 this can be fixed by export/importing, and perhaps also by incrementally updating LP through major versions.
