### ISSUE TITLE
Crash report from console

### ISSUE THREAD

**Issue by Govno123333** [LuckPerms/LuckPerms#3855]
### Description

[21:07:26 INFO]: [LuckPerms] Loading configuration...
[21:07:27 INFO]: [LuckPerms] Loading storage provider... [H2]
[21:07:27 WARN]: [LuckPerms] [DB Upgrade] Found an old (v1) H2 database file. LuckPerms will now attempt to upgrade it to v2 (this is a one time operation).
[21:07:27 INFO]: [LuckPerms] [DB Upgrade] Stage 1: Exporting the old database to an intermediary file...
[21:07:27 INFO]: [LuckPerms] [DB Upgrade] Stage 2: Importing the intermediary file into the new database...
[21:07:27 WARN]: [LuckPerms] Something went wrong whilst upgrading the LuckPerms database. Please report this on GitHub.
org.h2.jdbc.JdbcSQLSyntaxErrorException: Sequence "SYSTEM_SEQUENCE_31A0FE7F_1347_4E6F_8AA7_EC1E88FA018E" already exists; SQL statement:
            
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_31A0FE7F_1347_4E6F_8AA7_EC1E88FA018E" START WITH 398 BELONGS_TO_TABLE [90035-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:632) ~[?:?]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:223) ~[?:?]
        at org.h2.message.DbException.get(DbException.java:199) ~[?:?]
        at org.h2.command.ddl.CreateSequence.update(CreateSequence.java:53) ~[?:?]
        at org.h2.command.ddl.SchemaOwnerCommand.update(SchemaOwnerCommand.java:33) ~[?:?]
        at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
        at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
        at org.h2.command.dml.RunScriptCommand.execute(RunScriptCommand.java:108) ~[?:?]
        at org.h2.command.dml.RunScriptCommand.update(RunScriptCommand.java:70) ~[?:?]
        at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
        at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252) ~[?:?]
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory$MigrateH2ToVersion2.run(H2ConnectionFactory.java:144) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.init(H2ConnectionFactory.java:68) ~[?:?]
        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:162) ~[?:?]
        at me.lucko.luckperms.common.storage.Storage.init(Storage.java:114) ~[?:?]
        at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:87) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:201) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:50) ~[LuckPerms-Bukkit-5.4.120.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-451]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-451]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-451]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-451]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-451]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-451]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-451]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
        [21:07:28 INFO]: [LuckPerms] Loading internal permission managers...
[21:07:28 INFO]: [LuckPerms] Performing initial data load...
[21:07:28 INFO]: [LuckPerms] Successfully enabled. (took 3317ms)

### Reproduction Steps

I sent everything above and now LuckPerms must help me fix the plagins fault. If it is on me, tell me how to fix that.

### Expected Behaviour

I sent everything above and now LuckPerms must help me fix the plagins fault. If it is on me, tell me how to fix that.

### Server Details

paper-1.20.4-45.jar

### LuckPerms Version

5.4.102

**Comment by ImDarkLaw** [comment]
Quoting Luck on #3676, the suggested course of action here is to:

1. Roll back to the last installed version of LuckPerms that worked, and do a [`/lp export`](https://luckperms.net/wiki/General-Commands#lp-export-file--upload).
2. Stop the server.
3. Delete (create a backup / move it somewhere else) the old database file.
4. Start the server and run [`/lp import`](https://luckperms.net/wiki/General-Commands#lp-import-filecode---upload---replace).

**Comment by Govno123333** [comment]
> Quoting Luck on #3676, the suggested course of action here is to:
> 
> 1. Roll back to the last installed version of LuckPerms that worked, and do a [`/lp export`](https://luckperms.net/wiki/General-Commands#lp-export-file--upload).
> 2. Stop the server.
> 3. Delete (create a backup / move it somewhere else) the old database file.
> 4. Start the server and run [`/lp import`](https://luckperms.net/wiki/General-Commands#lp-import-filecode---upload---replace).

it doesnt work

**Comment by Laarryy** [comment]
Without further information on what it means that it "doesn't work" to follow DarkLaw's steps, I'm going to assume that it was made to work. If it still causes problems, please make a new issue and describe why exporting from old LP/importing to new LP doesn't work.
