### ISSUE TITLE
Exception stopping the server

### ISSUE THREAD

**Issue by Mrgaton** [LuckPerms/LuckPerms#3857]
### Description

[17:41:26] [Server thread/ERROR]: Exception stopping the server
java.util.concurrent.RejectedExecutionException: null
        at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2179) ~[?:?]
        at java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:2196) ~[?:?]
        at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2664) ~[?:?]
        at me.lucko.luckperms.common.plugin.scheduler.SchedulerAdapter.executeAsync(SchedulerAdapter.java:56) ~[LuckPerms-Fabric-5.4.102.jar:?]
        at me.lucko.luckperms.common.plugin.util.AbstractConnectionListener.handleDisconnect(AbstractConnectionListener.java:120) ~[LuckPerms-Fabric-5.4.102.jar:?]
        at me.lucko.luckperms.fabric.listeners.FabricConnectionListener.onDisconnect(FabricConnectionListener.java:135) ~[LuckPerms-Fabric-5.4.102.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$4(ServerPlayConnectionEvents.java:59) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.invokeDisconnectEvent(ServerPlayNetworkAddon.java:136) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
        at net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect(AbstractNetworkAddon.java:131) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
        at net.minecraft.class_3244.handler$zmd001$fabric-networking-api-v1$handleDisconnection(class_3244.java:2007) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_10839(class_3244.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10768(class_2535.java:450) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_19537(class_1255.java:87) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_14367(class_3244.java:356) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14597(class_3324.java:800) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:584) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:537) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:703) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

### Reproduction Steps

use the command stop

### Expected Behaviour

stop the server

### Server Details

fabric 1.20.1

### LuckPerms Version

LuckPerms-Fabric-5.4.102.jar

**Comment by ac101m** [comment]
I'm also seeing this error. 
I've also had instances of entities disappearing off the server when this happens, though this seems to be due to an interaction with another plugin.

**Comment by BNTFryingPan** [comment]
> I've also had instances of entities disappearing off the server when this happens

luckperms does not touch the world, so its incredibly unlikely that luckperms would cause entities to disappear. also you say you are writing a plugin, which implies you are running on a bukkit based platform, where this exact error could not possibly occur. If you are in fact running a bukkit based platform, please open a new issue with the exact error (or ideally a *fully* log, uploaded to a [pastebin](https://pastes.dev))

**Comment by Mrgaton** [comment]
> I'm also seeing this error. I've also had instances of entities disappearing off the server when this happens, though this seems to be due to an interaction with a plugin which I'm writing and could be my fault.

I'm not using plugin's I'm on the fabric version of the mod

**Comment by ac101m** [comment]
> luckperms does not touch the world, so its incredibly unlikely that luckperms would cause entities to disappear. also you say you are writing a plugin, which implies you are running on a bukkit based platform, where this exact error could not possibly occur. If you are in fact running a bukkit based platform, please open a new issue with the exact error (or ideally a _full_ log, uploaded to a [pastebin](https://pastes.dev))

I'm using fabric. The plugin (or mod if you prefer) I mentioned is trivial. It's only function is to create chunk tickets which follow minecarts around the world. Sometimes when this crash occurs, entities tracked by the plugin disappear from the world. It's definitely _correlated_ with the crash, but as neither LP nor my mod modify the state of entities, I suspect that it has more to do with _when_ the crash is occurring than it does what either plugin is actually doing. See [here](https://pastes.dev/9KalzA5nED) for server logs. 

Happy to attempt to reproduce on a clean server if you think that would be helpful.

**Comment by Mrgaton** [comment]
Ok if it crashes again I will upload full crash log and normal logs

**Comment by ac101m** [comment]
Something else I've noticed is that it only ever seems to happen when someone is online. If nobody is on the server when it's stopped, the crash doesn't occur. A workaround might be to kick all players before issuing the stop command.

Another thing that might work is running `save-all` and `save-off` before `stop`, to prevent the crash from interfering with save state (which it seems to do sometimes).

**Comment by willroxby** [comment]
> Something else I've noticed is that it only ever seems to happen when someone is online. If nobody is on the server when it's stopped, the crash doesn't occur. A workaround might be to kick all players before issuing the stop command.
> 
> Another thing that might work is running `save-all` and `save-off` before `stop`, to prevent the crash from interfering with save state (which it seems to do sometimes).

My Forge servers are having this issue as well. Did the above work around have success?

**Comment by willroxby** [comment]
Curious if anyone here managed to find a possible solution to these issues with restarting their server?

**Comment by Skullians** [comment]
I found a temporary fix (not really a fix, deleted the libs folder in luckperms and then started the server and only fixed it for one or two restarts)

**Comment by Alex-Pqn** [comment]
Is there a fix planned for this issue ?

**Comment by creeper12121** [comment]
I met the same issue, please fix it

**Comment by Laarryy** [comment]
To those with this issue: Please upload full server logs to GitHub gists. Make sure your fabric version is correct so you aren't duplicating #3839 

In the absence of full logs and clear reproduction steps (with the _correct_ version of LP for your server's fabric version) this issue will be closed shortly.

**Comment by Skullians** [comment]
We were running latest fabric version which LP was compatible with at the time. We were not running latest mc version due to obvious mod version limitations

**Comment by FunnyShadow** [comment]
https://gist.github.com/FunnyShadow/422cda27377371c89f9f966bcc761880
