### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Mrgaton** [LuckPerms/LuckPerms#3866]
### Description

[18:33:37] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "me.lucko.luckperms.common.webeditor.store.WebEditorStore.sockets()" because "this.webEditorStore" is null
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:262) ~[LuckPerms-Fabric-5.4.102.jar:?]
	at me.lucko.luckperms.fabric.LPFabricBootstrap.onServerStopping(LPFabricBootstrap.java:152) ~[LuckPerms-Fabric-5.4.102.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-d012b44cfa5b8a32.jar:?]
	at net.minecraft.server.MinecraftServer.handler$znk000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:3847) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:537) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:703) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
[18:36:12] [JDA shutdown/INFO]: Stopping scheduled events

### Reproduction Steps

just start the server

### Expected Behaviour

 not crash idk lol

### Server Details

fabric 1.20.1

### LuckPerms Version

v5.4.102

**Comment by ac101m** [comment]
Also seeing this, already been reported actually!
See here: https://github.com/LuckPerms/LuckPerms/issues/3857

**Comment by TH2403y** [comment]
Have you used Azul Zing?

**Comment by Mrgaton** [comment]
No

**Comment by TH2403y** [comment]
When I use a different path of the JDK, it works
