### ISSUE TITLE
Fails to start on Velocity

### ISSUE THREAD

**Issue by TISnoob** [LuckPerms/LuckPerms#3869]
### Description

```[09:31:13 ERROR]: Couldn't pass ProxyInitializeEvent to luckperms 5.4.121
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/adventure/translation/Translator
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:127) ~[?:?]
        at me.lucko.luckperms.velocity.LPVelocityBootstrap.onEnable(LPVelocityBootstrap.java:134) ~[?:?]
        at me.lucko.luckperms.velocity.Lmbda$10.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-374.jar:3.3.0-SNAPSHOT (git-3bce4d85-b374)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-374.jar:3.3.0-SNAPSHOT (git-3bce4d85-b374)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-374.jar:3.3.0-SNAPSHOT (git-3bce4d85-b374)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.adventure.translation.Translator
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.3.0-SNAPSHOT-374.jar:3.3.0-SNAPSHOT (git-3bce4d85-b374)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-374.jar:3.3.0-SNAPSHOT (git-3bce4d85-b374)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 9 more```

### Reproduction Steps

Update your code

### Expected Behaviour

Should run smoothly

### Server Details

velocity-3.3.0-SNAPSHOT-374

### LuckPerms Version

luckperms 5.4.121

### Logs and Configs

_No response_

### Extra Details

_No response_

**Comment by TISnoob** [comment]
Issue fixed. Just deleted plugins/luckperms
