### ISSUE TITLE
Something occured when using the "/lp editor" and the web editor cannot be opened

### ISSUE THREAD

**Issue by fhfzfy1231** [LuckPerms/LuckPerms#3870]
### Description

After the server starts normally and Luckperms shows normal loading, using the command "/lp editor" has no effect and the reason cannot be confirmed.

### Reproduction Steps

Start the server using the mohist-1.18.2-153 core and install plugins CMI-9.6.0.9, CMILib1.4.4.2, LuckPerms Bukkit 5.4.121, ProtocolLib, and Vault-1.7.3. Enable whitelist and enter /lp editor after the server starts normally

### Expected Behaviour

In theory, it should output the website address of the web editor, but the final result is displaying Unable to communicate with the editor Check the console for errors

### Server Details

mohist-1.18.2-153-server

### LuckPerms Version

v5.4.121

### Logs and Configs

> lp editor

[09:27:03 INFO]: [LP] Preparing a new editor session, please wait...
[09:27:13 WARN]: [LuckPerms] Command execution [editor] has not completed. Trace:
  java.base@17.0.10/sun.nio.ch.Net.poll(Native Method)
  java.base@17.0.10/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:186)
  java.base@17.0.10/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:290)
  java.base@17.0.10/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
  java.base@17.0.10/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
  java.base@17.0.10/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
  java.base@17.0.10/java.net.Socket$SocketInputStream.read(Socket.java:966)
  java.base@17.0.10/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
  java.base@17.0.10/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:467)
  java.base@17.0.10/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
  java.base@17.0.10/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
  java.base@17.0.10/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
  java.base@17.0.10/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
  java.base@17.0.10/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
  java.base@17.0.10/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
  java.base@17.0.10/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
  me.lucko.luckperms.lib.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytesocksClient.createSocket(BytesocksClient.java:67)
  me.lucko.luckperms.common.webeditor.socket.WebEditorSocket.initialize(WebEditorSocket.java:88)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createSocket(WebEditorSession.java:94)
  me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:86)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$7843/0x00000277e33ed7d8.run(Unknown Source)
  java.base@17.0.10/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.10/java.lang.Thread.run(Thread.java:842)
[09:27:18 WARN]: [LuckPerms] Unable to establish socket connection
java.io.InterruptedIOException: timeout
        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.timeoutExit(Transmitter.java:109) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:302) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.noMoreExchanges(Transmitter.java:267) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:237) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81) ~[?:?]
        at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47) ~[?:?]
        at me.lucko.luckperms.common.http.BytesocksClient.createSocket(BytesocksClient.java:67) ~[?:?]
        at me.lucko.luckperms.common.webeditor.socket.WebEditorSocket.initialize(WebEditorSocket.java:88) ~[?:?]
        at me.lucko.luckperms.common.webeditor.WebEditorSession.createSocket(WebEditorSession.java:94) ~[?:?]
        at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:86) ~[?:?]
        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110) ~[?:?]
        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55) ~[?:?]
        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47) ~[?:?]
        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279) ~[?:?]
        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.io.IOException: Canceled
        at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:82) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[?:?]
        ... 15 more
[09:27:33 WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[09:27:33 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:210)
[09:27:33 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)
[09:27:33 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)
[09:27:33 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[09:27:33 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
[09:27:33 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
[09:27:33 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
[09:27:33 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
[09:27:33 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[09:27:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:27:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:27:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
[09:27:33 WARN]: Caused by: java.io.InterruptedIOException: timeout
[09:27:33 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.timeoutExit(Transmitter.java:109)
[09:27:33 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:302)
[09:27:33 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Transmitter.noMoreExchanges(Transmitter.java:267)
[09:27:33 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:237)
[09:27:33 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[09:27:33 WARN]:        at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[09:27:33 WARN]:        at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)
[09:27:33 WARN]:        at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)
[09:27:33 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)
[09:27:33 WARN]:        ... 11 more
[09:27:33 WARN]: Caused by: java.io.IOException: Canceled
[09:27:33 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:82)
[09:27:33 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[09:27:33 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[09:27:33 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[09:27:33 WARN]:        ... 16 more
[09:27:33 INFO]: [LP] Unable to communicate with the editor. Check the console for errors.

> lp info

[09:30:23 INFO]: [LP] Running LuckPerms v5.4.121 by Luck.
[09:30:23 INFO]: [LP] -  Platform: Bukkit
[09:30:23 INFO]: [LP] -  Server Brand: Mohist
[09:30:23 INFO]: [LP] -  Server Version:
[09:30:23 INFO]: [LP]      1.18.2-153 (MC: 1.18.2) - 1.18.2-R0.1-SNAPSHOT
[09:30:23 INFO]: [LP] -  Storage:
[09:30:23 INFO]: [LP]      Type: H2
[09:30:23 INFO]: [LP]      File Size: 0.02MB
[09:30:23 INFO]: [LP] -  Extensions:
[09:30:23 INFO]: [LP]      None
[09:30:23 INFO]: [LP] -  Messaging: None
[09:30:23 INFO]: [LP] -  Instance:
[09:30:23 INFO]: [LP]      Static contexts: None
[09:30:23 INFO]: [LP]      Online Players: 0 (0 unique)
[09:30:23 INFO]: [LP]      Uptime: 16m 21s
[09:30:23 INFO]: [LP]      Local Data: 0 users, 1 groups, 0 tracks

**Comment by ImDarkLaw** [comment]
This issue stems from network-related factors affecting your server's connectivity with the web editor servers at `usersockets.luckperms.net`. Given that it's taking an extended period to reach or establish connections with the editor servers, it's likely beyond LuckPerms' control and we'd advise you reach out to your host regarding potential issues with outbound connections on their end.

**Comment by fhfzfy1231** [comment]
Are you saying that my server timed out while trying to connect to the web page editor server? (Please forgive my limited English proficiency, which prevented me from fully understanding).

**Comment by Laarryy** [comment]
Yes. Your server did not connect to the web server properly.
