### ISSUE TITLE
LP Editor unable to communicate with the editor

### ISSUE THREAD

**Issue by OfficialBubbles** [LuckPerms/LuckPerms#3886]
### Description

I am running a 1.20.1 server with luckperms 5.4.128 and get an error when trying to run the editor. Here is the error:

[16:52:25] [luckperms-worker-1/WARN]: [LuckPerms] Command execution [editor] has not completed. Trace:
  java.base@17.0.11/java.lang.Object.wait(Native Method)
  java.base@17.0.11/java.lang.Object.wait(Object.java:338)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:660)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
  me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)
  me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)
  me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$7947/0x00000251822f31e0.run(Unknown Source)
  java.base@17.0.11/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  java.base@17.0.11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.11/java.lang.Thread.run(Thread.java:842)
[16:52:26] [luckperms-command-executor/WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:210)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
[16:52:26] [luckperms-command-executor/WARN]:   at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[16:52:26] [luckperms-command-executor/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:52:26] [luckperms-command-executor/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:52:26] [luckperms-command-executor/WARN]:   at java.base/java.lang.Thread.run(Thread.java:842)
[16:52:26] [luckperms-command-executor/WARN]: Caused by: java.net.SocketTimeoutException: timeout
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)
[16:52:26] [luckperms-command-executor/WARN]:   ... 11 more

### Reproduction Steps

type /lp editor and get error in console

### Expected Behaviour

Should open the link to the editor

### Server Details

Spigot 1.20.1

### LuckPerms Version

v5.4.128

### Logs and Configs

[16:52:25] [luckperms-worker-1/WARN]: [LuckPerms] Command execution [editor] has not completed. Trace:
  java.base@17.0.11/java.lang.Object.wait(Native Method)
  java.base@17.0.11/java.lang.Object.wait(Object.java:338)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:660)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
  me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)
  me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)
  me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$7947/0x00000251822f31e0.run(Unknown Source)
  java.base@17.0.11/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  java.base@17.0.11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.11/java.lang.Thread.run(Thread.java:842)
[16:52:26] [luckperms-command-executor/WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:210)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
[16:52:26] [luckperms-command-executor/WARN]:   at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[16:52:26] [luckperms-command-executor/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:52:26] [luckperms-command-executor/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:52:26] [luckperms-command-executor/WARN]:   at java.base/java.lang.Thread.run(Thread.java:842)
[16:52:26] [luckperms-command-executor/WARN]: Caused by: java.net.SocketTimeoutException: timeout
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)
[16:52:26] [luckperms-command-executor/WARN]:   at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)
[16:52:26] [luckperms-command-executor/WARN]:   ... 11 more

**Comment by p0nx77** [comment]
I am having the exact same issue. running on paper 1.20.4, luckperms ver: v5.4.128.

**Comment by BNTFryingPan** [comment]
please use a pastebin to send logs and stacktraces in the future.

bytebin is down right now so this isnt an issue with LP itself

**Comment by OfficialBubbles** [comment]
> please use a pastebin to send logs and stacktraces in the future.
> 
> bytebin is down right now so this isnt an issue with LP itself

I apologize, I am still new to the use of LP. So this means that there is nothing wrong with my install or anything, just have to wait until the bytebin is back?

**Comment by BNTFryingPan** [comment]
all you can do is wait. the editor command uploads the data to a pastebin (bytebin) and includes the code for the paste in the editor link, but since bytebin is down, that fails and lp throws an error

**Comment by SteveTed0** [comment]
I haveing some issue. I'm useing Paper 1.20.1
![image](https://github.com/LuckPerms/LuckPerms/assets/111440235/6916055f-aa94-49b8-84e2-b1fddacbc498)

**Comment by ldnetwork** [comment]
Same here not working updated the plugin and server too
[02:37:36 WARN]: [LuckPerms] Command execution [editor] has not completed. Trace:
  java.base@17.0.10/java.lang.Object.wait(Native Method)
  java.base@17.0.10/java.lang.Object.wait(Object.java:338)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:660)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
  me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)
  me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)
  me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
  me.lucko.luckperms.common.command.CommandManager$$Lambda$10503/0x000071903daab218.run(Unknown Source)
  java.base@17.0.10/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
[02:37:38 WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[02:37:38 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:210)
[02:37:38 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)
[02:37:38 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)
[02:37:38 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[02:37:38 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)
[02:37:38 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)
[02:37:38 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)
[02:37:38 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)
[02:37:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[02:37:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[02:37:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02:37:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[02:37:38 WARN]: Caused by: java.net.SocketTimeoutException: timeout
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[02:37:38 WARN]:        at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[02:37:38 WARN]:        at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[02:37:38 WARN]:        at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)
[02:37:38 WARN]:        at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)
[02:37:38 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)
[02:37:38 WARN]:        ... 11 more
[02:37:38 INFO]: [LP] Unable to communicate with the editor. Check the console for errors.

**Comment by underscore11code** [comment]
Thank you folks, we're aware, and this is a global problem until such time Luck gets the service running again. Further "I'm affected too" replies are redundant, as everyone is affected. Thank you for your patience.
