### ISSUE TITLE
 [LuckPerms] Command execution [editor] has not completed.

### ISSUE THREAD

**Issue by AndreiFilin** [LuckPerms/LuckPerms#3887]
### Description

[04:57:57 WARN]: [LuckPerms] Command execution [editor, users] has not completed. Trace:

java.base/java.lang.Object.wait0(Native Method)

java.base/java.lang.Object.wait(Object.java:366)

java.base/java.lang.Object.wait(Object.java:339)

me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:660)

me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151)

me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)

me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)

me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)

me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)

me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)

me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)

me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)

me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)

me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)

me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)

me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)

me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)

me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)

me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)

me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)

me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)

me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)

me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)

me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)

me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)

me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)

me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)

me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)

java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)

java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)

java.base/java.lang.Thread.run(Thread.java:1583)

[04:57:57 WARN]: java.lang.RuntimeException: Error uploading data to bytebin

[04:57:57 WARN]: at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:210)

[04:57:57 WARN]: at me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)

[04:57:57 WARN]: at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)

[04:57:57 WARN]: at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)

[04:57:57 WARN]: at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:55)

[04:57:57 WARN]: at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:47)

[04:57:57 WARN]: at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:279)

[04:57:57 WARN]: at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:183)

[04:57:57 WARN]: at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

[04:57:57 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)

[04:57:57 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)

[04:57:57 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)

[04:57:57 WARN]: Caused by: java.net.SocketTimeoutException: timeout

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)

[04:57:57 WARN]: at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)

[04:57:57 WARN]: at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)

[04:57:57 WARN]: at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)

[04:57:57 WARN]: at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)

[04:57:57 WARN]: at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)

[04:57:57 WARN]: ... 11 more

### Reproduction Steps

/lp editor

### Expected Behaviour

web editor

### Server Details

git-Paper-196 (MC: 1.20.1)

### LuckPerms Version

v5.4.121

### Extra Details

LP info

[LP] Running LuckPerms v5.4.121 by Luck.

[LP] - Platform: Bukkit

[LP] - Server Brand: Paper

[LP] - Server Version:

[LP] git-Paper-196 (MC: 1.20.1) - 1.20.1-R0.1-SNAPSHOT

[LP] - Storage:

[LP] Type: YAML

[LP] - Extensions:

[LP] None

[LP] - Messaging: None

[LP] - Instance:

 [LP] Static contexts: None

 [LP] Online Players: 1 (1 unique)

 [LP] Uptime: 16m 57s

 [LP] Local Data: 1 users, 24 groups, 0 tracks

**Comment by ImDarkLaw** [comment]
To avoid cluttering this issue, please use a pastebin to send logs.

Currently, Bytebin (bytebin.lucko.me) is temporarily down affecting access to the LuckPermsWeb. We're fully aware of the situation and have notified Luck about this issue. We expect him to address it as soon as he's able. Will keep you updated when the Web Editor becomes accessible again.
