### ISSUE TITLE
LuckPerms not working with PlaceholderAPI

### ISSUE THREAD

**Issue by SulkyWhale** [LuckPerms/LuckPerms#3900]
### Description

I used /papi ecloud download LuckPerms followed by /papi reload as per the wiki and receive this error: Failed to load expansion class LuckPermsExpansion (Is a dependency missing?)

### Reproduction Steps

Using PlaceholderAPI file PlaceholderAPI-2.11.6.jar and LuckPerms file LuckPerms-Bukkit-5.4.128.jar all in plugins file running /papi ecloud download LuckPerms followed by /papi reload

### Expected Behaviour

[PlaceholderAPI] Placeholder expansion registration initializing...
[PlaceholderAPI] Fetching available expansion information...
[PlaceholderAPI] Successfully registered external expansion: (name of expansion)

### Server Details

paper-496(MC: 1.20.4)

### LuckPerms Version

5.4.128

### Logs and Configs

> papi ecloud download LuckPerms
[18:37:12 INFO]: Successfully downloaded expansion LuckPerms [5.4-R2] to file: Expansion-luckperms.jar
Make sure to type /papi reload to enable your new expansion!
[18:37:12 INFO]: [PlaceholderAPI] Fetching available expansion information...
> papi reload
[18:37:20 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[18:37:20 INFO]: [PlaceholderAPI] Fetching available expansion information...
[18:37:20 INFO]: [PlaceholderAPI] Successfully registered external expansion: essentials [1.5.2]
[18:37:20 ERROR]: [PlaceholderAPI] Failed to load expansion class LuckPermsExpansion (Is a dependency missing?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/placeholders/LPPlaceholderProvider
        at me.lucko.luckperms.placeholders.LuckPermsExpansion.register(LuckPermsExpansion.java:58) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:193) ~[PlaceholderAPI-2.11.6.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:366) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46) ~[PlaceholderAPI-2.11.6.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.placeholders.LPPlaceholderProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 20 more

### Extra Details

I was able to add EssentialsX placeholder using the same method with positive results, working as expected. I am logging this due to placeholderAPI's common issues' page: https://wiki.placeholderapi.com/common-issues/

**Comment by powercasgamer** [comment]
Upload your **full** latest.log to a paste site such as pastes.dev

**Comment by ImDarkLaw** [comment]
> This should work, dropped it in here: https://gist.github.com/SulkyWhale/36730035173135ab878ad0cc96dd7ac2

Follow the steps below to resolve the issue:

1. Stop your server.
2. Delete the `/plugins/LuckPerms/libs/` directory.
3. Restart your server.

**Comment by SulkyWhale** [comment]
I just tried that, it does not work, when starting the server, the directory is added back at line [LuckPerms] Enabling LickPerms v5.4.128, and the error reoccurs
