### ISSUE TITLE
Data truncation: Truncated incorrect DOUBLE value

### ISSUE THREAD

**Issue by zhYue1** [LuckPerms/LuckPerms#3904]
### Description

me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect DOUBLE value: '2024-06-01 14:58:30'
[15:42:44 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[15:42:44 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
[15:42:44 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
[15:42:44 WARN]:        at me.lucko.luckperms.lib.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
[15:42:44 WARN]:        at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[15:42:44 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[15:42:44 WARN]:        at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.runHousekeeping(AbstractSqlMessenger.java:143)
[15:42:44 WARN]:        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[15:42:44 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[15:42:44 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[15:42:44 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[15:42:44 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

### Reproduction Steps

At first, there was no error, the server would report such an error every 30s after a few days of running, due to some old plugin limitations, I was using mysql 5.7.44, and I checked that the type of LP table in the database was varchar

### Expected Behaviour

Fix this error as it makes it difficult for me to see the live output of the server

### Server Details

spigot-1.8.8

### LuckPerms Version

v5.4.102

**Comment by Laarryy** [comment]
Is this still an issue on latest LP? It looks like some other plugin has added info the LP database. Please open a new issue with more detailed logs, and potentially a snippet of your database (whichever table/row has "2024-06-01 14:58:30" instead of a number would be nice).

Closing as not enough info atm.
