### ISSUE TITLE
Fabric PlaceholderAPI not working with luckperms

### ISSUE THREAD

**Issue by MrBeelo** [LuckPerms/LuckPerms#3923]
### Description

When trying to open a server with luckperms and LuckPerms-Fabric-PlaceholderAPI-Hook, the server brings up the following error:

java.lang.IllegalAccessError: class me.lucko.luckperms.placeholders.LuckPermsFabricPlaceholders tried to access private method 'void net.minecraft.class_2960.<init>(java.lang.String, java.lang.String)' (me.lucko.luckperms.placeholders.LuckPermsFabricPlaceholders and net.minecraft.class_2960 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @29ee9faa)
	at me.lucko.luckperms.placeholders.LuckPermsFabricPlaceholders.lambda$registerPlaceholders$2(LuckPermsFabricPlaceholders.java:61)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:297)
	at me.lucko.luckperms.placeholders.LuckPermsFabricPlaceholders.registerPlaceholders(LuckPermsFabricPlaceholders.java:58)
	at me.lucko.luckperms.placeholders.LuckPermsFabricPlaceholders.lambda$onInitialize$0(LuckPermsFabricPlaceholders.java:51)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$zfc000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2642)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1570)

### Reproduction Steps

1) Put LuckPerms-Fabric-5.4.134 and LuckPerms-Fabric-PlaceholderAPI-Hook in your mods folder of your fabric server.
2) Launch the server.

### Expected Behaviour

The server would have opened and the placeholders would have worked.

### Server Details

Fabric Loader 0.15.11

### LuckPerms Version

v5.4.134

### Logs and Configs

https://gist.github.com/MrBeelo/70775574b99ed333c9f4e0e7d8c86239

### Extra Details

I last reproduced the problem at 18/6/2024, however I am pretty sure the problem still exists since someone reported it to the official discord server today.

**Comment by BNTFryingPan** [comment]
i dont think the fabric placeholder thing has been updated for 1.21 yet

**Comment by Rexwel** [comment]
and when should we expect it?

**Comment by Mr-Fussy** [comment]
I am updating from 1.20.4 to 1.21 on fabric vanilla server and can also add that I am getting this error, I suspect as above that the API has not been updated to 1.21. Will monitor to confirm.

**Comment by ev3rest** [comment]
still broken

**Comment by BNTFryingPan** [comment]
please see LuckPerms/Placeholders#58 and LuckPerms/Placeholders#59
