### ISSUE TITLE
display name error

### ISSUE THREAD

**Issue by SK-Koren** [LuckPerms/LuckPerms#3924]
### Description

**i want to upgrade from old version (a year) of db to the latest and getting this error.
I didnt find any solution...**

```
[03:33:26] [Server thread/WARN]: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: display name is empty
[03:33:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[03:33:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[03:33:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
[03:33:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[03:33:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[03:33:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[03:33:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[03:33:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[03:33:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[03:33:26] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: display name is empty
[03:33:26] [Server thread/WARN]: 	at me.lucko.luckperms.common.node.types.DisplayName$Builder.displayName(DisplayName.java:98)
[03:33:26] [Server thread/WARN]: 	at me.lucko.luckperms.common.node.types.DisplayName.parse(DisplayName.java:79)
[03:33:26] [Server thread/WARN]: 	at me.lucko.luckperms.common.node.factory.NodeBuilders.determineMostApplicable(NodeBuilders.java:65)
[03:33:26] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.readNode(SqlStorage.java:818)
[03:33:26] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectAllGroupPermissions(SqlStorage.java:1062)
[03:33:26] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:534)
[03:33:26] [Server thread/WARN]: 	at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:178)
[03:33:26] [Server thread/WARN]: 	at me.lucko.luckperms.common.util.AsyncInterface.lambda$future$1(AsyncInterface.java:61)
[03:33:26] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

```

### Reproduction Steps

upgrade from a year ago version of the luckperms to the latest (with mysql)

### Expected Behaviour

let me upgrade to the latest and not resetting all my db

### Server Details

1.19.4

### LuckPerms Version

latest

**Comment by SK-Koren** [comment]
old version: LuckPerms-Bukkit-5.4.40.jar
