### ISSUE TITLE
Failed to init storage implementation

### ISSUE THREAD

**Issue by jstinson5640** [LuckPerms/LuckPerms#3927]
### Description

Users cannot connect to my lobby due to a database issue

### Reproduction Steps

Starting the server

### Expected Behaviour

The database would be connected and allow players in the server

### Server Details

Paper 1.20.4

### LuckPerms Version

v5.4.134

### Logs and Configs

24.06 21:29:10 [Server] ERROR [luckperms]: Exception occurred whilst enabling SQL messaging service
24.06 21:29:10 [Server] INFO java.lang.RuntimeException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:56) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:263) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:74) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:143) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.velocity.messaging.VelocityMessagingFactory.getServiceFor(VelocityMessagingFactory.java:52) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:102) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:202) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.velocity.LPVelocityBootstrap.onEnable(LPVelocityBootstrap.java:140) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.velocity.Lmbda$9.execute(Unknown Source) ~[?:?]
24.06 21:29:10 [Server] INFO at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[Velocity-Latest.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
24.06 21:29:10 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Velocity-Latest.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
24.06 21:29:10 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Velocity-Latest.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
24.06 21:29:10 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
24.06 21:29:10 [Server] INFO Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:169) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.common.messaging.sql.SqlMessenger.getConnection(SqlMessenger.java:84) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.common.messaging.sql.AbstractSqlMessenger.init(AbstractSqlMessenger.java:60) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.common.messaging.sql.SqlMessenger.init(SqlMessenger.java:54) ~[?:?]
24.06 21:29:10 [Server] INFO ... 14 more
24.06 21:29:10 [Server] INFO Caused by: me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
24.06 21:29:10 [Server] INFO ... 3 more
24.06 21:29:10 [Server] INFO Caused by: me.lucko.luckperms.lib.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
24.06 21:29:10 [Server] INFO at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
24.06 21:29:10 [Server] INFO ... 3 more
24.06 21:29:10 [Server] INFO Caused by: java.net.ConnectException: Connection refused
24.06 21:29:10 [Server] INFO at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[?:?]
24.06 21:29:10 [Server] INFO at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[?:?]
24.06 21:29:10 [Server] INFO at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
24.06 21:29:10 [Server] INFO ... 3 more
24.06 21:29:10 [Server] WARN [luckperms]: Messaging service 'sql' not recognised.
24.06 21:29:10 [Server] INFO [luckperms]: Loading internal permission managers...
24.06 21:29:10 [Server] INFO [luckperms]: Performing initial data load...
24.06 21:29:15 [Server] ERROR java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.common.util.AsyncInterface.lambda$future$1(AsyncInterface.java:66)
24.06 21:29:15 [Server] ERROR at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
24.06 21:29:15 [Server] ERROR at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285)
24.06 21:29:15 [Server] ERROR at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
24.06 21:29:15 [Server] ERROR at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
24.06 21:29:15 [Server] ERROR at java.base/java.lang.Thread.run(Thread.java:1583)
24.06 21:29:15 [Server] ERROR Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:169)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:532)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:178)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.common.util.AsyncInterface.lambda$future$1(AsyncInterface.java:61)
24.06 21:29:15 [Server] ERROR ... 5 more
24.06 21:29:15 [Server] ERROR Caused by: me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
24.06 21:29:15 [Server] ERROR at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
24.06 21:29:15 [Server] ERROR ... 3 more
24.06 21:29:15 [Server] ERROR Caused by: me.lucko.luckperms.lib.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
24.06 21:29:15 [Server] ERROR at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
24.06 21:29:15 [Server] ERROR at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
24.06 21:29:15 [Server] ERROR at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.NativeSession.connect(NativeSession.java:144)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
24.06 21:29:15 [Server] ERROR ... 14 more
24.06 21:29:15 [Server] ERROR Caused by: java.net.ConnectException: Connection refused
24.06 21:29:15 [Server] ERROR at java.base/sun.nio.ch.Net.pollConnect(Native Method)
24.06 21:29:15 [Server] ERROR at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
24.06 21:29:15 [Server] ERROR at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
24.06 21:29:15 [Server] ERROR at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
24.06 21:29:15 [Server] ERROR at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
24.06 21:29:15 [Server] ERROR at java.base/java.net.Socket.connect(Socket.java:751)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
24.06 21:29:15 [Server] ERROR at me.lucko.luckperms.lib.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
24.06 21:29:15 [Server] ERROR ... 17 more

### Extra Details

Server IP: play.orcsworld.net

**Comment by Laarryy** [comment]
This is a configuration issue - this should help: https://luckperms.net/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server
