### ISSUE TITLE
Dependencies could not be loaded

### ISSUE THREAD

**Issue by boringmj** [LuckPerms/LuckPerms#3930]
### Description

The dependency cannot be loaded, resulting in mysql being unable to connect. The following are the configuration and logs

### Reproduction Steps

Config
```
storage-method: mysql
data:
  address: this_mysqlserver_addr
  database: mc_server
  username: mc_server
  password: 'this is password'
  pool-settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 1800000 # 30 minutes
    keepalive-time: 0
    properties:
      useUnicode: true
      characterEncoding: utf8
  table-prefix: 'luckperms_'
  ```
Log
```
[18:32:04] [luckperms-worker-2/WARN]: java.lang.RuntimeException: Unable to load dependency HIKARI
[18:32:04] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.lambda$loadDependencies$2(DependencyManagerImpl.java:148)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[18:32:04] [luckperms-worker-2/WARN]: Caused by: me.lucko.luckperms.common.dependencies.DependencyDownloadException: java.net.ConnectException: Connection timed out: connect
[18:32:04] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:112)
[18:32:04] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:125)
[18:32:04] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:150)
[18:32:04] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.downloadDependency(DependencyManagerImpl.java:189)
[18:32:04] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.loadDependency(DependencyManagerImpl.java:167)
[18:32:04] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.lambda$loadDependencies$2(DependencyManagerImpl.java:146)
[18:32:04] [luckperms-worker-2/WARN]: 	... 6 more
[18:32:04] [luckperms-worker-2/WARN]: Caused by: java.net.ConnectException: Connection timed out: connect
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:589)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:578)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:751)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[18:32:04] [luckperms-worker-2/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[18:32:04] [luckperms-worker-2/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:104)
[18:32:04] [luckperms-worker-2/WARN]: 	... 11 more
[18:32:04] [luckperms-worker-3/WARN]: java.lang.RuntimeException: Unable to load dependency MYSQL_DRIVER
[18:32:04] [luckperms-worker-3/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.lambda$loadDependencies$2(DependencyManagerImpl.java:148)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[18:32:04] [luckperms-worker-3/WARN]: Caused by: me.lucko.luckperms.common.dependencies.DependencyDownloadException: java.net.ConnectException: Connection timed out: connect
[18:32:04] [luckperms-worker-3/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:112)
[18:32:04] [luckperms-worker-3/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:125)
[18:32:04] [luckperms-worker-3/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.download(DependencyRepository.java:150)
[18:32:04] [luckperms-worker-3/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.downloadDependency(DependencyManagerImpl.java:189)
[18:32:04] [luckperms-worker-3/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.loadDependency(DependencyManagerImpl.java:167)
[18:32:04] [luckperms-worker-3/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.lambda$loadDependencies$2(DependencyManagerImpl.java:146)
[18:32:04] [luckperms-worker-3/WARN]: 	... 6 more
[18:32:04] [luckperms-worker-3/WARN]: Caused by: java.net.ConnectException: Connection timed out: connect
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:589)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:578)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:751)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[18:32:04] [luckperms-worker-3/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[18:32:04] [luckperms-worker-3/WARN]: 	at me.lucko.luckperms.common.dependencies.DependencyRepository.downloadRaw(DependencyRepository.java:104)
[18:32:04] [luckperms-worker-3/WARN]: 	... 11 more
[18:32:04] [Server thread/INFO]: [LuckPerms] Loading storage provider... [MYSQL]
[18:32:04] [Server thread/WARN]: [LuckPerms] A NoClassDefFoundError has occurred whilst initialising Hikari. This is likely due to classloading conflicts between other plugins.
[18:32:04] [Server thread/WARN]: [LuckPerms] Please check for other plugins below (and try loading LuckPerms without them installed) before reporting the issue.
[18:32:04] [Server thread/WARN]: [LuckPerms] Class org.slf4j.LoggerFactory has been loaded by: null (java.net.URLClassLoader@4ccabbaa)
[18:32:04] [Server thread/WARN]: [LuckPerms] Class org.slf4j.ILoggerFactory has been loaded by: null (java.net.URLClassLoader@4ccabbaa)
[18:32:04] [Server thread/WARN]: [LuckPerms] Class org.apache.logging.slf4j.Log4jLoggerFactory has been loaded by: null (java.net.URLClassLoader@4ccabbaa)
[18:32:04] [Server thread/WARN]: [LuckPerms] Class org.apache.logging.log4j.spi.LoggerContext has been loaded by: null (java.net.URLClassLoader@4ccabbaa)
[18:32:04] [Server thread/WARN]: [LuckPerms] Class org.apache.logging.log4j.spi.AbstractLoggerAdapter has been loaded by: null (java.net.URLClassLoader@4ccabbaa)
[18:32:04] [Server thread/WARN]: [LuckPerms] Class org.slf4j.helpers.MessageFormatter has been loaded by: null (java.net.URLClassLoader@4ccabbaa)
[18:32:04] [Server thread/ERROR]: Error occurred while enabling LuckPerms v5.4.131 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/hikari/HikariConfig
	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.init(HikariConnectionFactory.java:110) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:162) ~[?:?]
	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:114) ~[?:?]
	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:87) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:201) ~[?:?]
	at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:546) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:460) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:220) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.hikari.HikariConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 16 more
```

### Expected Behaviour

I hope someone can help or tell me what is causing the problem and how to fix it

### Server Details

spigot(MC:1.20.1)

### LuckPerms Version

v.5.4.131

**Comment by boringmj** [comment]
The database address and port, the user and password used are all correct, and other plug-ins on the server can connect normally.

**Comment by Laarryy** [comment]
This is a dependencies issue - delete the LuckPerms/libs folder and let it redownload or get it via one of the methods listed here at the bottom of this page: https://luckperms.net/wiki/FAQ#luckperms-cannot-download-dependencies
