### ISSUE TITLE
Crashing server 1.21/.1 with LuckPerms

### ISSUE THREAD

**Issue by softy-oniguru** [LuckPerms/LuckPerms#3955]
### Description

?

### Reproduction Steps

1. Install LuckPerms

### Expected Behaviour

all plugins crashing with zip file closed, server can't start

### Server Details

Purpur 1.21.1-2286-366af80

### LuckPerms Version

v5.4.139

### Logs and Configs

https://gist.github.com/softy-oniguru/535f232cd71c4ccec96d2dc4c49be9c1

**Comment by BNTFryingPan** [comment]
if *all* your plugins are doing this *on startup* (as opposed to on a reload), i suspect this malware from some other plugin that has injected itself into every jar it can find. if this issue still occurs with other plugins if you remove LP from your plugins folder, then this is **not** an issue with LuckPerms. If it does not occur after removing LP, download the latest version from [the website](https://luckperms.net/download) and send a **full** log (not a partial log)

**Comment by MikeWu597** [comment]
same issue happened

**Comment by MikeWu597** [comment]
[21:26:45] [ForkJoinPool-4-worker-1/ERROR]: [me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache] Exception thrown when performing the maintenance task
java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperSimplePluginClassLoader.findClass(PaperSimplePluginClassLoader.java:62) ~[paper-1.21.jar:1.21-37-dd49fba]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:118) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:187) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.expireAfterAccessEntries(BoundedLocalCache.java:826) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.expireAfterAccessEntries(BoundedLocalCache.java:810) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.expireEntries(BoundedLocalCache.java:790) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1484) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1453) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:3323) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache$PerformCleanupTask.exec(BoundedLocalCache.java:3310) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1310) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[21:26:45] [Server thread/WARN]: [LuckPerms] Unable to pass event ContextUpdateEvent to handler me.lucko.luckperms.bukkit.listeners.BukkitCommandListUpdater$$Lambda/0x00007f87954f7828
java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperSimplePluginClassLoader.findClass(PaperSimplePluginClassLoader.java:62) ~[paper-1.21.jar:1.21-37-dd49fba]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:118) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:187) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:580) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2394) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1940) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2373) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2356) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[?:?]
	at me.lucko.luckperms.lib.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54) ~[?:?]
	at me.lucko.luckperms.bukkit.listeners.BukkitCommandListUpdater.requestUpdate(BukkitCommandListUpdater.java:88) ~[?:?]
	at me.lucko.luckperms.bukkit.listeners.BukkitCommandListUpdater.lambda$onContextUpdate$1(BukkitCommandListUpdater.java:75) ~[?:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at me.lucko.luckperms.bukkit.listeners.BukkitCommandListUpdater.onContextUpdate(BukkitCommandListUpdater.java:75) ~[?:?]
	at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:94) ~[?:?]
	at me.lucko.luckperms.common.event.LuckPermsEventSubscription.invoke(LuckPermsEventSubscription.java:42) ~[?:?]
	at me.lucko.luckperms.lib.eventbus.SimpleEventBus.post(SimpleEventBus.java:107) ~[?:?]
	at me.lucko.luckperms.common.event.AbstractEventBus.post(AbstractEventBus.java:82) ~[?:?]
	at me.lucko.luckperms.common.event.EventDispatcher.post(EventDispatcher.java:128) ~[?:?]
	at me.lucko.luckperms.common.event.EventDispatcher.postSync(EventDispatcher.java:153) ~[?:?]
	at me.lucko.luckperms.common.event.EventDispatcher.dispatchContextUpdate(EventDispatcher.java:182) ~[?:?]
	at me.lucko.luckperms.common.context.manager.ContextManager.signalContextUpdate(ContextManager.java:114) ~[?:?]
	at me.lucko.luckperms.bukkit.context.BukkitPlayerCalculator.onWorldChange(BukkitPlayerCalculator.java:131) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor14.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:1421) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.world.entity.Entity.handlePortal(Entity.java:3112) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.world.entity.Entity.baseTick(Entity.java:854) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:442) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.world.entity.Entity.tick(Entity.java:827) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3077) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.world.entity.player.Player.tick(Player.java:287) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:836) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:346) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.network.Connection.tick(Connection.java:635) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1750) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by BNTFryingPan** [comment]
like i said, if this is still an issue, make a *new* issue with a *full* log (*not* just a stacktrace), uploaded to a [pastebin](https://pastes.dev)
