### ISSUE TITLE
Postgres Connection dropped then re-established

### ISSUE THREAD

**Issue by bszartur69** [LuckPerms/LuckPerms#3976]
### Description

I am using PostgresSQL with Supabase for luckperms and everytime I start the server it starts
spamming the console with these:
[23:11:39 INFO] [luckperms]: Postgres listen/notify connection re-established
[23:11:44 WARN] [luckperms]: Postgres listen/notify connection dropped, trying to re-open the connection
and also

[23:11:44 ERROR]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5001ms.
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[23:11:44 ERROR]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:169)
[23:11:44 ERROR]: 	at me.lucko.luckperms.common.messaging.postgres.PostgresMessenger$NotificationListener.listenAndBind(PostgresMessenger.java:135)
[23:11:44 ERROR]: 	at me.lucko.luckperms.common.messaging.postgres.PostgresMessenger.lambda$checkAndReopenConnection$1(PostgresMessenger.java:117)
[23:11:44 ERROR]: 	at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285)
[23:11:44 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:11:44 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:11:44 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[23:11:44 ERROR]: Caused by: me.lucko.luckperms.lib.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:395)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:327)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.core.SetupQueryRunner.run(SetupQueryRunner.java:55)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.core.v3.ConnectionFactoryImpl.runInitialQueries(ConnectionFactoryImpl.java:918)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:327)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.Driver.makeConnection(Driver.java:443)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.Driver.connect(Driver.java:297)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
[23:11:44 ERROR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[23:11:44 ERROR]: 	... 3 more
[23:11:44 ERROR]: Caused by: java.io.EOFException
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.core.PGStream.receiveChar(PGStream.java:467)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
[23:11:44 ERROR]: 	at me.lucko.luckperms.lib.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[23:11:44 ERROR]: 	... 19 more

### Reproduction Steps

Just start the server and then it starts happening

### Expected Behaviour

Start getting errors and when saving most of the time it gives an error

### Server Details

Server type / version: Velocity, 3.4.0-SNAPSHOT

### LuckPerms Version

v5.4.131.

**Comment by BNTFryingPan** [comment]
are you using this database for any other plugins? do they have connection issues as well, or is it only LP? usually problems like this are caused by problems with network conditions, and not by anything in LP itself
