### ISSUE TITLE
LuckPerms don't generate the files on craftycontroller

### ISSUE THREAD

**Issue by ChrysesCat** [LuckPerms/LuckPerms#3980]
### Description

Literally the title, I can't get luckperms to work in any way shape or form

### Reproduction Steps

put luckperm into the server. that's it that's what I did

### Expected Behaviour

watch the server not loading

### Server Details

Fabric.1.21.1

### LuckPerms Version

5.4.140

### Logs and Configs

Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'luckperms' at 'me.lucko.luckperms.fabric.LPFabricBootstrap'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.16.2.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-1.21.1.jar:1.0.1]
Caused by: java.lang.RuntimeException: Unable to create libs directory
	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.setupCacheDirectory(DependencyManagerImpl.java:223) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.<init>(DependencyManagerImpl.java:77) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.createDependencyManager(AbstractLuckPermsPlugin.java:329) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:123) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at me.lucko.luckperms.fabric.LPFabricBootstrap.onInitializeServer(LPFabricBootstrap.java:134) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.2.jar:?]
	... 7 more
Caused by: java.nio.file.AccessDeniedException: /crafty/servers/12ad2965-2487-495b-a4e6-386e1e9ef595/./mods/luckperms
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438) ~[?:?]
	at java.base/java.nio.file.Files.createDirectory(Files.java:699) ~[?:?]
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]
	at java.base/java.nio.file.Files.createDirectories(Files.java:793) ~[?:?]
	at me.lucko.luckperms.common.util.MoreFiles.createDirectoriesIfNotExists(MoreFiles.java:64) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.setupCacheDirectory(DependencyManagerImpl.java:221) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at me.lucko.luckperms.common.dependencies.DependencyManagerImpl.<init>(DependencyManagerImpl.java:77) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.createDependencyManager(AbstractLuckPermsPlugin.java:329) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.load(AbstractLuckPermsPlugin.java:123) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at me.lucko.luckperms.fabric.LPFabricBootstrap.onInitializeServer(LPFabricBootstrap.java:134) ~[LuckPerms-Fabric-5.4.140%20(1).jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.2.jar:?]
	... 7 more

**Comment by emilyy-dev** [comment]
> `AccessDeniedException: /crafty/servers/12ad2965-2487-495b-a4e6-386e1e9ef595/./mods/luckperms`

LuckPerms needs write access to download some libraries during startup (and to generate the config file, but IIRC that's in another directory). This is usually a one-time operation until a LP update includes library updates (for which it needs to download them again) or the LP config is changed in a way that the mod needs to download another set of libraries (for example, changing the storage type from h2 to mariadb or json).

**Comment by ChrysesCat** [comment]
how do I do that?

**Comment by BNTFryingPan** [comment]
if you are using a server host, ask them
otherwise you should try asking people from crafty controller

**Comment by ChrysesCat** [comment]
> if you are using a server host, ask them otherwise you should try asking people from crafty controller

I tried looking online couldn't find anything

**Comment by BNTFryingPan** [comment]
a server host will have some way to contact them, and crafty controller has a discord server linked on their website
