### ISSUE TITLE
mariadb bug

### ISSUE THREAD

**Issue by Saulencijus10** [LuckPerms/LuckPerms#3988]
### Description

doesnt put info lp editor doesnt work

### Reproduction Steps

adding mariadb info and then loading server

### Expected Behaviour

it works

### Server Details

1.21 papermc

### LuckPerms Version

latest

### Logs and Configs

error: [13:38:16 WARN]: [me.lucko.luckperms.lib.mariadb.message.server.ErrorPacket] Error: 1146-42S02: Table 'saulencijus10_mc.luckperms_tracks' doesn't exist
[13:38:16 WARN]: java.util.concurrent.CompletionException: java.sql.SQLSyntaxErrorException: (conn=204173) Table 'saulencijus10_mc.luckperms_tracks' doesn't exist
[13:38:16 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:103)
[13:38:16 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[13:38:16 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[13:38:16 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[13:38:16 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[13:38:16 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[13:38:16 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[13:38:16 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[13:38:16 WARN]: Caused by: java.sql.SQLSyntaxErrorException: (conn=204173) Table 'saulencijus10_mc.luckperms_tracks' doesn't exist
[13:38:16 WARN]:        at me.lucko.luckperms.lib.mariadb.export.ExceptionFactory.createException(ExceptionFactory.java:282)
[13:38:16 WARN]:        at me.lucko.luckperms.lib.mariadb.export.ExceptionFactory.create(ExceptionFactory.java:370)
[13:38:16 WARN]:        at me.lucko.luckperms.lib.mariadb.message.ClientMessage.readPacket(ClientMessage.java:134)
[13:38:16 WARN]:        at me.lucko.luckperms.lib.mariadb.client.impl.StandardClient.readPacket(StandardClient.java:855)
[13:38:16 WARN]:        at me.lucko.luckperms.lib.mariadb.client.impl.StandardClient.readResults(StandardClient.java:794)
[13:38:16 WARN]:        at me.lucko.luckperms.lib.mariadb.client.impl.StandardClient.readResponse(StandardClient.java:713)
[13:38:16 WARN]:        at me.lucko.luckperms.lib.mariadb.client.impl.StandardClient.execute(StandardClient.java:637)
[13:38:16 WARN]:        at me.lucko.luckperms.lib.mariadb.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95)
[13:38:16 WARN]:        at me.lucko.luckperms.lib.mariadb.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:288)
[13:38:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[13:38:16 WARN]:        at me.lucko.luckperms.lib.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[13:38:16 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.selectTracks(SqlStorage.java:1077)
[13:38:16 WARN]:        at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllTracks(SqlStorage.java:605)
[13:38:16 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$loadAllTracks$18(Storage.java:248)
[13:38:16 WARN]:        at me.lucko.luckperms.common.storage.Storage.lambda$future$1(Storage.java:98)
[13:38:16 WARN]:        ... 7 more

**Comment by Laarryy** [comment]
It is likely that your database user doesn't have permission to create/modify/read tables in the database. Either that or it does but something is overwriting your database and deleting the table after it's created. This does not look like an LP issue but rather one of DB access permissions.
