### ISSUE TITLE
Error (Command execution [editor] has not completed. Trace) in Linux

### ISSUE THREAD

**Issue by jonzesmit** [LuckPerms/LuckPerms#4014]
### Description

[09:33:05] [luckperms-command-executor/INFO]: [LP] Preparing a new editor session, please wait...
[09:33:15] [luckperms-worker-0/WARN]: [LuckPerms] Command execution [editor] has not completed. Trace: 
  java.base/java.lang.Object.wait0(Native Method)
  java.base/java.lang.Object.wait(Object.java:366)
  java.base/java.lang.Object.wait(Object.java:339)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:660)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:151)
  me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
  me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
  me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
  me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
  me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
  me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
  me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
  me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)
  me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)
  me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)
  me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)
  me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)
  me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
  me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
  me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:280)
  me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:184)
  java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  java.base/java.lang.Thread.run(Thread.java:1583)
[09:33:16] [luckperms-command-executor/WARN]: java.lang.RuntimeException: Error uploading data to bytebin
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:210)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.webeditor.WebEditorSession.createInitialSession(WebEditorSession.java:129)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.webeditor.WebEditorSession.open(WebEditorSession.java:87)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:280)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$1(CommandManager.java:184)
[09:33:16] [luckperms-command-executor/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[09:33:16] [luckperms-command-executor/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[09:33:16] [luckperms-command-executor/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[09:33:16] [luckperms-command-executor/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[09:33:16] [luckperms-command-executor/WARN]: Caused by: java.net.SocketTimeoutException: timeout
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.lib.okhttp3.RealCall.execute(RealCall.java:81)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.http.AbstractHttpClient.makeHttpRequest(AbstractHttpClient.java:47)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.http.BytebinClient.makeHttpRequest(BytebinClient.java:76)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.http.BytebinClient.postContent(BytebinClient.java:102)
[09:33:16] [luckperms-command-executor/WARN]: 	at me.lucko.luckperms.common.webeditor.WebEditorSession.uploadRequestData(WebEditorSession.java:205)
[09:33:16] [luckperms-command-executor/WARN]: 	... 11 more
[09:33:16] [luckperms-command-executor/INFO]: [LP] Unable to communicate with the editor. Check the console for errors.

### Reproduction Steps

/lp editor

### Expected Behaviour

web editor

### Server Details

paper-1.21.3-82

### LuckPerms Version

v5.4.151

### Logs and Configs

https://gist.github.com/jonzesmit/c6cf9ceb837448e20969fb121cf8034d

### Extra Details

I only have this problem on Linux server
It works fine on Windows server.

**Comment by BNTFryingPan** [comment]
make sure your server has access to `luckperms.net` and `bytebin.lucko.me`

**Comment by jonzesmit** [comment]
> make sure your server has access to `luckperms.net` and `bytebin.lucko.me`

It pings both of them fine!!

**Comment by Laarryy** [comment]
Is this still an issue? It looks like a networking error more than an internal LP error. Something is making LP think it doesn't have a connection to bytebin - maybe the server doesn't have a connection to the internet, maybe something is preventing your MC server from receiving data from bytebin.

If this is still a problem for you, please do let us know and send more recent stacktraces on latest LP. Closing for now as this stacktrace doesn't immediately indicate a bug in LP itself.
